import type {
  ContractStatus,
  ContractType,
  PaymentStatus,
  PaymentType,
  PaymentMethod,
  DebtStatus,
  DebtSeverity,
  BlockType,
  BlockStatus,
  ExceptionStatus,
  ReconciliationStatus,
  AuditActionType,
  ReportType,
  ReportFormat,
  AlertSeverity,
  Contract,
  ContractPaymentSchedule,
  Payment,
  Debt,
  Block,
  BlockHistoryEntry,
  ReconciliationRecord,
  AuditEntry,
  FinanceReport,
  ImportRecord,
  ImportValidationRow,
  FinanceSettings,
  FinanceDashboardStats,
  ContractStats,
  PaymentStats,
  DebtStats,
  BlockingStats,
  ReconciliationStats,
} from "@/types/accountant";

export type {
  ContractStatus,
  ContractType,
  PaymentStatus,
  PaymentType,
  PaymentMethod,
  DebtStatus,
  DebtSeverity,
  BlockType,
  BlockStatus,
  ExceptionStatus,
  ReconciliationStatus,
  AuditActionType,
  ReportType,
  ReportFormat,
  AlertSeverity,
  Contract,
  ContractPaymentSchedule,
  Payment,
  Debt,
  Block,
  BlockHistoryEntry,
  ReconciliationRecord,
  AuditEntry,
  FinanceReport,
  ImportRecord,
  ImportValidationRow,
  FinanceSettings,
  FinanceDashboardStats,
  ContractStats,
  PaymentStats,
  DebtStats,
  BlockingStats,
  ReconciliationStats,
};

// ─── Mock Data ────────────────────────────────────────────────────────────────

export const mockFinanceStats: FinanceDashboardStats = {
  totalRevenue: 4_850_000,
  outstandingDebts: 320_500,
  pendingPayments: 47,
  activeContracts: 312,
  blockedStudents: 18,
  monthlyCollections: 680_000,
  revenueChangePercent: 8.4,
  lastSyncAt: "2026-03-26T09:15:00Z",
  syncStatus: "Synced",
};

export const mockContractStats: ContractStats = {
  total: 345,
  active: 312,
  expiringSoon: 14,
  totalValue: 8_240_000,
};

export const mockPaymentStats: PaymentStats = {
  totalCollected: 4_850_000,
  pending: 320_500,
  failed: 42_000,
  refunds: 18_500,
};

export const mockDebtStats: DebtStats = {
  totalOutstanding: 320_500,
  overdueAmount: 187_000,
  studentsWithDebt: 43,
  avgDaysOverdue: 22,
};

export const mockBlockingStats: BlockingStats = {
  currentlyBlocked: 18,
  autoBlocked: 13,
  manualBlocks: 5,
  pendingExceptions: 4,
};

export const mockReconciliationStats: ReconciliationStats = {
  totalRecords: 480,
  matched: 461,
  mismatches: 12,
  pendingReview: 7,
};

export const mockContracts: Contract[] = [
  {
    id: "ctr-001",
    contractNumber: "CTR-2025-001",
    studentId: "std-001",
    studentName: "Alina Karimova",
    studentEmail: "a.karimova@student.uou.edu",
    program: "Computer Science",
    faculty: "Engineering",
    type: "Full",
    totalAmount: 18_000,
    paidAmount: 12_000,
    startDate: "2025-09-01",
    endDate: "2026-06-30",
    status: "Active",
    installmentCount: 2,
    nextPaymentDate: "2026-02-01",
    nextPaymentAmount: 6_000,
    notes: "",
    createdAt: "2025-08-20",
    createdBy: "N. Yusupov",
  },
  {
    id: "ctr-002",
    contractNumber: "CTR-2025-002",
    studentId: "std-002",
    studentName: "Bobur Toshmatov",
    studentEmail: "b.toshmatov@student.uou.edu",
    program: "Business Administration",
    faculty: "Economics",
    type: "Partial",
    totalAmount: 14_000,
    paidAmount: 7_000,
    startDate: "2025-09-01",
    endDate: "2026-06-30",
    status: "Active",
    installmentCount: 2,
    nextPaymentDate: "2026-02-01",
    nextPaymentAmount: 7_000,
    notes: "Partial scholarship applied",
    createdAt: "2025-08-21",
    createdBy: "N. Yusupov",
  },
  {
    id: "ctr-003",
    contractNumber: "CTR-2025-003",
    studentId: "std-003",
    studentName: "Dilnoza Rakhimova",
    studentEmail: "d.rakhimova@student.uou.edu",
    program: "Law",
    faculty: "Humanities",
    type: "Grant",
    totalAmount: 0,
    paidAmount: 0,
    startDate: "2025-09-01",
    endDate: "2026-06-30",
    status: "Active",
    installmentCount: 0,
    nextPaymentDate: null,
    nextPaymentAmount: null,
    notes: "State grant recipient",
    createdAt: "2025-08-22",
    createdBy: "N. Yusupov",
  },
  {
    id: "ctr-004",
    contractNumber: "CTR-2025-004",
    studentId: "std-004",
    studentName: "Eldor Nazarov",
    studentEmail: "e.nazarov@student.uou.edu",
    program: "Medicine",
    faculty: "Health Sciences",
    type: "Full",
    totalAmount: 24_000,
    paidAmount: 24_000,
    startDate: "2024-09-01",
    endDate: "2025-06-30",
    status: "Expired",
    installmentCount: 2,
    nextPaymentDate: null,
    nextPaymentAmount: null,
    notes: "",
    createdAt: "2024-08-15",
    createdBy: "S. Mirzayeva",
  },
  {
    id: "ctr-005",
    contractNumber: "CTR-2025-005",
    studentId: "std-005",
    studentName: "Feruza Umarova",
    studentEmail: "f.umarova@student.uou.edu",
    program: "Architecture",
    faculty: "Design",
    type: "Full",
    totalAmount: 16_000,
    paidAmount: 0,
    startDate: "2026-02-01",
    endDate: "2026-06-30",
    status: "Pending",
    installmentCount: 1,
    nextPaymentDate: "2026-02-01",
    nextPaymentAmount: 16_000,
    notes: "Pending signature",
    createdAt: "2026-01-20",
    createdBy: "N. Yusupov",
  },
  {
    id: "ctr-006",
    contractNumber: "CTR-2025-006",
    studentId: "std-006",
    studentName: "Gulsanam Khodjaeva",
    studentEmail: "g.khodjaeva@student.uou.edu",
    program: "Data Science",
    faculty: "Engineering",
    type: "Partial",
    totalAmount: 9_000,
    paidAmount: 4_500,
    startDate: "2025-09-01",
    endDate: "2026-06-30",
    status: "Active",
    installmentCount: 2,
    nextPaymentDate: "2026-03-01",
    nextPaymentAmount: 4_500,
    notes: "",
    createdAt: "2025-08-25",
    createdBy: "N. Yusupov",
  },
  {
    id: "ctr-007",
    contractNumber: "CTR-2024-007",
    studentId: "std-007",
    studentName: "Hamid Ergashev",
    studentEmail: "h.ergashev@student.uou.edu",
    program: "Finance",
    faculty: "Economics",
    type: "Full",
    totalAmount: 15_000,
    paidAmount: 5_000,
    startDate: "2024-09-01",
    endDate: "2025-06-30",
    status: "Terminated",
    installmentCount: 3,
    nextPaymentDate: null,
    nextPaymentAmount: null,
    notes: "Student withdrew from program",
    createdAt: "2024-08-18",
    createdBy: "S. Mirzayeva",
  },
  {
    id: "ctr-008",
    contractNumber: "CTR-2025-008",
    studentId: "std-008",
    studentName: "Iroda Sultanova",
    studentEmail: "i.sultanova@student.uou.edu",
    program: "Marketing",
    faculty: "Economics",
    type: "Full",
    totalAmount: 13_500,
    paidAmount: 9_000,
    startDate: "2025-09-01",
    endDate: "2026-06-30",
    status: "Active",
    installmentCount: 3,
    nextPaymentDate: "2026-04-01",
    nextPaymentAmount: 4_500,
    notes: "",
    createdAt: "2025-08-19",
    createdBy: "N. Yusupov",
  },
];

export const mockPaymentSchedules: ContractPaymentSchedule[] = [
  {
    id: "ps-001",
    contractId: "ctr-001",
    installmentNumber: 1,
    dueDate: "2025-09-01",
    amount: 6_000,
    status: "Completed",
    paidAt: "2025-09-01",
  },
  {
    id: "ps-002",
    contractId: "ctr-001",
    installmentNumber: 2,
    dueDate: "2026-02-01",
    amount: 6_000,
    status: "Completed",
    paidAt: "2026-01-28",
  },
  {
    id: "ps-003",
    contractId: "ctr-002",
    installmentNumber: 1,
    dueDate: "2025-09-01",
    amount: 7_000,
    status: "Completed",
    paidAt: "2025-09-03",
  },
  {
    id: "ps-004",
    contractId: "ctr-002",
    installmentNumber: 2,
    dueDate: "2026-02-01",
    amount: 7_000,
    status: "Pending",
    paidAt: null,
  },
  {
    id: "ps-005",
    contractId: "ctr-006",
    installmentNumber: 1,
    dueDate: "2025-09-01",
    amount: 4_500,
    status: "Completed",
    paidAt: "2025-09-02",
  },
  {
    id: "ps-006",
    contractId: "ctr-006",
    installmentNumber: 2,
    dueDate: "2026-03-01",
    amount: 4_500,
    status: "Pending",
    paidAt: null,
  },
];

export const mockPayments: Payment[] = [
  {
    id: "pay-001",
    paymentNumber: "PAY-2026-0312",
    contractId: "ctr-001",
    contractNumber: "CTR-2025-001",
    studentId: "std-001",
    studentName: "Alina Karimova",
    amount: 6_000,
    type: "Installment",
    method: "Bank Transfer",
    status: "Completed",
    date: "2026-01-28",
    description: "Installment 2 of 2",
    processedBy: "N. Yusupov",
  },
  {
    id: "pay-002",
    paymentNumber: "PAY-2026-0298",
    contractId: "ctr-008",
    contractNumber: "CTR-2025-008",
    studentId: "std-008",
    studentName: "Iroda Sultanova",
    amount: 4_500,
    type: "Installment",
    method: "Card",
    status: "Completed",
    date: "2026-01-25",
    description: "Installment 2 of 3",
    processedBy: "N. Yusupov",
  },
  {
    id: "pay-003",
    paymentNumber: "PAY-2026-0287",
    contractId: "ctr-006",
    contractNumber: "CTR-2025-006",
    studentId: "std-006",
    studentName: "Gulsanam Khodjaeva",
    amount: 4_500,
    type: "Installment",
    method: "Online",
    status: "Pending",
    date: "2026-03-01",
    description: "Installment 2 of 2",
    processedBy: "System",
  },
  {
    id: "pay-004",
    paymentNumber: "PAY-2025-1102",
    contractId: "ctr-003",
    contractNumber: "CTR-2025-003",
    studentId: "std-003",
    studentName: "Dilnoza Rakhimova",
    amount: 0,
    type: "Tuition",
    method: "Bank Transfer",
    status: "Completed",
    date: "2025-09-01",
    description: "Grant — no payment required",
    processedBy: "N. Yusupov",
  },
  {
    id: "pay-005",
    paymentNumber: "PAY-2025-0988",
    contractId: "ctr-007",
    contractNumber: "CTR-2024-007",
    studentId: "std-007",
    studentName: "Hamid Ergashev",
    amount: 5_000,
    type: "Tuition",
    method: "Cash",
    status: "Refunded",
    date: "2025-02-10",
    description: "Refund upon withdrawal",
    processedBy: "S. Mirzayeva",
  },
  {
    id: "pay-006",
    paymentNumber: "PAY-2025-0890",
    contractId: "ctr-002",
    contractNumber: "CTR-2025-002",
    studentId: "std-002",
    studentName: "Bobur Toshmatov",
    amount: 7_000,
    type: "Installment",
    method: "Bank Transfer",
    status: "Completed",
    date: "2025-09-03",
    description: "Installment 1 of 2",
    processedBy: "N. Yusupov",
  },
  {
    id: "pay-007",
    paymentNumber: "PAY-2025-0855",
    contractId: "ctr-001",
    contractNumber: "CTR-2025-001",
    studentId: "std-001",
    studentName: "Alina Karimova",
    amount: 6_000,
    type: "Installment",
    method: "Card",
    status: "Completed",
    date: "2025-09-01",
    description: "Installment 1 of 2",
    processedBy: "N. Yusupov",
  },
  {
    id: "pay-008",
    paymentNumber: "PAY-2026-0321",
    contractId: "ctr-005",
    contractNumber: "CTR-2025-005",
    studentId: "std-005",
    studentName: "Feruza Umarova",
    amount: 16_000,
    type: "Tuition",
    method: "Bank Transfer",
    status: "Failed",
    date: "2026-02-01",
    description: "Payment failed — insufficient funds",
    processedBy: "System",
  },
  {
    id: "pay-009",
    paymentNumber: "PAY-2026-0305",
    contractId: "ctr-008",
    contractNumber: "CTR-2025-008",
    studentId: "std-008",
    studentName: "Iroda Sultanova",
    amount: 250,
    type: "Fine",
    method: "Online",
    status: "Completed",
    date: "2026-02-15",
    description: "Late payment penalty",
    processedBy: "System",
  },
  {
    id: "pay-010",
    paymentNumber: "PAY-2025-0920",
    contractId: "ctr-008",
    contractNumber: "CTR-2025-008",
    studentId: "std-008",
    studentName: "Iroda Sultanova",
    amount: 4_500,
    type: "Installment",
    method: "Card",
    status: "Completed",
    date: "2025-09-10",
    description: "Installment 1 of 3",
    processedBy: "N. Yusupov",
  },
];

export const mockDebts: Debt[] = [
  {
    id: "debt-001",
    studentId: "std-002",
    studentName: "Bobur Toshmatov",
    studentEmail: "b.toshmatov@student.uou.edu",
    contractId: "ctr-002",
    contractNumber: "CTR-2025-002",
    program: "Business Administration",
    amount: 7_000,
    dueDate: "2026-02-01",
    daysOverdue: 53,
    status: "Overdue",
    severity: "Critical",
    lastReminderDate: "2026-03-01",
    notes: "Second reminder sent",
  },
  {
    id: "debt-002",
    studentId: "std-005",
    studentName: "Feruza Umarova",
    studentEmail: "f.umarova@student.uou.edu",
    contractId: "ctr-005",
    contractNumber: "CTR-2025-005",
    program: "Architecture",
    amount: 16_000,
    dueDate: "2026-02-01",
    daysOverdue: 53,
    status: "Overdue",
    severity: "Critical",
    lastReminderDate: "2026-03-10",
    notes: "Payment failed, contract pending",
  },
  {
    id: "debt-003",
    studentId: "std-006",
    studentName: "Gulsanam Khodjaeva",
    studentEmail: "g.khodjaeva@student.uou.edu",
    contractId: "ctr-006",
    contractNumber: "CTR-2025-006",
    program: "Data Science",
    amount: 4_500,
    dueDate: "2026-03-01",
    daysOverdue: 25,
    status: "Overdue",
    severity: "High",
    lastReminderDate: "2026-03-15",
    notes: "",
  },
  {
    id: "debt-004",
    studentId: "std-009",
    studentName: "Jasur Mirzaev",
    studentEmail: "j.mirzaev@student.uou.edu",
    contractId: "ctr-009",
    contractNumber: "CTR-2025-009",
    program: "Physics",
    amount: 8_000,
    dueDate: "2026-03-15",
    daysOverdue: 11,
    status: "Outstanding",
    severity: "High",
    lastReminderDate: null,
    notes: "",
  },
  {
    id: "debt-005",
    studentId: "std-010",
    studentName: "Kamola Yusupova",
    studentEmail: "k.yusupova@student.uou.edu",
    contractId: "ctr-010",
    contractNumber: "CTR-2025-010",
    program: "Linguistics",
    amount: 3_200,
    dueDate: "2026-03-20",
    daysOverdue: 6,
    status: "PartiallyPaid",
    severity: "Medium",
    lastReminderDate: "2026-03-21",
    notes: "Made partial payment of 1,800",
  },
  {
    id: "debt-006",
    studentId: "std-011",
    studentName: "Lola Hasanova",
    studentEmail: "l.hasanova@student.uou.edu",
    contractId: "ctr-011",
    contractNumber: "CTR-2025-011",
    program: "Psychology",
    amount: 5_500,
    dueDate: "2026-04-01",
    daysOverdue: 0,
    status: "Outstanding",
    severity: "Low",
    lastReminderDate: null,
    notes: "",
  },
  {
    id: "debt-007",
    studentId: "std-007",
    studentName: "Hamid Ergashev",
    studentEmail: "h.ergashev@student.uou.edu",
    contractId: "ctr-007",
    contractNumber: "CTR-2024-007",
    program: "Finance",
    amount: 10_000,
    dueDate: "2025-10-01",
    daysOverdue: 0,
    status: "WrittenOff",
    severity: "Low",
    lastReminderDate: "2025-09-01",
    notes: "Written off after withdrawal settlement",
  },
  {
    id: "debt-008",
    studentId: "std-012",
    studentName: "Mansur Tursunov",
    studentEmail: "m.tursunov@student.uou.edu",
    contractId: "ctr-012",
    contractNumber: "CTR-2025-012",
    program: "Civil Engineering",
    amount: 6_300,
    dueDate: "2026-03-10",
    daysOverdue: 16,
    status: "Overdue",
    severity: "High",
    lastReminderDate: "2026-03-20",
    notes: "",
  },
];

export const mockBlocks: Block[] = [
  {
    id: "blk-001",
    studentId: "std-002",
    studentName: "Bobur Toshmatov",
    studentEmail: "b.toshmatov@student.uou.edu",
    program: "Business Administration",
    reason: "Overdue payment — 53 days",
    blockDate: "2026-03-15",
    type: "Auto",
    status: "Active",
    exceptionStatus: "None",
    blockedBy: "System",
    debtAmount: 7_000,
  },
  {
    id: "blk-002",
    studentId: "std-005",
    studentName: "Feruza Umarova",
    studentEmail: "f.umarova@student.uou.edu",
    program: "Architecture",
    reason: "Failed payment, contract unpaid",
    blockDate: "2026-03-10",
    type: "Auto",
    status: "Active",
    exceptionStatus: "Pending",
    blockedBy: "System",
    debtAmount: 16_000,
  },
  {
    id: "blk-003",
    studentId: "std-006",
    studentName: "Gulsanam Khodjaeva",
    studentEmail: "g.khodjaeva@student.uou.edu",
    program: "Data Science",
    reason: "Overdue payment — 25 days",
    blockDate: "2026-03-20",
    type: "Auto",
    status: "Active",
    exceptionStatus: "None",
    blockedBy: "System",
    debtAmount: 4_500,
  },
  {
    id: "blk-004",
    studentId: "std-013",
    studentName: "Nilufar Razzaqova",
    studentEmail: "n.razzaqova@student.uou.edu",
    program: "Chemistry",
    reason: "Repeated late payments",
    blockDate: "2026-02-28",
    type: "Manual",
    status: "Active",
    exceptionStatus: "None",
    blockedBy: "N. Yusupov",
    debtAmount: 9_000,
  },
  {
    id: "blk-005",
    studentId: "std-012",
    studentName: "Mansur Tursunov",
    studentEmail: "m.tursunov@student.uou.edu",
    program: "Civil Engineering",
    reason: "Overdue payment — 16 days",
    blockDate: "2026-03-22",
    type: "Auto",
    status: "Active",
    exceptionStatus: "Approved",
    blockedBy: "System",
    debtAmount: 6_300,
  },
];

export const mockBlockHistory: BlockHistoryEntry[] = [
  {
    id: "bh-001",
    studentId: "std-014",
    studentName: "Otabek Sobirov",
    action: "Unblocked",
    type: "Auto",
    reason: "Payment received in full",
    date: "2026-03-24",
    actor: "N. Yusupov",
  },
  {
    id: "bh-002",
    studentId: "std-002",
    studentName: "Bobur Toshmatov",
    action: "Blocked",
    type: "Auto",
    reason: "Overdue payment — 53 days",
    date: "2026-03-15",
    actor: "System",
  },
  {
    id: "bh-003",
    studentId: "std-015",
    studentName: "Parizod Jurayeva",
    action: "Unblocked",
    type: "Manual",
    reason: "Exception approved by Academic Dept",
    date: "2026-03-12",
    actor: "S. Mirzayeva",
  },
  {
    id: "bh-004",
    studentId: "std-013",
    studentName: "Nilufar Razzaqova",
    action: "Blocked",
    type: "Manual",
    reason: "Repeated late payments",
    date: "2026-02-28",
    actor: "N. Yusupov",
  },
  {
    id: "bh-005",
    studentId: "std-005",
    studentName: "Feruza Umarova",
    action: "Blocked",
    type: "Auto",
    reason: "Failed payment, contract unpaid",
    date: "2026-03-10",
    actor: "System",
  },
  {
    id: "bh-006",
    studentId: "std-016",
    studentName: "Qodir Ismoilov",
    action: "Unblocked",
    type: "Auto",
    reason: "Debt fully settled",
    date: "2026-03-05",
    actor: "System",
  },
  {
    id: "bh-007",
    studentId: "std-012",
    studentName: "Mansur Tursunov",
    action: "Blocked",
    type: "Auto",
    reason: "Overdue payment — 16 days",
    date: "2026-03-22",
    actor: "System",
  },
  {
    id: "bh-008",
    studentId: "std-017",
    studentName: "Rohila Ahmedova",
    action: "Unblocked",
    type: "Manual",
    reason: "Payment plan agreed",
    date: "2026-02-20",
    actor: "N. Yusupov",
  },
];

export const mockReconciliationRecords: ReconciliationRecord[] = [
  {
    id: "rec-001",
    recordNumber: "REC-2026-001",
    studentId: "std-001",
    studentName: "Alina Karimova",
    contractNumber: "CTR-2025-001",
    lmsAmount: 12_000,
    oneCAmount: 12_000,
    difference: 0,
    status: "Matched",
    lastCheckedAt: "2026-03-26T09:15:00Z",
    resolvedBy: null,
    resolvedAt: null,
    notes: "",
  },
  {
    id: "rec-002",
    recordNumber: "REC-2026-002",
    studentId: "std-002",
    studentName: "Bobur Toshmatov",
    contractNumber: "CTR-2025-002",
    lmsAmount: 7_000,
    oneCAmount: 6_800,
    difference: 200,
    status: "Mismatch",
    lastCheckedAt: "2026-03-26T09:15:00Z",
    resolvedBy: null,
    resolvedAt: null,
    notes: "Bank fee discrepancy",
  },
  {
    id: "rec-003",
    recordNumber: "REC-2026-003",
    studentId: "std-006",
    studentName: "Gulsanam Khodjaeva",
    contractNumber: "CTR-2025-006",
    lmsAmount: 4_500,
    oneCAmount: 4_500,
    difference: 0,
    status: "Matched",
    lastCheckedAt: "2026-03-26T09:15:00Z",
    resolvedBy: null,
    resolvedAt: null,
    notes: "",
  },
  {
    id: "rec-004",
    recordNumber: "REC-2026-004",
    studentId: "std-008",
    studentName: "Iroda Sultanova",
    contractNumber: "CTR-2025-008",
    lmsAmount: 9_250,
    oneCAmount: 9_000,
    difference: 250,
    status: "Mismatch",
    lastCheckedAt: "2026-03-26T09:15:00Z",
    resolvedBy: null,
    resolvedAt: null,
    notes: "Fine not recorded in 1C",
  },
  {
    id: "rec-005",
    recordNumber: "REC-2026-005",
    studentId: "std-012",
    studentName: "Mansur Tursunov",
    contractNumber: "CTR-2025-012",
    lmsAmount: 0,
    oneCAmount: 500,
    difference: -500,
    status: "Mismatch",
    lastCheckedAt: "2026-03-26T09:15:00Z",
    resolvedBy: null,
    resolvedAt: null,
    notes: "Phantom entry in 1C",
  },
  {
    id: "rec-006",
    recordNumber: "REC-2026-006",
    studentId: "std-003",
    studentName: "Dilnoza Rakhimova",
    contractNumber: "CTR-2025-003",
    lmsAmount: 0,
    oneCAmount: 0,
    difference: 0,
    status: "Matched",
    lastCheckedAt: "2026-03-26T09:15:00Z",
    resolvedBy: null,
    resolvedAt: null,
    notes: "Grant — zero amount",
  },
  {
    id: "rec-007",
    recordNumber: "REC-2026-007",
    studentId: "std-018",
    studentName: "Sarvar Nizomov",
    contractNumber: "CTR-2025-018",
    lmsAmount: 8_000,
    oneCAmount: 8_000,
    difference: 0,
    status: "Pending",
    lastCheckedAt: "2026-03-26T09:15:00Z",
    resolvedBy: null,
    resolvedAt: null,
    notes: "Awaiting 1C confirmation",
  },
  {
    id: "rec-008",
    recordNumber: "REC-2026-008",
    studentId: "std-019",
    studentName: "Tabassum Ergasheva",
    contractNumber: "CTR-2025-019",
    lmsAmount: 13_500,
    oneCAmount: 13_500,
    difference: 0,
    status: "Matched",
    lastCheckedAt: "2026-03-26T09:15:00Z",
    resolvedBy: null,
    resolvedAt: null,
    notes: "",
  },
];

export const mockAuditEntries: AuditEntry[] = [
  {
    id: "aud-001",
    timestamp: "2026-03-26T09:15:00Z",
    userId: "usr-finance-01",
    userName: "N. Yusupov",
    action: "SyncTriggered",
    entityType: "System",
    entityId: "sync-001",
    entityLabel: "1C Reconciliation Sync",
    details: "Manual sync triggered. 480 records processed, 12 mismatches found.",
    severity: "info",
  },
  {
    id: "aud-002",
    timestamp: "2026-03-25T14:32:00Z",
    userId: "usr-finance-01",
    userName: "N. Yusupov",
    action: "StudentBlocked",
    entityType: "Student",
    entityId: "std-012",
    entityLabel: "Mansur Tursunov",
    details: "Auto-block triggered: overdue payment 16 days.",
    severity: "warning",
  },
  {
    id: "aud-003",
    timestamp: "2026-03-24T11:10:00Z",
    userId: "usr-finance-01",
    userName: "N. Yusupov",
    action: "StudentUnblocked",
    entityType: "Student",
    entityId: "std-014",
    entityLabel: "Otabek Sobirov",
    details: "Unblocked after full payment received.",
    severity: "success",
  },
  {
    id: "aud-004",
    timestamp: "2026-03-23T16:45:00Z",
    userId: "usr-finance-02",
    userName: "S. Mirzayeva",
    action: "ContractCreated",
    entityType: "Contract",
    entityId: "ctr-008",
    entityLabel: "CTR-2025-008",
    details: "New contract created for Iroda Sultanova — Marketing, Full type, 13,500.",
    severity: "info",
  },
  {
    id: "aud-005",
    timestamp: "2026-03-22T10:00:00Z",
    userId: "usr-finance-01",
    userName: "N. Yusupov",
    action: "PaymentRecorded",
    entityType: "Payment",
    entityId: "pay-002",
    entityLabel: "PAY-2026-0298",
    details: "Payment of 4,500 recorded for Iroda Sultanova — Installment 2 of 3.",
    severity: "info",
  },
  {
    id: "aud-006",
    timestamp: "2026-03-21T09:30:00Z",
    userId: "system",
    userName: "System",
    action: "DebtCreated",
    entityType: "Debt",
    entityId: "debt-003",
    entityLabel: "Gulsanam Khodjaeva",
    details: "Debt of 4,500 auto-generated after missed installment due 2026-03-01.",
    severity: "warning",
  },
  {
    id: "aud-007",
    timestamp: "2026-03-20T15:20:00Z",
    userId: "usr-finance-01",
    userName: "N. Yusupov",
    action: "ReportGenerated",
    entityType: "Report",
    entityId: "rpt-005",
    entityLabel: "Revenue Report Q1 2026",
    details: "Revenue report for Q1 2026 generated in PDF format.",
    severity: "info",
  },
  {
    id: "aud-008",
    timestamp: "2026-03-18T11:55:00Z",
    userId: "usr-finance-02",
    userName: "S. Mirzayeva",
    action: "ContractTerminated",
    entityType: "Contract",
    entityId: "ctr-007",
    entityLabel: "CTR-2024-007",
    details: "Contract terminated for Hamid Ergashev — student withdrew from program.",
    severity: "danger",
  },
  {
    id: "aud-009",
    timestamp: "2026-03-15T08:00:00Z",
    userId: "system",
    userName: "System",
    action: "StudentBlocked",
    entityType: "Student",
    entityId: "std-002",
    entityLabel: "Bobur Toshmatov",
    details: "Auto-block triggered: overdue payment 53 days.",
    severity: "danger",
  },
  {
    id: "aud-010",
    timestamp: "2026-03-10T13:40:00Z",
    userId: "usr-finance-01",
    userName: "N. Yusupov",
    action: "SettingsUpdated",
    entityType: "Settings",
    entityId: "settings-01",
    entityLabel: "Finance Settings",
    details: "Late penalty changed from 2% to 3%. Grace period updated to 5 days.",
    severity: "warning",
  },
  {
    id: "aud-011",
    timestamp: "2026-03-08T10:15:00Z",
    userId: "usr-finance-02",
    userName: "S. Mirzayeva",
    action: "ExceptionGranted",
    entityType: "Student",
    entityId: "std-015",
    entityLabel: "Parizod Jurayeva",
    details: "Block exception approved. Academic Dept coordination ref: ACD-2026-043.",
    severity: "info",
  },
  {
    id: "aud-012",
    timestamp: "2026-03-05T16:30:00Z",
    userId: "system",
    userName: "System",
    action: "StudentUnblocked",
    entityType: "Student",
    entityId: "std-016",
    entityLabel: "Qodir Ismoilov",
    details: "Auto-unblocked: debt fully settled.",
    severity: "success",
  },
];

export const mockReportHistory: FinanceReport[] = [
  {
    id: "rpt-005",
    type: "Revenue",
    period: "Q1 2026",
    format: "PDF",
    generatedAt: "2026-03-20T15:20:00Z",
    generatedBy: "N. Yusupov",
    fileSize: "1.2 MB",
    status: "Ready",
  },
  {
    id: "rpt-004",
    type: "Debt",
    period: "March 2026",
    format: "Excel",
    generatedAt: "2026-03-15T10:00:00Z",
    generatedBy: "S. Mirzayeva",
    fileSize: "0.8 MB",
    status: "Ready",
  },
  {
    id: "rpt-003",
    type: "PaymentCollection",
    period: "February 2026",
    format: "PDF",
    generatedAt: "2026-03-01T09:00:00Z",
    generatedBy: "N. Yusupov",
    fileSize: "2.1 MB",
    status: "Ready",
  },
  {
    id: "rpt-002",
    type: "ContractSummary",
    period: "2025–2026 Academic Year",
    format: "Excel",
    generatedAt: "2026-02-10T14:30:00Z",
    generatedBy: "S. Mirzayeva",
    fileSize: "1.5 MB",
    status: "Ready",
  },
  {
    id: "rpt-001",
    type: "Reconciliation",
    period: "January 2026",
    format: "PDF",
    generatedAt: "2026-02-01T11:00:00Z",
    generatedBy: "N. Yusupov",
    fileSize: "0.6 MB",
    status: "Ready",
  },
];

export const mockImportHistory: ImportRecord[] = [
  {
    id: "imp-001",
    fileName: "contracts_spring_2026.xlsx",
    importedAt: "2026-01-25T10:30:00Z",
    importedBy: "N. Yusupov",
    totalRows: 52,
    validRows: 50,
    errorRows: 2,
    status: "PartialSuccess",
  },
  {
    id: "imp-002",
    fileName: "contracts_fall_2025.xlsx",
    importedAt: "2025-08-20T09:00:00Z",
    importedBy: "S. Mirzayeva",
    totalRows: 298,
    validRows: 298,
    errorRows: 0,
    status: "Completed",
  },
  {
    id: "imp-003",
    fileName: "contracts_grants_2025.xlsx",
    importedAt: "2025-08-22T14:15:00Z",
    importedBy: "N. Yusupov",
    totalRows: 45,
    validRows: 45,
    errorRows: 0,
    status: "Completed",
  },
];

export const mockImportValidationPreview: ImportValidationRow[] = [
  {
    rowNumber: 1,
    studentName: "Anora Bekova",
    studentId: "STD-2026-101",
    program: "Computer Science",
    amount: "18000",
    status: "Valid",
  },
  {
    rowNumber: 2,
    studentName: "Bahodir Normatov",
    studentId: "STD-2026-102",
    program: "Business Administration",
    amount: "14000",
    status: "Valid",
  },
  {
    rowNumber: 3,
    studentName: "Charos Saidova",
    studentId: "",
    program: "Law",
    amount: "16000",
    status: "Error",
    errorDetails: "Student ID is required",
  },
  {
    rowNumber: 4,
    studentName: "Doniyor Xasanov",
    studentId: "STD-2026-104",
    program: "Unknown Program",
    amount: "12000",
    status: "Error",
    errorDetails: "Program not found in system",
  },
  {
    rowNumber: 5,
    studentName: "Ezgulik Yuldasheva",
    studentId: "STD-2026-105",
    program: "Architecture",
    amount: "20000",
    status: "Valid",
  },
];

export const mockFinanceSettings: FinanceSettings = {
  paymentMethods: ["Card", "Bank Transfer", "Online"],
  paymentDeadlineDays: 30,
  latePenaltyPercent: 3,
  autoBlockEnabled: true,
  autoBlockThresholdDays: 14,
  gracePeriodDays: 5,
  defaultInstallmentCount: 2,
  minDownPaymentPercent: 30,
  lateInstallmentPenaltyPercent: 2,
  syncFrequency: "daily",
  autoResolveThreshold: 100,
  notificationEmail: "finance@uou.edu",
  paymentReminderTemplate:
    "Dear {student_name}, this is a reminder that your payment of {amount} is due on {due_date}. Please ensure timely payment to avoid penalties.",
  overdueNoticeTemplate:
    "Dear {student_name}, your payment of {amount} is now {days_overdue} days overdue. Please settle your debt immediately to avoid account suspension.",
  blockNotificationTemplate:
    "Dear {student_name}, your account has been blocked due to outstanding debt of {amount}. Please contact the Finance Department to resolve this issue.",
};
