import type {
  ActiveSession,
  AdminDashboardStats,
  Backup,
  BlockedIP,
  DisasterRecoveryPlan,
  Integration,
  LogsPageStats,
  MaintenanceStats,
  MonitoringStats,
  ReportsStats,
  RoleDefinition,
  SecurityEvent,
  SecurityStats,
  ServiceHealth,
  SupportStats,
  SupportTicket,
  SystemConfigItem,
  SystemLog,
  SystemMetric,
  SystemReport,
  SystemUser,
  UserManagementStats,
} from "@/types/admin";

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const mockAdminDashboardStats: AdminDashboardStats = {
  totalUsers: 1248,
  activeUsers: 1104,
  activeSessions: 87,
  systemUptime: 99.8,
  errorRate: 0.3,
  avgResponseTime: 142,
  pendingTickets: 7,
  securityAlerts: 2,
};

// ─── Users ────────────────────────────────────────────────────────────────────

export const mockUserStats: UserManagementStats = {
  totalUsers: 1248,
  activeUsers: 1104,
  suspendedUsers: 12,
  pendingUsers: 34,
  newUsersThisMonth: 56,
  twoFactorAdoption: 72,
};

export const mockSystemUsers: SystemUser[] = [
  {
    id: "u1",
    fullName: "Alisher Karimov",
    email: "a.karimov@uni.edu",
    role: "admin",
    status: "Active",
    lastLogin: "2026-03-26T08:14:00Z",
    createdAt: "2023-09-01",
    department: "IT",
    twoFactorEnabled: true,
  },
  {
    id: "u2",
    fullName: "Malika Yusupova",
    email: "m.yusupova@uni.edu",
    role: "deputy",
    status: "Active",
    lastLogin: "2026-03-26T07:55:00Z",
    createdAt: "2023-09-01",
    department: "Administration",
    twoFactorEnabled: true,
  },
  {
    id: "u3",
    fullName: "Bobur Toshmatov",
    email: "b.toshmatov@uni.edu",
    role: "teacher",
    status: "Active",
    lastLogin: "2026-03-25T17:32:00Z",
    createdAt: "2023-09-05",
    department: "Computer Science",
    twoFactorEnabled: false,
  },
  {
    id: "u4",
    fullName: "Dilnoza Ergasheva",
    email: "d.ergasheva@uni.edu",
    role: "student",
    status: "Active",
    lastLogin: "2026-03-26T06:10:00Z",
    createdAt: "2024-02-15",
    department: "Economics",
    twoFactorEnabled: false,
  },
  {
    id: "u5",
    fullName: "Jasur Mirzayev",
    email: "j.mirzayev@uni.edu",
    role: "accountant",
    status: "Active",
    lastLogin: "2026-03-26T09:00:00Z",
    createdAt: "2023-10-10",
    department: "Finance",
    twoFactorEnabled: true,
  },
  {
    id: "u6",
    fullName: "Nargiza Holmatova",
    email: "n.holmatova@uni.edu",
    role: "academic",
    status: "Active",
    lastLogin: "2026-03-25T14:20:00Z",
    createdAt: "2023-09-03",
    department: "Academic Affairs",
    twoFactorEnabled: true,
  },
  {
    id: "u7",
    fullName: "Otabek Sobirov",
    email: "o.sobirov@uni.edu",
    role: "student",
    status: "Suspended",
    lastLogin: "2026-03-10T11:00:00Z",
    createdAt: "2024-03-01",
    department: "Mathematics",
    twoFactorEnabled: false,
  },
  {
    id: "u8",
    fullName: "Feruza Nazarova",
    email: "f.nazarova@uni.edu",
    role: "aqad",
    status: "Active",
    lastLogin: "2026-03-26T08:45:00Z",
    createdAt: "2023-11-01",
    department: "Quality Assurance",
    twoFactorEnabled: true,
  },
  {
    id: "u9",
    fullName: "Sardor Yuldashev",
    email: "s.yuldashev@uni.edu",
    role: "resource",
    status: "Active",
    lastLogin: "2026-03-25T16:30:00Z",
    createdAt: "2023-09-15",
    department: "HR",
    twoFactorEnabled: false,
  },
  {
    id: "u10",
    fullName: "Zulfiya Rakhimova",
    email: "z.rakhimova@uni.edu",
    role: "applicant",
    status: "Pending",
    lastLogin: null,
    createdAt: "2026-03-20",
    department: "—",
    twoFactorEnabled: false,
  },
  {
    id: "u11",
    fullName: "Kamol Ismoilov",
    email: "k.ismoilov@uni.edu",
    role: "teacher",
    status: "Inactive",
    lastLogin: "2026-02-01T09:00:00Z",
    createdAt: "2023-09-05",
    department: "Physics",
    twoFactorEnabled: false,
  },
  {
    id: "u12",
    fullName: "Umida Xasanova",
    email: "u.xasanova@uni.edu",
    role: "it-ops",
    status: "Active",
    lastLogin: "2026-03-26T07:00:00Z",
    createdAt: "2023-09-01",
    department: "IT",
    twoFactorEnabled: true,
  },
  {
    id: "u13",
    fullName: "Ravshan Qodirov",
    email: "r.qodirov@uni.edu",
    role: "student",
    status: "Active",
    lastLogin: "2026-03-26T05:55:00Z",
    createdAt: "2024-09-01",
    department: "Law",
    twoFactorEnabled: false,
  },
  {
    id: "u14",
    fullName: "Barno Tursunova",
    email: "b.tursunova@uni.edu",
    role: "applicant",
    status: "Pending",
    lastLogin: null,
    createdAt: "2026-03-22",
    department: "—",
    twoFactorEnabled: false,
  },
  {
    id: "u15",
    fullName: "Mansur Abdullayev",
    email: "m.abdullayev@uni.edu",
    role: "student",
    status: "Suspended",
    lastLogin: "2026-03-05T10:20:00Z",
    createdAt: "2024-02-20",
    department: "Engineering",
    twoFactorEnabled: false,
  },
];

// ─── Roles ────────────────────────────────────────────────────────────────────

export const mockRoleDefinitions: RoleDefinition[] = [
  {
    id: "r1",
    role: "admin",
    label: "Admin",
    userCount: 3,
    isSystem: true,
    description: "Full system access with audit logging on all actions",
    permissions: [
      { module: "users", access: ["read", "write", "delete", "admin"] },
      { module: "courses", access: ["read", "write", "delete", "admin"] },
      { module: "finance", access: ["read", "write", "admin"] },
      { module: "reports", access: ["read", "write", "admin"] },
      { module: "settings", access: ["read", "write", "admin"] },
      { module: "integrations", access: ["read", "write", "admin"] },
      { module: "logs", access: ["read", "admin"] },
      { module: "security", access: ["read", "write", "admin"] },
    ],
  },
  {
    id: "r2",
    role: "deputy",
    label: "Deputy Director",
    userCount: 2,
    isSystem: true,
    description: "Strategic oversight: KPIs, analytics, performance monitoring",
    permissions: [
      { module: "users", access: ["read"] },
      { module: "courses", access: ["read"] },
      { module: "finance", access: ["read"] },
      { module: "reports", access: ["read", "write"] },
      { module: "settings", access: ["read"] },
      { module: "integrations", access: ["read"] },
      { module: "logs", access: ["read"] },
      { module: "security", access: ["read"] },
    ],
  },
  {
    id: "r3",
    role: "teacher",
    label: "Teacher",
    userCount: 148,
    isSystem: true,
    description: "Manage courses, assignments, grades, and student attendance",
    permissions: [
      { module: "users", access: ["read"] },
      { module: "courses", access: ["read", "write"] },
      { module: "finance", access: [] },
      { module: "reports", access: ["read"] },
      { module: "settings", access: [] },
      { module: "integrations", access: [] },
      { module: "logs", access: [] },
      { module: "security", access: [] },
    ],
  },
  {
    id: "r4",
    role: "student",
    label: "Student",
    userCount: 876,
    isSystem: true,
    description: "Access courses, submit assignments, view grades",
    permissions: [
      { module: "users", access: [] },
      { module: "courses", access: ["read"] },
      { module: "finance", access: ["read"] },
      { module: "reports", access: [] },
      { module: "settings", access: [] },
      { module: "integrations", access: [] },
      { module: "logs", access: [] },
      { module: "security", access: [] },
    ],
  },
  {
    id: "r5",
    role: "academic",
    label: "Academic Department",
    userCount: 12,
    isSystem: true,
    description: "Manage programs, groups, schedules, and admission",
    permissions: [
      { module: "users", access: ["read", "write"] },
      { module: "courses", access: ["read", "write", "delete"] },
      { module: "finance", access: ["read"] },
      { module: "reports", access: ["read", "write"] },
      { module: "settings", access: ["read"] },
      { module: "integrations", access: ["read"] },
      { module: "logs", access: ["read"] },
      { module: "security", access: [] },
    ],
  },
  {
    id: "r6",
    role: "accountant",
    label: "Finance",
    userCount: 8,
    isSystem: true,
    description: "Manage contracts, payments, debts, and financial reports",
    permissions: [
      { module: "users", access: ["read"] },
      { module: "courses", access: [] },
      { module: "finance", access: ["read", "write", "admin"] },
      { module: "reports", access: ["read", "write"] },
      { module: "settings", access: [] },
      { module: "integrations", access: ["read"] },
      { module: "logs", access: ["read"] },
      { module: "security", access: [] },
    ],
  },
  {
    id: "r7",
    role: "aqad",
    label: "AQAD",
    userCount: 6,
    isSystem: true,
    description: "Quality assurance, audits, complaints and standards",
    permissions: [
      { module: "users", access: ["read"] },
      { module: "courses", access: ["read"] },
      { module: "finance", access: [] },
      { module: "reports", access: ["read", "write"] },
      { module: "settings", access: ["read"] },
      { module: "integrations", access: [] },
      { module: "logs", access: ["read"] },
      { module: "security", access: [] },
    ],
  },
  {
    id: "r8",
    role: "resource",
    label: "Resource Department",
    userCount: 5,
    isSystem: true,
    description: "Manage teacher assignments, workload, and replacements",
    permissions: [
      { module: "users", access: ["read", "write"] },
      { module: "courses", access: ["read"] },
      { module: "finance", access: [] },
      { module: "reports", access: ["read"] },
      { module: "settings", access: [] },
      { module: "integrations", access: [] },
      { module: "logs", access: [] },
      { module: "security", access: [] },
    ],
  },
  {
    id: "r9",
    role: "applicant",
    label: "Applicant",
    userCount: 184,
    isSystem: true,
    description: "Apply to programs, upload documents, take admission exams",
    permissions: [
      { module: "users", access: [] },
      { module: "courses", access: [] },
      { module: "finance", access: [] },
      { module: "reports", access: [] },
      { module: "settings", access: [] },
      { module: "integrations", access: [] },
      { module: "logs", access: [] },
      { module: "security", access: [] },
    ],
  },
  {
    id: "r10",
    role: "it-ops",
    label: "IT Operations",
    userCount: 4,
    isSystem: true,
    description: "System monitoring, releases, backups, and infrastructure",
    permissions: [
      { module: "users", access: ["read"] },
      { module: "courses", access: [] },
      { module: "finance", access: [] },
      { module: "reports", access: ["read"] },
      { module: "settings", access: ["read", "write"] },
      { module: "integrations", access: ["read", "write"] },
      { module: "logs", access: ["read", "admin"] },
      { module: "security", access: ["read", "write"] },
    ],
  },
];

// ─── Logs ─────────────────────────────────────────────────────────────────────

export const mockLogsStats: LogsPageStats = {
  totalLogs24h: 3842,
  errors24h: 14,
  warnings24h: 67,
  criticalEvents: 2,
};

export const mockSystemLogs: SystemLog[] = [
  {
    id: "l1",
    timestamp: "2026-03-26T09:12:44Z",
    level: "critical",
    source: "Auth",
    message: "Multiple failed login attempts from suspicious IP",
    userId: null,
    userName: null,
    ipAddress: "185.220.101.45",
    details: "25 failed attempts within 5 minutes",
  },
  {
    id: "l2",
    timestamp: "2026-03-26T09:08:11Z",
    level: "error",
    source: "Integration",
    message: "1C sync failed: connection timeout",
    userId: "u5",
    userName: "Jasur Mirzayev",
    ipAddress: "10.0.1.5",
    details: "Timeout after 30s — retrying in 15 minutes",
  },
  {
    id: "l3",
    timestamp: "2026-03-26T09:05:33Z",
    level: "warning",
    source: "Database",
    message: "Slow query detected: reports.generateMonthlyFinance",
    userId: null,
    userName: null,
    ipAddress: "10.0.0.2",
    details: "Query executed in 4.2s (threshold: 2s)",
  },
  {
    id: "l4",
    timestamp: "2026-03-26T09:01:20Z",
    level: "info",
    source: "Auth",
    message: "User login successful",
    userId: "u1",
    userName: "Alisher Karimov",
    ipAddress: "192.168.1.100",
    details: "Login from Tashkent, Uzbekistan",
  },
  {
    id: "l5",
    timestamp: "2026-03-26T08:58:55Z",
    level: "info",
    source: "Scheduler",
    message: "Daily backup job completed successfully",
    userId: null,
    userName: null,
    ipAddress: "10.0.0.1",
    details: "Backup size: 14.2 GB — stored to S3",
  },
  {
    id: "l6",
    timestamp: "2026-03-26T08:50:17Z",
    level: "warning",
    source: "API",
    message: "Rate limit approaching for /api/reports endpoint",
    userId: null,
    userName: null,
    ipAddress: "10.0.0.1",
    details: "Current: 850/1000 requests per minute",
  },
  {
    id: "l7",
    timestamp: "2026-03-26T08:45:02Z",
    level: "error",
    source: "System",
    message: "Disk usage exceeded 85% on /var/data",
    userId: null,
    userName: null,
    ipAddress: "10.0.0.1",
    details: "Current usage: 86.3% — cleanup recommended",
  },
  {
    id: "l8",
    timestamp: "2026-03-26T08:40:30Z",
    level: "info",
    source: "Auth",
    message: "Password changed successfully",
    userId: "u3",
    userName: "Bobur Toshmatov",
    ipAddress: "192.168.1.45",
    details: "Password reset via email verification",
  },
  {
    id: "l9",
    timestamp: "2026-03-26T08:35:10Z",
    level: "critical",
    source: "System",
    message: "Unauthorized access attempt to /admin/system-config",
    userId: "u4",
    userName: "Dilnoza Ergasheva",
    ipAddress: "192.168.2.10",
    details: "Access denied — insufficient privileges (student role)",
  },
  {
    id: "l10",
    timestamp: "2026-03-26T08:30:44Z",
    level: "info",
    source: "Integration",
    message: "Teams webhook registered successfully",
    userId: "u1",
    userName: "Alisher Karimov",
    ipAddress: "192.168.1.100",
    details: "Webhook URL: https://teams.microsoft.com/webhook/...",
  },
  {
    id: "l11",
    timestamp: "2026-03-26T08:25:05Z",
    level: "warning",
    source: "Auth",
    message: "Session expired for inactive user",
    userId: "u9",
    userName: "Sardor Yuldashev",
    ipAddress: "192.168.1.78",
    details: "Session idle for 30 minutes — auto-terminated",
  },
  {
    id: "l12",
    timestamp: "2026-03-26T08:20:00Z",
    level: "info",
    source: "System",
    message: "System health check passed",
    userId: null,
    userName: null,
    ipAddress: "10.0.0.1",
    details: "All 8 services reporting healthy status",
  },
  {
    id: "l13",
    timestamp: "2026-03-26T08:15:33Z",
    level: "error",
    source: "API",
    message: "Failed to send email notification",
    userId: null,
    userName: null,
    ipAddress: "10.0.0.1",
    details: "SMTP connection refused — retrying",
  },
  {
    id: "l14",
    timestamp: "2026-03-26T08:10:00Z",
    level: "info",
    source: "Auth",
    message: "2FA enabled by user",
    userId: "u6",
    userName: "Nargiza Holmatova",
    ipAddress: "192.168.1.55",
    details: "TOTP authenticator configured successfully",
  },
  {
    id: "l15",
    timestamp: "2026-03-26T08:05:22Z",
    level: "warning",
    source: "Database",
    message: "Connection pool near capacity",
    userId: null,
    userName: null,
    ipAddress: "10.0.0.2",
    details: "90/100 connections in use",
  },
];

// ─── Integrations & System Config ─────────────────────────────────────────────

export const mockIntegrations: Integration[] = [
  {
    id: "i1",
    name: "Teams",
    status: "Connected",
    lastSync: "2026-03-26T09:00:00Z",
    nextSync: "2026-03-26T10:00:00Z",
    recordsSynced: 1248,
    errorCount: 0,
    endpoint: "https://graph.microsoft.com/v1.0",
    description: "Microsoft Teams for online lectures and communications",
  },
  {
    id: "i2",
    name: "Classmate",
    status: "Connected",
    lastSync: "2026-03-26T08:30:00Z",
    nextSync: "2026-03-26T09:30:00Z",
    recordsSynced: 876,
    errorCount: 1,
    endpoint: "https://api.classmate.uz/v2",
    description: "Student-teacher interaction and assignment platform",
  },
  {
    id: "i3",
    name: "1C",
    status: "Error",
    lastSync: "2026-03-26T07:00:00Z",
    nextSync: "2026-03-26T09:15:00Z",
    recordsSynced: 0,
    errorCount: 3,
    endpoint: "https://1c.uni.edu/api",
    description: "Accounting system for financial data synchronization",
  },
  {
    id: "i4",
    name: "aSc",
    status: "Connected",
    lastSync: "2026-03-26T06:00:00Z",
    nextSync: "2026-03-26T18:00:00Z",
    recordsSynced: 324,
    errorCount: 0,
    endpoint: "https://asc.uni.edu/export",
    description: "Schedule management and timetable generation",
  },
  {
    id: "i5",
    name: "SMTP",
    status: "Disconnected",
    lastSync: null,
    nextSync: null,
    recordsSynced: 0,
    errorCount: 5,
    endpoint: "smtp.uni.edu:587",
    description: "Email delivery service for notifications",
  },
  {
    id: "i6",
    name: "SMS Gateway",
    status: "Connected",
    lastSync: "2026-03-26T08:00:00Z",
    nextSync: null,
    recordsSynced: 142,
    errorCount: 0,
    endpoint: "https://sms.eskiz.uz/api",
    description: "SMS notifications for critical alerts and OTP",
  },
];

export const mockSystemConfig: SystemConfigItem[] = [
  {
    id: "c1",
    key: "site.name",
    value: "Unified Online University",
    category: "General",
    description: "Platform display name shown in the UI and emails",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c2",
    key: "site.url",
    value: "https://lms.uni.edu",
    category: "General",
    description: "Base URL of the platform",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c3",
    key: "site.timezone",
    value: "Asia/Tashkent",
    category: "General",
    description: "Default timezone for all date/time display",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c4",
    key: "site.language",
    value: "en",
    category: "General",
    description: "Default platform language",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c5",
    key: "email.host",
    value: "smtp.uni.edu",
    category: "Email",
    description: "SMTP server hostname",
    lastModified: "2026-02-10",
    modifiedBy: "Umida Xasanova",
    isSecret: false,
  },
  {
    id: "c6",
    key: "email.port",
    value: "587",
    category: "Email",
    description: "SMTP server port (587 for TLS)",
    lastModified: "2026-02-10",
    modifiedBy: "Umida Xasanova",
    isSecret: false,
  },
  {
    id: "c7",
    key: "email.password",
    value: "smtp_password_here",
    category: "Email",
    description: "SMTP authentication password",
    lastModified: "2026-02-10",
    modifiedBy: "Umida Xasanova",
    isSecret: true,
  },
  {
    id: "c8",
    key: "security.session_timeout",
    value: "30",
    category: "Security",
    description: "Session timeout in minutes after inactivity",
    lastModified: "2026-03-01",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c9",
    key: "security.max_login_attempts",
    value: "5",
    category: "Security",
    description: "Max failed login attempts before account lock",
    lastModified: "2026-03-01",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c10",
    key: "security.require_2fa",
    value: "false",
    category: "Security",
    description: "Enforce 2FA for all admin and staff accounts",
    lastModified: "2026-03-01",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c11",
    key: "security.jwt_secret",
    value: "jwt_secret_key_here",
    category: "Security",
    description: "JWT signing secret key",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: true,
  },
  {
    id: "c12",
    key: "limits.max_upload_size",
    value: "50",
    category: "Limits",
    description: "Maximum file upload size in MB",
    lastModified: "2026-02-20",
    modifiedBy: "Umida Xasanova",
    isSecret: false,
  },
  {
    id: "c13",
    key: "limits.max_students_per_group",
    value: "30",
    category: "Limits",
    description: "Maximum students per academic group",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c14",
    key: "scheduling.backup_frequency",
    value: "24",
    category: "Scheduling",
    description: "Automatic backup frequency in hours",
    lastModified: "2026-03-10",
    modifiedBy: "Umida Xasanova",
    isSecret: false,
  },
  {
    id: "c15",
    key: "scheduling.log_retention",
    value: "90",
    category: "Scheduling",
    description: "Log retention period in days",
    lastModified: "2026-03-10",
    modifiedBy: "Umida Xasanova",
    isSecret: false,
  },
  {
    id: "c16",
    key: "storage.provider",
    value: "S3",
    category: "Storage",
    description: "File storage provider (S3, local, GCS)",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c17",
    key: "storage.bucket",
    value: "uni-lms-files",
    category: "Storage",
    description: "S3 bucket name for file storage",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: false,
  },
  {
    id: "c18",
    key: "storage.access_key",
    value: "AKIAIOSFODNN7EXAMPLE",
    category: "Storage",
    description: "S3 access key ID",
    lastModified: "2026-01-15",
    modifiedBy: "Alisher Karimov",
    isSecret: true,
  },
];

// ─── Monitoring ───────────────────────────────────────────────────────────────

export const mockMonitoringStats: MonitoringStats = {
  cpuUsage: 42,
  memoryUsage: 68,
  diskUsage: 86,
  activeConnections: 87,
  requestsPerMinute: 324,
  avgResponseTime: 142,
};

export const mockServiceHealth: ServiceHealth[] = [
  {
    id: "s1",
    name: "Web Application",
    status: "Healthy",
    uptime: 99.98,
    responseTime: 124,
    lastChecked: "2026-03-26T09:12:00Z",
    cpuUsage: 38,
    memoryUsage: 62,
    errorRate: 0.1,
  },
  {
    id: "s2",
    name: "API Gateway",
    status: "Healthy",
    uptime: 99.95,
    responseTime: 88,
    lastChecked: "2026-03-26T09:12:00Z",
    cpuUsage: 45,
    memoryUsage: 55,
    errorRate: 0.2,
  },
  {
    id: "s3",
    name: "Database (PostgreSQL)",
    status: "Degraded",
    uptime: 99.80,
    responseTime: 420,
    lastChecked: "2026-03-26T09:12:00Z",
    cpuUsage: 72,
    memoryUsage: 88,
    errorRate: 0.8,
  },
  {
    id: "s4",
    name: "Redis Cache",
    status: "Healthy",
    uptime: 100,
    responseTime: 2,
    lastChecked: "2026-03-26T09:12:00Z",
    cpuUsage: 12,
    memoryUsage: 34,
    errorRate: 0.0,
  },
  {
    id: "s5",
    name: "File Storage",
    status: "Degraded",
    uptime: 99.50,
    responseTime: 560,
    lastChecked: "2026-03-26T09:12:00Z",
    cpuUsage: 25,
    memoryUsage: 92,
    errorRate: 1.2,
  },
  {
    id: "s6",
    name: "Email Service",
    status: "Down",
    uptime: 95.20,
    responseTime: 0,
    lastChecked: "2026-03-26T09:12:00Z",
    cpuUsage: 0,
    memoryUsage: 0,
    errorRate: 100,
  },
  {
    id: "s7",
    name: "Auth Service",
    status: "Healthy",
    uptime: 99.99,
    responseTime: 45,
    lastChecked: "2026-03-26T09:12:00Z",
    cpuUsage: 22,
    memoryUsage: 40,
    errorRate: 0.0,
  },
  {
    id: "s8",
    name: "Scheduler",
    status: "Healthy",
    uptime: 99.90,
    responseTime: 210,
    lastChecked: "2026-03-26T09:12:00Z",
    cpuUsage: 18,
    memoryUsage: 30,
    errorRate: 0.1,
  },
];

export const mockSystemMetrics: SystemMetric[] = Array.from(
  { length: 24 },
  (_, i) => ({
    timestamp: `${String(i).padStart(2, "0")}:00`,
    cpuUsage: Math.round(30 + Math.random() * 40),
    memoryUsage: Math.round(55 + Math.random() * 25),
    diskUsage: Math.round(82 + Math.random() * 6),
    activeConnections: Math.round(40 + Math.random() * 80),
    requestsPerMinute: Math.round(150 + Math.random() * 300),
  }),
);

// ─── Backup & Maintenance ─────────────────────────────────────────────────────

export const mockMaintenanceStats: MaintenanceStats = {
  lastBackup: "2026-03-26T02:00:00Z",
  backupSuccessRate: 96.7,
  totalBackupSize: "142.8 GB",
  drPlansVerified: 3,
  drPlansTotal: 4,
  nextScheduledBackup: "2026-03-27T02:00:00Z",
  failedBackups: 1,
};

export const mockBackups: Backup[] = [
  {
    id: "b1",
    type: "Full",
    status: "Completed",
    startedAt: "2026-03-26T02:00:00Z",
    completedAt: "2026-03-26T02:47:00Z",
    size: "14.2 GB",
    location: "s3://uni-lms-backups/2026-03-26/",
    initiatedBy: "Scheduler",
    retentionDays: 30,
  },
  {
    id: "b2",
    type: "Incremental",
    status: "Completed",
    startedAt: "2026-03-25T14:00:00Z",
    completedAt: "2026-03-25T14:08:00Z",
    size: "1.4 GB",
    location: "s3://uni-lms-backups/2026-03-25-inc/",
    initiatedBy: "Scheduler",
    retentionDays: 7,
  },
  {
    id: "b3",
    type: "Full",
    status: "Completed",
    startedAt: "2026-03-25T02:00:00Z",
    completedAt: "2026-03-25T02:51:00Z",
    size: "14.1 GB",
    location: "s3://uni-lms-backups/2026-03-25/",
    initiatedBy: "Scheduler",
    retentionDays: 30,
  },
  {
    id: "b4",
    type: "Incremental",
    status: "Failed",
    startedAt: "2026-03-24T14:00:00Z",
    completedAt: null,
    size: "—",
    location: "—",
    initiatedBy: "Scheduler",
    retentionDays: 7,
  },
  {
    id: "b5",
    type: "Full",
    status: "Completed",
    startedAt: "2026-03-24T02:00:00Z",
    completedAt: "2026-03-24T02:44:00Z",
    size: "13.9 GB",
    location: "s3://uni-lms-backups/2026-03-24/",
    initiatedBy: "Scheduler",
    retentionDays: 30,
  },
  {
    id: "b6",
    type: "Differential",
    status: "Completed",
    startedAt: "2026-03-23T10:00:00Z",
    completedAt: "2026-03-23T10:22:00Z",
    size: "4.8 GB",
    location: "s3://uni-lms-backups/2026-03-23-diff/",
    initiatedBy: "Alisher Karimov",
    retentionDays: 14,
  },
  {
    id: "b7",
    type: "Full",
    status: "Scheduled",
    startedAt: "2026-03-27T02:00:00Z",
    completedAt: null,
    size: "—",
    location: "s3://uni-lms-backups/2026-03-27/",
    initiatedBy: "Scheduler",
    retentionDays: 30,
  },
];

export const mockDisasterRecoveryPlans: DisasterRecoveryPlan[] = [
  {
    id: "dr1",
    name: "Database Failure Recovery",
    lastTested: "2026-02-15",
    rtoMinutes: 30,
    rpoMinutes: 60,
    status: "Verified",
  },
  {
    id: "dr2",
    name: "Full System Restore",
    lastTested: "2026-01-20",
    rtoMinutes: 120,
    rpoMinutes: 240,
    status: "Verified",
  },
  {
    id: "dr3",
    name: "DDoS Response Plan",
    lastTested: "2026-03-01",
    rtoMinutes: 15,
    rpoMinutes: 0,
    status: "Verified",
  },
  {
    id: "dr4",
    name: "Data Breach Containment",
    lastTested: "2025-11-10",
    rtoMinutes: 60,
    rpoMinutes: 120,
    status: "NeedsTesting",
  },
];

// ─── Security ─────────────────────────────────────────────────────────────────

export const mockSecurityStats: SecurityStats = {
  failedLogins24h: 47,
  blockedIPs: 5,
  activeSessions: 87,
  twoFactorAdoption: 72,
  securityEvents24h: 124,
  suspiciousActivities: 2,
};

export const mockSecurityEvents: SecurityEvent[] = [
  {
    id: "se1",
    type: "SuspiciousActivity",
    timestamp: "2026-03-26T09:12:44Z",
    userId: null,
    userName: null,
    ipAddress: "185.220.101.45",
    userAgent: "curl/7.68.0",
    details: "25 login attempts in 5 minutes — possible brute force",
    severity: "danger",
  },
  {
    id: "se2",
    type: "SuspiciousActivity",
    timestamp: "2026-03-26T08:35:10Z",
    userId: "u4",
    userName: "Dilnoza Ergasheva",
    ipAddress: "192.168.2.10",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    details: "Attempted to access admin-only endpoint",
    severity: "danger",
  },
  {
    id: "se3",
    type: "IPBlocked",
    timestamp: "2026-03-26T09:13:00Z",
    userId: null,
    userName: null,
    ipAddress: "185.220.101.45",
    userAgent: "curl/7.68.0",
    details: "Automatically blocked after brute force detection",
    severity: "warning",
  },
  {
    id: "se4",
    type: "LoginFailed",
    timestamp: "2026-03-26T08:20:00Z",
    userId: null,
    userName: "unknown",
    ipAddress: "203.0.113.42",
    userAgent: "Python-requests/2.28.0",
    details: "Unknown user email: hacker@test.com",
    severity: "warning",
  },
  {
    id: "se5",
    type: "LoginSuccess",
    timestamp: "2026-03-26T09:01:20Z",
    userId: "u1",
    userName: "Alisher Karimov",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    details: "Admin login from Tashkent, Uzbekistan",
    severity: "info",
  },
  {
    id: "se6",
    type: "PasswordChanged",
    timestamp: "2026-03-26T08:40:30Z",
    userId: "u3",
    userName: "Bobur Toshmatov",
    ipAddress: "192.168.1.45",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    details: "Password changed via email reset flow",
    severity: "info",
  },
  {
    id: "se7",
    type: "2FAEnabled",
    timestamp: "2026-03-26T08:14:00Z",
    userId: "u6",
    userName: "Nargiza Holmatova",
    ipAddress: "192.168.1.55",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0)",
    details: "TOTP 2FA configured for account",
    severity: "success",
  },
  {
    id: "se8",
    type: "RoleChanged",
    timestamp: "2026-03-25T15:30:00Z",
    userId: "u9",
    userName: "Sardor Yuldashev",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    details: "Role changed from 'teacher' to 'resource' by admin",
    severity: "warning",
  },
  {
    id: "se9",
    type: "SessionRevoked",
    timestamp: "2026-03-25T11:00:00Z",
    userId: "u7",
    userName: "Otabek Sobirov",
    ipAddress: "10.0.0.1",
    userAgent: "System",
    details: "Session forcibly revoked — account suspended",
    severity: "warning",
  },
  {
    id: "se10",
    type: "LoginFailed",
    timestamp: "2026-03-25T10:45:00Z",
    userId: null,
    userName: "o.sobirov@uni.edu",
    ipAddress: "192.168.3.22",
    userAgent: "Mozilla/5.0 (Android 12; Mobile)",
    details: "Account suspended — login blocked",
    severity: "warning",
  },
];

export const mockBlockedIPs: BlockedIP[] = [
  {
    id: "ip1",
    ipAddress: "185.220.101.45",
    reason: "Brute force attack — 25 login attempts in 5 minutes",
    blockedAt: "2026-03-26T09:13:00Z",
    blockedBy: "Auto-block System",
    expiresAt: "2026-03-27T09:13:00Z",
    attempts: 25,
  },
  {
    id: "ip2",
    ipAddress: "203.0.113.42",
    reason: "Credential stuffing — multiple unknown accounts",
    blockedAt: "2026-03-25T14:00:00Z",
    blockedBy: "Alisher Karimov",
    expiresAt: null,
    attempts: 12,
  },
  {
    id: "ip3",
    ipAddress: "198.51.100.88",
    reason: "Vulnerability scanning detected",
    blockedAt: "2026-03-24T08:30:00Z",
    blockedBy: "Auto-block System",
    expiresAt: "2026-03-31T08:30:00Z",
    attempts: 340,
  },
  {
    id: "ip4",
    ipAddress: "192.0.2.17",
    reason: "DDoS traffic source",
    blockedAt: "2026-03-20T12:00:00Z",
    blockedBy: "Umida Xasanova",
    expiresAt: null,
    attempts: 5820,
  },
  {
    id: "ip5",
    ipAddress: "172.16.0.99",
    reason: "SQL injection attempt on /api/reports",
    blockedAt: "2026-03-18T09:45:00Z",
    blockedBy: "Auto-block System",
    expiresAt: null,
    attempts: 4,
  },
];

export const mockActiveSessions: ActiveSession[] = [
  {
    id: "as1",
    userId: "u1",
    userName: "Alisher Karimov",
    role: "admin",
    ipAddress: "192.168.1.100",
    userAgent: "Chrome 123 / macOS",
    startedAt: "2026-03-26T09:01:20Z",
    lastActivity: "2026-03-26T09:12:00Z",
    location: "Tashkent, UZ",
  },
  {
    id: "as2",
    userId: "u2",
    userName: "Malika Yusupova",
    role: "deputy",
    ipAddress: "192.168.1.102",
    userAgent: "Chrome 123 / Windows",
    startedAt: "2026-03-26T07:55:00Z",
    lastActivity: "2026-03-26T09:10:00Z",
    location: "Tashkent, UZ",
  },
  {
    id: "as3",
    userId: "u5",
    userName: "Jasur Mirzayev",
    role: "accountant",
    ipAddress: "192.168.1.105",
    userAgent: "Firefox 124 / Windows",
    startedAt: "2026-03-26T09:00:00Z",
    lastActivity: "2026-03-26T09:08:00Z",
    location: "Tashkent, UZ",
  },
  {
    id: "as4",
    userId: "u6",
    userName: "Nargiza Holmatova",
    role: "academic",
    ipAddress: "192.168.1.55",
    userAgent: "Safari 17 / macOS",
    startedAt: "2026-03-26T08:30:00Z",
    lastActivity: "2026-03-26T09:05:00Z",
    location: "Tashkent, UZ",
  },
  {
    id: "as5",
    userId: "u12",
    userName: "Umida Xasanova",
    role: "it-ops",
    ipAddress: "10.0.1.12",
    userAgent: "Chrome 123 / Linux",
    startedAt: "2026-03-26T07:00:00Z",
    lastActivity: "2026-03-26T09:12:00Z",
    location: "Tashkent, UZ",
  },
  {
    id: "as6",
    userId: "u3",
    userName: "Bobur Toshmatov",
    role: "teacher",
    ipAddress: "192.168.2.30",
    userAgent: "Chrome 123 / Windows",
    startedAt: "2026-03-26T08:00:00Z",
    lastActivity: "2026-03-26T08:55:00Z",
    location: "Samarkand, UZ",
  },
];

// ─── Support ──────────────────────────────────────────────────────────────────

export const mockSupportStats: SupportStats = {
  openTickets: 7,
  inProgressTickets: 4,
  avgResponseTime: "2h 14m",
  avgResolutionTime: "18h 30m",
  satisfactionRate: 91,
  resolvedThisWeek: 23,
};

export const mockSupportTickets: SupportTicket[] = [
  {
    id: "t1",
    ticketNumber: "TKT-0241",
    subject: "Cannot log in — password reset not working",
    description: "I requested a password reset but never received the email.",
    category: "Account",
    priority: "Critical",
    status: "InProgress",
    createdAt: "2026-03-26T08:00:00Z",
    updatedAt: "2026-03-26T09:00:00Z",
    submittedBy: "Ravshan Qodirov",
    submittedByRole: "student",
    assignedTo: "Alisher Karimov",
    responseCount: 2,
  },
  {
    id: "t2",
    ticketNumber: "TKT-0240",
    subject: "1C integration not syncing payment data",
    description: "Finance data has not synced since March 24th.",
    category: "Technical",
    priority: "High",
    status: "Open",
    createdAt: "2026-03-25T14:30:00Z",
    updatedAt: "2026-03-25T14:30:00Z",
    submittedBy: "Jasur Mirzayev",
    submittedByRole: "accountant",
    assignedTo: null,
    responseCount: 0,
  },
  {
    id: "t3",
    ticketNumber: "TKT-0239",
    subject: "Gradebook showing incorrect GPA calculation",
    description: "One student's GPA appears wrong — missing one exam grade.",
    category: "Bug",
    priority: "High",
    status: "Open",
    createdAt: "2026-03-25T10:00:00Z",
    updatedAt: "2026-03-25T10:00:00Z",
    submittedBy: "Bobur Toshmatov",
    submittedByRole: "teacher",
    assignedTo: null,
    responseCount: 0,
  },
  {
    id: "t4",
    ticketNumber: "TKT-0238",
    subject: "Request to change account email address",
    description: "Need to update primary email to new faculty email.",
    category: "Account",
    priority: "Medium",
    status: "WaitingOnUser",
    createdAt: "2026-03-24T16:00:00Z",
    updatedAt: "2026-03-26T07:00:00Z",
    submittedBy: "Feruza Nazarova",
    submittedByRole: "aqad",
    assignedTo: "Umida Xasanova",
    responseCount: 3,
  },
  {
    id: "t5",
    ticketNumber: "TKT-0237",
    subject: "Cannot access Classmate platform",
    description: "Getting 403 Forbidden error when trying to open Classmate.",
    category: "Access",
    priority: "Medium",
    status: "InProgress",
    createdAt: "2026-03-24T11:00:00Z",
    updatedAt: "2026-03-25T09:00:00Z",
    submittedBy: "Dilnoza Ergasheva",
    submittedByRole: "student",
    assignedTo: "Umida Xasanova",
    responseCount: 1,
  },
  {
    id: "t6",
    ticketNumber: "TKT-0236",
    subject: "Teams meeting link expired before session",
    description: "The Teams link for today's lecture was already expired.",
    category: "Technical",
    priority: "Medium",
    status: "Resolved",
    createdAt: "2026-03-24T08:00:00Z",
    updatedAt: "2026-03-24T10:30:00Z",
    submittedBy: "Barno Tursunova",
    submittedByRole: "applicant",
    assignedTo: "Alisher Karimov",
    responseCount: 4,
  },
  {
    id: "t7",
    ticketNumber: "TKT-0235",
    subject: "Payment receipt not generated after transaction",
    description: "Student paid tuition but no receipt was issued.",
    category: "Billing",
    priority: "High",
    status: "Open",
    createdAt: "2026-03-23T15:00:00Z",
    updatedAt: "2026-03-23T15:00:00Z",
    submittedBy: "Mansur Abdullayev",
    submittedByRole: "student",
    assignedTo: null,
    responseCount: 0,
  },
  {
    id: "t8",
    ticketNumber: "TKT-0234",
    subject: "Schedule conflict — two exams on same day",
    description: "Two exams scheduled at the same time slot for group B-204.",
    category: "Other",
    priority: "High",
    status: "InProgress",
    createdAt: "2026-03-23T09:00:00Z",
    updatedAt: "2026-03-24T08:00:00Z",
    submittedBy: "Nargiza Holmatova",
    submittedByRole: "academic",
    assignedTo: "Alisher Karimov",
    responseCount: 2,
  },
  {
    id: "t9",
    ticketNumber: "TKT-0233",
    subject: "Role permissions not updating after change",
    description: "Changed user role but they still see old menu items.",
    category: "Access",
    priority: "Low",
    status: "Resolved",
    createdAt: "2026-03-22T14:00:00Z",
    updatedAt: "2026-03-22T17:00:00Z",
    submittedBy: "Sardor Yuldashev",
    submittedByRole: "resource",
    assignedTo: "Alisher Karimov",
    responseCount: 5,
  },
  {
    id: "t10",
    ticketNumber: "TKT-0232",
    subject: "Export to Excel not working on reports page",
    description: "Clicking Export button does nothing — no download starts.",
    category: "Bug",
    priority: "Medium",
    status: "Open",
    createdAt: "2026-03-22T11:00:00Z",
    updatedAt: "2026-03-22T11:00:00Z",
    submittedBy: "Malika Yusupova",
    submittedByRole: "deputy",
    assignedTo: null,
    responseCount: 0,
  },
  {
    id: "t11",
    ticketNumber: "TKT-0231",
    subject: "Duplicate student ID in system",
    description: "Two students share the same student ID number.",
    category: "Technical",
    priority: "Critical",
    status: "Closed",
    createdAt: "2026-03-21T09:00:00Z",
    updatedAt: "2026-03-21T15:30:00Z",
    submittedBy: "Nargiza Holmatova",
    submittedByRole: "academic",
    assignedTo: "Alisher Karimov",
    responseCount: 6,
  },
];

// ─── Reports ──────────────────────────────────────────────────────────────────

export const mockReportsStats: ReportsStats = {
  totalReports: 48,
  generatedThisMonth: 12,
  scheduledReports: 5,
  failedReports: 1,
};

export const mockSystemReports: SystemReport[] = [
  {
    id: "rep1",
    type: "UserActivity",
    title: "Monthly User Activity — March 2026",
    period: "March 2026",
    format: "PDF",
    generatedAt: "2026-03-25T08:00:00Z",
    generatedBy: "Alisher Karimov",
    fileSize: "2.4 MB",
    status: "Ready",
  },
  {
    id: "rep2",
    type: "SecurityAudit",
    title: "Security Audit Report — Q1 2026",
    period: "Q1 2026",
    format: "PDF",
    generatedAt: "2026-03-24T10:00:00Z",
    generatedBy: "Alisher Karimov",
    fileSize: "4.1 MB",
    status: "Ready",
  },
  {
    id: "rep3",
    type: "SystemPerformance",
    title: "System Performance Report — March 2026",
    period: "March 2026",
    format: "Excel",
    generatedAt: "2026-03-23T09:00:00Z",
    generatedBy: "Umida Xasanova",
    fileSize: "1.8 MB",
    status: "Ready",
  },
  {
    id: "rep4",
    type: "UsageStatistics",
    title: "Platform Usage Statistics — March 2026",
    period: "March 2026",
    format: "CSV",
    generatedAt: "2026-03-22T08:00:00Z",
    generatedBy: "Alisher Karimov",
    fileSize: "0.6 MB",
    status: "Ready",
  },
  {
    id: "rep5",
    type: "ComplianceReport",
    title: "Data Compliance Report — Q1 2026",
    period: "Q1 2026",
    format: "PDF",
    generatedAt: "2026-03-21T14:00:00Z",
    generatedBy: "Alisher Karimov",
    fileSize: "3.2 MB",
    status: "Ready",
  },
  {
    id: "rep6",
    type: "ErrorAnalysis",
    title: "Error Analysis — Week 12, 2026",
    period: "Week 12 2026",
    format: "Excel",
    generatedAt: "2026-03-21T08:00:00Z",
    generatedBy: "Umida Xasanova",
    fileSize: "1.1 MB",
    status: "Ready",
  },
  {
    id: "rep7",
    type: "UserActivity",
    title: "Monthly User Activity — February 2026",
    period: "February 2026",
    format: "PDF",
    generatedAt: "2026-02-25T08:00:00Z",
    generatedBy: "Alisher Karimov",
    fileSize: "2.2 MB",
    status: "Ready",
  },
  {
    id: "rep8",
    type: "SystemPerformance",
    title: "System Performance Report — February 2026",
    period: "February 2026",
    format: "Excel",
    generatedAt: "2026-02-23T09:00:00Z",
    generatedBy: "Umida Xasanova",
    fileSize: "1.7 MB",
    status: "Ready",
  },
  {
    id: "rep9",
    type: "SecurityAudit",
    title: "Security Audit — February 2026",
    period: "February 2026",
    format: "PDF",
    generatedAt: "2026-02-20T10:00:00Z",
    generatedBy: "Alisher Karimov",
    fileSize: "3.6 MB",
    status: "Ready",
  },
  {
    id: "rep10",
    type: "ErrorAnalysis",
    title: "Error Analysis — January 2026",
    period: "January 2026",
    format: "CSV",
    generatedAt: "2026-02-01T08:00:00Z",
    generatedBy: "Umida Xasanova",
    fileSize: "0.4 MB",
    status: "Ready",
  },
  {
    id: "rep11",
    type: "ComplianceReport",
    title: "Annual Compliance Report — 2025",
    period: "Year 2025",
    format: "PDF",
    generatedAt: "2026-01-10T14:00:00Z",
    generatedBy: "Alisher Karimov",
    fileSize: "8.4 MB",
    status: "Ready",
  },
  {
    id: "rep12",
    type: "UsageStatistics",
    title: "Platform Usage Statistics — Q4 2025",
    period: "Q4 2025",
    format: "Excel",
    generatedAt: "2025-12-30T09:00:00Z",
    generatedBy: "Alisher Karimov",
    fileSize: "2.0 MB",
    status: "Failed",
  },
];
