import type {
  AttendanceSummary,
  ComparativeEntry,
  DeputyDashboardStats,
  DeputySettings,
  DepartmentPerformance,
  ExecutiveReport,
  ForecastScenario,
  Incident,
  KPIMetric,
  QualityMetric,
  StudentProgression,
  AcademicProgram,
  FinancialSummary,
} from "@/types/deputy";

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const mockDeputyStats: DeputyDashboardStats = {
  totalStudents: 4820,
  totalTeachers: 186,
  overallGPA: 3.42,
  retentionRate: 87.3,
  satisfactionScore: 4.1,
  revenueYTD: 12_450_000,
  kpisOnTrack: 18,
  kpisAtRisk: 5,
  openIncidents: 3,
  qualityScore: 88.5,
};

// ─── KPI Metrics ──────────────────────────────────────────────────────────────

export const mockKPIs: KPIMetric[] = [
  {
    id: "kpi-1",
    name: "Student Satisfaction",
    category: "Student",
    currentValue: 4.1,
    targetValue: 4.5,
    unit: "score",
    status: "AtRisk",
    trend: "up",
    changePercent: 2.5,
    period: "Spring 2026",
  },
  {
    id: "kpi-2",
    name: "Graduation Rate",
    category: "Academic",
    currentValue: 84.2,
    targetValue: 90,
    unit: "%",
    status: "AtRisk",
    trend: "up",
    changePercent: 1.8,
    period: "Spring 2026",
  },
  {
    id: "kpi-3",
    name: "Revenue Collection Rate",
    category: "Financial",
    currentValue: 91.3,
    targetValue: 95,
    unit: "%",
    status: "OnTrack",
    trend: "up",
    changePercent: 3.2,
    period: "Spring 2026",
  },
  {
    id: "kpi-4",
    name: "Teacher Retention",
    category: "Operational",
    currentValue: 93.5,
    targetValue: 95,
    unit: "%",
    status: "OnTrack",
    trend: "stable",
    changePercent: 0.5,
    period: "Spring 2026",
  },
  {
    id: "kpi-5",
    name: "Quality Audit Pass Rate",
    category: "Quality",
    currentValue: 88.5,
    targetValue: 90,
    unit: "%",
    status: "OnTrack",
    trend: "up",
    changePercent: 2.1,
    period: "Spring 2026",
  },
  {
    id: "kpi-6",
    name: "Student Retention Rate",
    category: "Student",
    currentValue: 87.3,
    targetValue: 92,
    unit: "%",
    status: "AtRisk",
    trend: "stable",
    changePercent: -0.3,
    period: "Spring 2026",
  },
  {
    id: "kpi-7",
    name: "Overall GPA",
    category: "Academic",
    currentValue: 3.42,
    targetValue: 3.6,
    unit: "GPA",
    status: "OnTrack",
    trend: "up",
    changePercent: 1.2,
    period: "Spring 2026",
  },
  {
    id: "kpi-8",
    name: "Budget Utilization",
    category: "Financial",
    currentValue: 78.4,
    targetValue: 85,
    unit: "%",
    status: "OnTrack",
    trend: "up",
    changePercent: 4.3,
    period: "Spring 2026",
  },
  {
    id: "kpi-9",
    name: "Engineering Dept GPA",
    category: "Academic",
    currentValue: 3.55,
    targetValue: 3.5,
    unit: "GPA",
    status: "Exceeded",
    trend: "up",
    changePercent: 3.1,
    department: "Engineering",
    period: "Spring 2026",
  },
  {
    id: "kpi-10",
    name: "Economics Dept GPA",
    category: "Academic",
    currentValue: 3.38,
    targetValue: 3.5,
    unit: "GPA",
    status: "AtRisk",
    trend: "down",
    changePercent: -1.4,
    department: "Economics",
    period: "Spring 2026",
  },
  {
    id: "kpi-11",
    name: "Avg Attendance Rate",
    category: "Student",
    currentValue: 82.7,
    targetValue: 85,
    unit: "%",
    status: "AtRisk",
    trend: "down",
    changePercent: -2.1,
    period: "Spring 2026",
  },
  {
    id: "kpi-12",
    name: "Course Completion Rate",
    category: "Academic",
    currentValue: 91.2,
    targetValue: 92,
    unit: "%",
    status: "OnTrack",
    trend: "up",
    changePercent: 0.8,
    period: "Spring 2026",
  },
  {
    id: "kpi-13",
    name: "Incident Resolution Time",
    category: "Operational",
    currentValue: 3.2,
    targetValue: 2,
    unit: "days",
    status: "Critical",
    trend: "down",
    changePercent: -15,
    period: "Spring 2026",
  },
  {
    id: "kpi-14",
    name: "Health Sciences GPA",
    category: "Academic",
    currentValue: 3.61,
    targetValue: 3.5,
    unit: "GPA",
    status: "Exceeded",
    trend: "up",
    changePercent: 2.8,
    department: "Health Sciences",
    period: "Spring 2026",
  },
  {
    id: "kpi-15",
    name: "Outstanding Debt Ratio",
    category: "Financial",
    currentValue: 8.7,
    targetValue: 5,
    unit: "%",
    status: "Critical",
    trend: "up",
    changePercent: 12,
    period: "Spring 2026",
  },
  {
    id: "kpi-16",
    name: "New Student Enrollment",
    category: "Student",
    currentValue: 1240,
    targetValue: 1300,
    unit: "students",
    status: "AtRisk",
    trend: "stable",
    changePercent: -1.2,
    period: "Spring 2026",
  },
  {
    id: "kpi-17",
    name: "Faculty Satisfaction",
    category: "Operational",
    currentValue: 3.9,
    targetValue: 4.2,
    unit: "score",
    status: "OnTrack",
    trend: "up",
    changePercent: 2.6,
    period: "Spring 2026",
  },
  {
    id: "kpi-18",
    name: "Research Publications",
    category: "Quality",
    currentValue: 47,
    targetValue: 60,
    unit: "count",
    status: "AtRisk",
    trend: "up",
    changePercent: 8.4,
    period: "Spring 2026",
  },
  {
    id: "kpi-19",
    name: "Library Usage Rate",
    category: "Operational",
    currentValue: 72.1,
    targetValue: 70,
    unit: "%",
    status: "Exceeded",
    trend: "up",
    changePercent: 5.2,
    period: "Spring 2026",
  },
  {
    id: "kpi-20",
    name: "Design Dept Retention",
    category: "Student",
    currentValue: 90.2,
    targetValue: 90,
    unit: "%",
    status: "Exceeded",
    trend: "up",
    changePercent: 3.1,
    department: "Design",
    period: "Spring 2026",
  },
  {
    id: "kpi-21",
    name: "IT Infrastructure Uptime",
    category: "Operational",
    currentValue: 99.1,
    targetValue: 99.5,
    unit: "%",
    status: "OnTrack",
    trend: "stable",
    changePercent: 0.1,
    period: "Spring 2026",
  },
  {
    id: "kpi-22",
    name: "Student-Teacher Ratio",
    category: "Operational",
    currentValue: 25.9,
    targetValue: 22,
    unit: "ratio",
    status: "AtRisk",
    trend: "stable",
    changePercent: 1.2,
    period: "Spring 2026",
  },
  {
    id: "kpi-23",
    name: "Humanities Dept Revenue",
    category: "Financial",
    currentValue: 1_820_000,
    targetValue: 2_000_000,
    unit: "$",
    status: "AtRisk",
    trend: "up",
    changePercent: 6.4,
    department: "Humanities",
    period: "Spring 2026",
  },
];

// ─── Department Performance ───────────────────────────────────────────────────

export const mockDepartmentPerformance: DepartmentPerformance[] = [
  {
    department: "Engineering",
    gpa: 3.55,
    enrollmentCount: 1140,
    retentionRate: 91.2,
    satisfactionScore: 4.3,
    completionRate: 93.1,
    revenueCollected: 3_420_000,
    outstandingDebt: 245_000,
    qualityScore: 91.4,
    teacherCount: 48,
    studentTeacherRatio: 23.75,
  },
  {
    department: "Economics",
    gpa: 3.38,
    enrollmentCount: 980,
    retentionRate: 85.7,
    satisfactionScore: 3.9,
    completionRate: 89.4,
    revenueCollected: 2_860_000,
    outstandingDebt: 318_000,
    qualityScore: 85.2,
    teacherCount: 38,
    studentTeacherRatio: 25.79,
  },
  {
    department: "Health Sciences",
    gpa: 3.61,
    enrollmentCount: 820,
    retentionRate: 92.4,
    satisfactionScore: 4.4,
    completionRate: 94.8,
    revenueCollected: 2_510_000,
    outstandingDebt: 178_000,
    qualityScore: 93.7,
    teacherCount: 34,
    studentTeacherRatio: 24.12,
  },
  {
    department: "Humanities",
    gpa: 3.44,
    enrollmentCount: 760,
    retentionRate: 83.1,
    satisfactionScore: 4.0,
    completionRate: 87.6,
    revenueCollected: 1_820_000,
    outstandingDebt: 290_000,
    qualityScore: 84.8,
    teacherCount: 31,
    studentTeacherRatio: 24.52,
  },
  {
    department: "Design",
    gpa: 3.48,
    enrollmentCount: 640,
    retentionRate: 90.2,
    satisfactionScore: 4.5,
    completionRate: 92.3,
    revenueCollected: 1_640_000,
    outstandingDebt: 112_000,
    qualityScore: 90.1,
    teacherCount: 22,
    studentTeacherRatio: 29.09,
  },
  {
    department: "Natural Sciences",
    gpa: 3.51,
    enrollmentCount: 480,
    retentionRate: 88.6,
    satisfactionScore: 4.2,
    completionRate: 91.7,
    revenueCollected: 1_200_000,
    outstandingDebt: 98_000,
    qualityScore: 89.3,
    teacherCount: 13,
    studentTeacherRatio: 36.92,
  },
];

// ─── Academic Programs ────────────────────────────────────────────────────────

export const mockAcademicPrograms: AcademicProgram[] = [
  {
    id: "prog-1",
    name: "Computer Science",
    department: "Engineering",
    enrolledStudents: 420,
    avgGPA: 3.62,
    completionRate: 94.2,
    satisfactionScore: 4.4,
    coursesCount: 48,
  },
  {
    id: "prog-2",
    name: "Software Engineering",
    department: "Engineering",
    enrolledStudents: 380,
    avgGPA: 3.49,
    completionRate: 92.1,
    satisfactionScore: 4.2,
    coursesCount: 44,
  },
  {
    id: "prog-3",
    name: "Business Administration",
    department: "Economics",
    enrolledStudents: 520,
    avgGPA: 3.31,
    completionRate: 88.3,
    satisfactionScore: 3.8,
    coursesCount: 36,
  },
  {
    id: "prog-4",
    name: "Finance & Banking",
    department: "Economics",
    enrolledStudents: 290,
    avgGPA: 3.44,
    completionRate: 90.6,
    satisfactionScore: 4.0,
    coursesCount: 32,
  },
  {
    id: "prog-5",
    name: "Medicine",
    department: "Health Sciences",
    enrolledStudents: 340,
    avgGPA: 3.71,
    completionRate: 96.4,
    satisfactionScore: 4.6,
    coursesCount: 62,
  },
  {
    id: "prog-6",
    name: "Nursing",
    department: "Health Sciences",
    enrolledStudents: 280,
    avgGPA: 3.52,
    completionRate: 93.1,
    satisfactionScore: 4.3,
    coursesCount: 40,
  },
  {
    id: "prog-7",
    name: "Psychology",
    department: "Humanities",
    enrolledStudents: 310,
    avgGPA: 3.47,
    completionRate: 88.9,
    satisfactionScore: 4.1,
    coursesCount: 34,
  },
  {
    id: "prog-8",
    name: "Graphic Design",
    department: "Design",
    enrolledStudents: 360,
    avgGPA: 3.53,
    completionRate: 93.4,
    satisfactionScore: 4.6,
    coursesCount: 38,
  },
  {
    id: "prog-9",
    name: "UX/UI Design",
    department: "Design",
    enrolledStudents: 280,
    avgGPA: 3.44,
    completionRate: 91.2,
    satisfactionScore: 4.4,
    coursesCount: 30,
  },
  {
    id: "prog-10",
    name: "Biology",
    department: "Natural Sciences",
    enrolledStudents: 480,
    avgGPA: 3.51,
    completionRate: 91.7,
    satisfactionScore: 4.2,
    coursesCount: 42,
  },
];

// ─── Attendance Summary ───────────────────────────────────────────────────────

export const mockAttendanceSummary: AttendanceSummary[] = [
  {
    department: "Engineering",
    totalStudents: 1140,
    avgAttendanceRate: 86.4,
    belowThresholdCount: 78,
    trend: "up",
    byMonth: [
      { month: "Oct", rate: 84.1 },
      { month: "Nov", rate: 83.7 },
      { month: "Dec", rate: 82.9 },
      { month: "Jan", rate: 85.2 },
      { month: "Feb", rate: 86.1 },
      { month: "Mar", rate: 86.4 },
    ],
  },
  {
    department: "Economics",
    totalStudents: 980,
    avgAttendanceRate: 79.8,
    belowThresholdCount: 142,
    trend: "down",
    byMonth: [
      { month: "Oct", rate: 82.3 },
      { month: "Nov", rate: 81.1 },
      { month: "Dec", rate: 80.4 },
      { month: "Jan", rate: 79.9 },
      { month: "Feb", rate: 80.1 },
      { month: "Mar", rate: 79.8 },
    ],
  },
  {
    department: "Health Sciences",
    totalStudents: 820,
    avgAttendanceRate: 91.2,
    belowThresholdCount: 34,
    trend: "stable",
    byMonth: [
      { month: "Oct", rate: 90.8 },
      { month: "Nov", rate: 91.4 },
      { month: "Dec", rate: 90.9 },
      { month: "Jan", rate: 91.1 },
      { month: "Feb", rate: 91.5 },
      { month: "Mar", rate: 91.2 },
    ],
  },
  {
    department: "Humanities",
    totalStudents: 760,
    avgAttendanceRate: 76.3,
    belowThresholdCount: 168,
    trend: "down",
    byMonth: [
      { month: "Oct", rate: 79.1 },
      { month: "Nov", rate: 78.4 },
      { month: "Dec", rate: 77.8 },
      { month: "Jan", rate: 76.9 },
      { month: "Feb", rate: 76.5 },
      { month: "Mar", rate: 76.3 },
    ],
  },
  {
    department: "Design",
    totalStudents: 640,
    avgAttendanceRate: 88.7,
    belowThresholdCount: 42,
    trend: "up",
    byMonth: [
      { month: "Oct", rate: 87.2 },
      { month: "Nov", rate: 87.8 },
      { month: "Dec", rate: 88.1 },
      { month: "Jan", rate: 88.3 },
      { month: "Feb", rate: 88.5 },
      { month: "Mar", rate: 88.7 },
    ],
  },
  {
    department: "Natural Sciences",
    totalStudents: 480,
    avgAttendanceRate: 84.1,
    belowThresholdCount: 56,
    trend: "stable",
    byMonth: [
      { month: "Oct", rate: 83.8 },
      { month: "Nov", rate: 84.2 },
      { month: "Dec", rate: 83.6 },
      { month: "Jan", rate: 84.0 },
      { month: "Feb", rate: 84.3 },
      { month: "Mar", rate: 84.1 },
    ],
  },
];

// ─── Financial Summary ────────────────────────────────────────────────────────

export const mockFinancialSummary: FinancialSummary[] = [
  {
    department: "Engineering",
    budgetAllocated: 4_200_000,
    budgetSpent: 3_180_000,
    revenueCollected: 3_420_000,
    outstandingDebt: 245_000,
    collectionRate: 93.3,
    forecastedRevenue: 4_100_000,
  },
  {
    department: "Economics",
    budgetAllocated: 3_500_000,
    budgetSpent: 2_940_000,
    revenueCollected: 2_860_000,
    outstandingDebt: 318_000,
    collectionRate: 90.0,
    forecastedRevenue: 3_200_000,
  },
  {
    department: "Health Sciences",
    budgetAllocated: 3_000_000,
    budgetSpent: 2_410_000,
    revenueCollected: 2_510_000,
    outstandingDebt: 178_000,
    collectionRate: 93.4,
    forecastedRevenue: 2_800_000,
  },
  {
    department: "Humanities",
    budgetAllocated: 2_400_000,
    budgetSpent: 1_920_000,
    revenueCollected: 1_820_000,
    outstandingDebt: 290_000,
    collectionRate: 86.3,
    forecastedRevenue: 2_100_000,
  },
  {
    department: "Design",
    budgetAllocated: 2_000_000,
    budgetSpent: 1_580_000,
    revenueCollected: 1_640_000,
    outstandingDebt: 112_000,
    collectionRate: 93.6,
    forecastedRevenue: 1_900_000,
  },
  {
    department: "Natural Sciences",
    budgetAllocated: 1_600_000,
    budgetSpent: 1_180_000,
    revenueCollected: 1_200_000,
    outstandingDebt: 98_000,
    collectionRate: 92.4,
    forecastedRevenue: 1_400_000,
  },
];

// ─── Quality Metrics ──────────────────────────────────────────────────────────

export const mockQualityMetrics: QualityMetric[] = [
  {
    id: "qm-1",
    name: "Curriculum Compliance",
    department: "Engineering",
    score: 92,
    maxScore: 100,
    status: "Exceeded",
    auditsCompleted: 8,
    issuesOpen: 1,
    lastAuditDate: "2026-03-10",
  },
  {
    id: "qm-2",
    name: "Teaching Quality",
    department: "Engineering",
    score: 88,
    maxScore: 100,
    status: "OnTrack",
    auditsCompleted: 12,
    issuesOpen: 2,
    lastAuditDate: "2026-03-18",
  },
  {
    id: "qm-3",
    name: "Curriculum Compliance",
    department: "Economics",
    score: 81,
    maxScore: 100,
    status: "OnTrack",
    auditsCompleted: 6,
    issuesOpen: 4,
    lastAuditDate: "2026-03-05",
  },
  {
    id: "qm-4",
    name: "Assessment Standards",
    department: "Economics",
    score: 76,
    maxScore: 100,
    status: "AtRisk",
    auditsCompleted: 5,
    issuesOpen: 7,
    lastAuditDate: "2026-02-28",
  },
  {
    id: "qm-5",
    name: "Clinical Practice Standards",
    department: "Health Sciences",
    score: 95,
    maxScore: 100,
    status: "Exceeded",
    auditsCompleted: 14,
    issuesOpen: 0,
    lastAuditDate: "2026-03-20",
  },
  {
    id: "qm-6",
    name: "Teaching Quality",
    department: "Health Sciences",
    score: 91,
    maxScore: 100,
    status: "Exceeded",
    auditsCompleted: 10,
    issuesOpen: 1,
    lastAuditDate: "2026-03-15",
  },
  {
    id: "qm-7",
    name: "Research Ethics Compliance",
    department: "Humanities",
    score: 83,
    maxScore: 100,
    status: "OnTrack",
    auditsCompleted: 4,
    issuesOpen: 3,
    lastAuditDate: "2026-03-01",
  },
  {
    id: "qm-8",
    name: "Studio Safety Standards",
    department: "Design",
    score: 90,
    maxScore: 100,
    status: "OnTrack",
    auditsCompleted: 7,
    issuesOpen: 2,
    lastAuditDate: "2026-03-12",
  },
  {
    id: "qm-9",
    name: "Lab Safety Compliance",
    department: "Natural Sciences",
    score: 68,
    maxScore: 100,
    status: "Critical",
    auditsCompleted: 9,
    issuesOpen: 11,
    lastAuditDate: "2026-03-08",
  },
];

// ─── Student Progression ──────────────────────────────────────────────────────

export const mockStudentProgression: StudentProgression[] = [
  {
    cohort: "2022",
    initialEnrollment: 1380,
    currentEnrollment: 1180,
    retentionRate: 85.5,
    graduationRate: 78.2,
    avgTimeToGraduation: 4.1,
    atRiskCount: 68,
    droppedCount: 200,
  },
  {
    cohort: "2023",
    initialEnrollment: 1460,
    currentEnrollment: 1290,
    retentionRate: 88.4,
    graduationRate: 0,
    avgTimeToGraduation: 0,
    atRiskCount: 82,
    droppedCount: 170,
  },
  {
    cohort: "2024",
    initialEnrollment: 1520,
    currentEnrollment: 1410,
    retentionRate: 92.8,
    graduationRate: 0,
    avgTimeToGraduation: 0,
    atRiskCount: 94,
    droppedCount: 110,
  },
  {
    cohort: "2025",
    initialEnrollment: 1240,
    currentEnrollment: 1210,
    retentionRate: 97.6,
    graduationRate: 0,
    avgTimeToGraduation: 0,
    atRiskCount: 41,
    droppedCount: 30,
  },
];

// ─── Comparative Data ─────────────────────────────────────────────────────────

export const mockComparativeData: ComparativeEntry[] = [
  {
    department: "Engineering",
    metric: "GPA",
    currentPeriodValue: 3.55,
    previousPeriodValue: 3.44,
    changePercent: 3.2,
    trend: "up",
  },
  {
    department: "Economics",
    metric: "GPA",
    currentPeriodValue: 3.38,
    previousPeriodValue: 3.43,
    changePercent: -1.4,
    trend: "down",
  },
  {
    department: "Health Sciences",
    metric: "GPA",
    currentPeriodValue: 3.61,
    previousPeriodValue: 3.52,
    changePercent: 2.6,
    trend: "up",
  },
  {
    department: "Humanities",
    metric: "GPA",
    currentPeriodValue: 3.44,
    previousPeriodValue: 3.41,
    changePercent: 0.9,
    trend: "up",
  },
  {
    department: "Design",
    metric: "GPA",
    currentPeriodValue: 3.48,
    previousPeriodValue: 3.39,
    changePercent: 2.7,
    trend: "up",
  },
  {
    department: "Natural Sciences",
    metric: "GPA",
    currentPeriodValue: 3.51,
    previousPeriodValue: 3.48,
    changePercent: 0.9,
    trend: "stable",
  },
];

// ─── Forecasts ────────────────────────────────────────────────────────────────

export const mockForecasts: ForecastScenario[] = [
  {
    id: "scenario-optimistic",
    name: "Optimistic",
    description:
      "Best-case scenario assuming continued enrollment growth, improved retention, and favorable economic conditions.",
    assumptions: [
      "Enrollment grows 8% semester-over-semester",
      "Retention rate improves to 92% by end of year",
      "Revenue collection rate reaches 96%",
      "No major operational disruptions",
    ],
    projections: [
      {
        period: "Oct 2025",
        actual: 4640,
        forecast: 4640,
        confidence: "high",
        lower: 4600,
        upper: 4680,
      },
      {
        period: "Nov 2025",
        actual: 4690,
        forecast: 4690,
        confidence: "high",
        lower: 4650,
        upper: 4730,
      },
      {
        period: "Dec 2025",
        actual: 4720,
        forecast: 4720,
        confidence: "high",
        lower: 4680,
        upper: 4760,
      },
      {
        period: "Jan 2026",
        actual: 4790,
        forecast: 4790,
        confidence: "high",
        lower: 4750,
        upper: 4830,
      },
      {
        period: "Feb 2026",
        actual: 4810,
        forecast: 4810,
        confidence: "high",
        lower: 4770,
        upper: 4850,
      },
      {
        period: "Mar 2026",
        actual: 4820,
        forecast: 4820,
        confidence: "high",
        lower: 4780,
        upper: 4860,
      },
      {
        period: "Apr 2026",
        actual: null,
        forecast: 4900,
        confidence: "high",
        lower: 4840,
        upper: 4960,
      },
      {
        period: "May 2026",
        actual: null,
        forecast: 4980,
        confidence: "medium",
        lower: 4890,
        upper: 5070,
      },
      {
        period: "Jun 2026",
        actual: null,
        forecast: 5060,
        confidence: "medium",
        lower: 4940,
        upper: 5180,
      },
      {
        period: "Jul 2026",
        actual: null,
        forecast: 5080,
        confidence: "low",
        lower: 4920,
        upper: 5240,
      },
      {
        period: "Aug 2026",
        actual: null,
        forecast: 5120,
        confidence: "low",
        lower: 4940,
        upper: 5300,
      },
      {
        period: "Sep 2026",
        actual: null,
        forecast: 5200,
        confidence: "low",
        lower: 4990,
        upper: 5410,
      },
    ],
  },
  {
    id: "scenario-baseline",
    name: "Baseline",
    description:
      "Most likely scenario based on current trends and historical patterns.",
    assumptions: [
      "Enrollment grows 4-5% semester-over-semester",
      "Retention rate holds steady at ~87-89%",
      "Revenue collection rate stays at 91-93%",
      "Minor operational disruptions accounted for",
    ],
    projections: [
      {
        period: "Oct 2025",
        actual: 4640,
        forecast: 4640,
        confidence: "high",
        lower: 4600,
        upper: 4680,
      },
      {
        period: "Nov 2025",
        actual: 4690,
        forecast: 4690,
        confidence: "high",
        lower: 4640,
        upper: 4740,
      },
      {
        period: "Dec 2025",
        actual: 4720,
        forecast: 4720,
        confidence: "high",
        lower: 4660,
        upper: 4780,
      },
      {
        period: "Jan 2026",
        actual: 4790,
        forecast: 4790,
        confidence: "high",
        lower: 4720,
        upper: 4860,
      },
      {
        period: "Feb 2026",
        actual: 4810,
        forecast: 4810,
        confidence: "high",
        lower: 4740,
        upper: 4880,
      },
      {
        period: "Mar 2026",
        actual: 4820,
        forecast: 4820,
        confidence: "high",
        lower: 4750,
        upper: 4890,
      },
      {
        period: "Apr 2026",
        actual: null,
        forecast: 4860,
        confidence: "high",
        lower: 4780,
        upper: 4940,
      },
      {
        period: "May 2026",
        actual: null,
        forecast: 4900,
        confidence: "medium",
        lower: 4800,
        upper: 5000,
      },
      {
        period: "Jun 2026",
        actual: null,
        forecast: 4940,
        confidence: "medium",
        lower: 4820,
        upper: 5060,
      },
      {
        period: "Jul 2026",
        actual: null,
        forecast: 4920,
        confidence: "low",
        lower: 4780,
        upper: 5060,
      },
      {
        period: "Aug 2026",
        actual: null,
        forecast: 4960,
        confidence: "low",
        lower: 4800,
        upper: 5120,
      },
      {
        period: "Sep 2026",
        actual: null,
        forecast: 5020,
        confidence: "low",
        lower: 4840,
        upper: 5200,
      },
    ],
  },
  {
    id: "scenario-conservative",
    name: "Conservative",
    description:
      "Pessimistic scenario factoring in economic headwinds and competition from other institutions.",
    assumptions: [
      "Enrollment grows only 1-2% or stays flat",
      "Retention drops slightly to ~84-86%",
      "Revenue collection rate decreases to ~88-90%",
      "Increased operational costs",
    ],
    projections: [
      {
        period: "Oct 2025",
        actual: 4640,
        forecast: 4640,
        confidence: "high",
        lower: 4600,
        upper: 4680,
      },
      {
        period: "Nov 2025",
        actual: 4690,
        forecast: 4690,
        confidence: "high",
        lower: 4630,
        upper: 4750,
      },
      {
        period: "Dec 2025",
        actual: 4720,
        forecast: 4720,
        confidence: "high",
        lower: 4650,
        upper: 4790,
      },
      {
        period: "Jan 2026",
        actual: 4790,
        forecast: 4790,
        confidence: "high",
        lower: 4710,
        upper: 4870,
      },
      {
        period: "Feb 2026",
        actual: 4810,
        forecast: 4810,
        confidence: "high",
        lower: 4720,
        upper: 4900,
      },
      {
        period: "Mar 2026",
        actual: 4820,
        forecast: 4820,
        confidence: "high",
        lower: 4730,
        upper: 4910,
      },
      {
        period: "Apr 2026",
        actual: null,
        forecast: 4810,
        confidence: "high",
        lower: 4700,
        upper: 4920,
      },
      {
        period: "May 2026",
        actual: null,
        forecast: 4790,
        confidence: "medium",
        lower: 4660,
        upper: 4920,
      },
      {
        period: "Jun 2026",
        actual: null,
        forecast: 4770,
        confidence: "medium",
        lower: 4620,
        upper: 4920,
      },
      {
        period: "Jul 2026",
        actual: null,
        forecast: 4720,
        confidence: "low",
        lower: 4540,
        upper: 4900,
      },
      {
        period: "Aug 2026",
        actual: null,
        forecast: 4750,
        confidence: "low",
        lower: 4560,
        upper: 4940,
      },
      {
        period: "Sep 2026",
        actual: null,
        forecast: 4780,
        confidence: "low",
        lower: 4580,
        upper: 4980,
      },
    ],
  },
];

// ─── Incidents ────────────────────────────────────────────────────────────────

export const mockIncidents: Incident[] = [
  {
    id: "inc-1",
    title: "Lab Safety Violation — Natural Sciences",
    description:
      "Multiple safety protocol breaches found during unannounced lab inspection. Improper chemical storage and missing safety equipment.",
    severity: "critical",
    status: "investigating",
    department: "Natural Sciences",
    reportedAt: "2026-03-22T09:15:00Z",
    reportedBy: "AQAD Inspector",
    assignedTo: "Dr. Rashidov, M.",
    resolvedAt: null,
    impactDescription: "Potential health risk to 120 students in lab courses",
  },
  {
    id: "inc-2",
    title: "Grade Manipulation Allegation — Economics",
    description:
      "A faculty member is under investigation for allegedly altering student grades in the grading system without authorization.",
    severity: "critical",
    status: "escalated",
    department: "Economics",
    reportedAt: "2026-03-20T14:30:00Z",
    reportedBy: "Student Affairs",
    assignedTo: "HR Department",
    resolvedAt: null,
    impactDescription: "Affects 3 courses, 87 students potentially impacted",
  },
  {
    id: "inc-3",
    title: "Server Outage — LMS Platform",
    description:
      "Primary LMS server experienced an 8-hour downtime affecting all student and teacher access during exam week.",
    severity: "high",
    status: "resolved",
    department: "Engineering",
    reportedAt: "2026-03-15T03:20:00Z",
    reportedBy: "IT Department",
    assignedTo: "IT-Ops Team",
    resolvedAt: "2026-03-15T11:45:00Z",
    impactDescription: "All 4,820 students and 186 teachers unable to access platform for 8 hours",
  },
  {
    id: "inc-4",
    title: "High Dropout Rate — Humanities Q1",
    description:
      "First-quarter dropout rate in Humanities exceeded threshold of 15%. 168 students below attendance threshold.",
    severity: "high",
    status: "open",
    department: "Humanities",
    reportedAt: "2026-03-18T10:00:00Z",
    reportedBy: "Academic Analytics",
    assignedTo: "Dean of Humanities",
    resolvedAt: null,
    impactDescription: "Potential revenue impact of $290,000 if dropouts continue",
  },
  {
    id: "inc-5",
    title: "Accreditation Concern — Assessment Standards",
    description:
      "AQAD found that Economics department assessment standards do not fully comply with national accreditation requirements.",
    severity: "high",
    status: "investigating",
    department: "Economics",
    reportedAt: "2026-03-10T11:00:00Z",
    reportedBy: "AQAD Department",
    assignedTo: "Dr. Karimova, S.",
    resolvedAt: null,
    impactDescription: "Risk to department accreditation renewal in June 2026",
  },
  {
    id: "inc-6",
    title: "Teacher Contract Non-Renewal Surge",
    description:
      "5 senior faculty members in Natural Sciences declined contract renewal, creating significant workload gaps.",
    severity: "medium",
    status: "open",
    department: "Natural Sciences",
    reportedAt: "2026-03-19T09:00:00Z",
    reportedBy: "HR Department",
    assignedTo: "Resource Manager",
    resolvedAt: null,
    impactDescription: "38% increase in student-teacher ratio in affected courses",
  },
  {
    id: "inc-7",
    title: "Payment System Integration Failure",
    description:
      "Third-party payment gateway experienced intermittent failures causing 47 payment transactions to fail.",
    severity: "medium",
    status: "resolved",
    department: "Economics",
    reportedAt: "2026-03-12T16:30:00Z",
    reportedBy: "Finance Department",
    assignedTo: "IT-Ops Team",
    resolvedAt: "2026-03-14T10:00:00Z",
    impactDescription: "$58,400 in failed transactions — all manually processed and recovered",
  },
  {
    id: "inc-8",
    title: "Plagiarism Software Licensing Expired",
    description:
      "Anti-plagiarism software license expired without renewal, leaving faculty without automated detection tools.",
    severity: "low",
    status: "resolved",
    department: "Humanities",
    reportedAt: "2026-03-08T08:00:00Z",
    reportedBy: "Faculty Services",
    assignedTo: "IT-Ops Team",
    resolvedAt: "2026-03-09T14:00:00Z",
    impactDescription: "3-day window without automated plagiarism detection",
  },
];

// ─── Report History ───────────────────────────────────────────────────────────

export const mockReportHistory: ExecutiveReport[] = [
  {
    id: "rep-1",
    type: "Executive",
    title: "Q1 2026 Executive Summary",
    period: "Q1 2026",
    format: "PDF",
    generatedAt: "2026-03-20T08:00:00Z",
    generatedBy: "Deputy Director",
    fileSize: "2.4 MB",
    status: "Ready",
  },
  {
    id: "rep-2",
    type: "Academic",
    title: "Spring 2026 Academic Performance Report",
    period: "Spring 2026",
    format: "Excel",
    generatedAt: "2026-03-15T10:30:00Z",
    generatedBy: "Deputy Director",
    fileSize: "5.1 MB",
    status: "Ready",
  },
  {
    id: "rep-3",
    type: "Financial",
    title: "February 2026 Financial Overview",
    period: "Feb 2026",
    format: "PDF",
    generatedAt: "2026-03-05T09:00:00Z",
    generatedBy: "Deputy Director",
    fileSize: "1.8 MB",
    status: "Ready",
  },
  {
    id: "rep-4",
    type: "Quality",
    title: "Q4 2025 AQAD Audit Summary",
    period: "Q4 2025",
    format: "PowerPoint",
    generatedAt: "2026-01-10T14:00:00Z",
    generatedBy: "AQAD Director",
    fileSize: "8.2 MB",
    status: "Ready",
  },
  {
    id: "rep-5",
    type: "Executive",
    title: "Annual University Performance 2025",
    period: "FY 2025",
    format: "PDF",
    generatedAt: "2026-01-05T11:00:00Z",
    generatedBy: "Deputy Director",
    fileSize: "12.6 MB",
    status: "Ready",
  },
  {
    id: "rep-6",
    type: "Custom",
    title: "Retention Crisis Analysis — Humanities",
    period: "Fall 2025",
    format: "Excel",
    generatedAt: "2026-02-20T16:00:00Z",
    generatedBy: "Deputy Director",
    fileSize: "3.3 MB",
    status: "Ready",
  },
];

// ─── Deputy Settings ──────────────────────────────────────────────────────────

export const mockDeputySettings: DeputySettings = {
  dashboardRefreshInterval: 15,
  defaultDepartment: "All",
  kpiAlertThreshold: 80,
  emailNotifications: true,
  weeklyDigest: true,
  notificationEmail: "deputy@university.edu",
  preferredReportFormat: "PDF",
};

// ─── Trend Data ───────────────────────────────────────────────────────────────

export const monthlyEnrollmentTrend = [
  { month: "Oct", value: 4640 },
  { month: "Nov", value: 4690 },
  { month: "Dec", value: 4720 },
  { month: "Jan", value: 4790 },
  { month: "Feb", value: 4810 },
  { month: "Mar", value: 4820 },
];

export const monthlyRevenueTrend = [
  { month: "Oct", value: 1_820_000 },
  { month: "Nov", value: 1_940_000 },
  { month: "Dec", value: 1_780_000 },
  { month: "Jan", value: 2_100_000 },
  { month: "Feb", value: 2_240_000 },
  { month: "Mar", value: 2_570_000 },
];

export const semesterGPATrend = [
  { semester: "Fall 2024", gpa: 3.31 },
  { semester: "Spring 2025", gpa: 3.36 },
  { semester: "Fall 2025", gpa: 3.39 },
  { semester: "Spring 2026", gpa: 3.42 },
];
