import type {
  TeacherStatus,
  AssignmentType,
  AssignmentStatus,
  WorkloadStatus,
  ReplacementReason,
  ReplacementStatus,
  ReplacementScope,
  AccessLevel,
  AccessType,
  DocumentType,
  DocumentStatus,
  AlertSeverity,
  ResourceTeacher,
  TeacherAssignment,
  WorkloadEntry,
  TeacherKPI,
  ReplacementStep,
  Replacement,
  AccessEntry,
  AccessHistoryEntry,
  TeacherDocument,
  ResourceStats,
  ResourceAlert,
} from "@/types/resource";

export type {
  TeacherStatus,
  AssignmentType,
  AssignmentStatus,
  WorkloadStatus,
  ReplacementReason,
  ReplacementStatus,
  ReplacementScope,
  AccessLevel,
  AccessType,
  DocumentType,
  DocumentStatus,
  AlertSeverity,
  ResourceTeacher,
  TeacherAssignment,
  WorkloadEntry,
  TeacherKPI,
  ReplacementStep,
  Replacement,
  AccessEntry,
  AccessHistoryEntry,
  TeacherDocument,
  ResourceStats,
  ResourceAlert,
};

// ─── Mock Data ────────────────────────────────────────────────────────────────

export const mockResourceStats: ResourceStats = {
  totalTeachers: 42,
  byStatus: { pending: 5, verified: 8, active: 27, suspended: 2 },
  activeAssignments: 63,
  avgWorkloadHours: 18,
  overloadedCount: 4,
  pendingVerification: 5,
  expiringContracts: 3,
};

export const mockTeachers: ResourceTeacher[] = [
  {
    id: "tchr-001",
    name: "Elena Volkova",
    email: "e.volkova@uou.edu",
    phone: "+998 90 123 4567",
    department: "Computer Science",
    specialization: ["Algorithms", "Data Structures", "Machine Learning"],
    status: "Active",
    coursesCount: 3,
    studentsCount: 87,
    lectureHoursWeek: 12,
    lectureHoursSemester: 144,
    kpiScore: 92,
    contractEndDate: "2026-08-31",
    registeredAt: "2024-08-15",
    maxWorkloadHours: 20,
    preferredLanguage: "English",
    bio: "Associate Professor with 10+ years of experience in CS education.",
  },
  {
    id: "tchr-002",
    name: "Rustam Nazarov",
    email: "r.nazarov@uou.edu",
    phone: "+998 91 234 5678",
    department: "Mathematics",
    specialization: ["Calculus", "Linear Algebra", "Statistics"],
    status: "Active",
    coursesCount: 4,
    studentsCount: 112,
    lectureHoursWeek: 22,
    lectureHoursSemester: 264,
    kpiScore: 78,
    contractEndDate: "2026-06-30",
    registeredAt: "2023-09-01",
    maxWorkloadHours: 20,
    preferredLanguage: "Russian",
    bio: "Senior lecturer specializing in applied mathematics.",
  },
  {
    id: "tchr-003",
    name: "Dilnoza Karimova",
    email: "d.karimova@uou.edu",
    phone: "+998 93 345 6789",
    department: "English",
    specialization: ["Academic Writing", "Business English", "IELTS Prep"],
    status: "Active",
    coursesCount: 2,
    studentsCount: 45,
    lectureHoursWeek: 8,
    lectureHoursSemester: 96,
    kpiScore: 88,
    contractEndDate: "2027-01-31",
    registeredAt: "2024-01-10",
    maxWorkloadHours: 16,
    preferredLanguage: "English",
    bio: "Certified EFL instructor with CELTA qualification.",
  },
  {
    id: "tchr-004",
    name: "Bobur Toshmatov",
    email: "b.toshmatov@uou.edu",
    phone: "+998 94 456 7890",
    department: "Computer Science",
    specialization: ["Web Development", "React", "Node.js"],
    status: "Verified",
    coursesCount: 0,
    studentsCount: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    kpiScore: 0,
    contractEndDate: "2026-12-31",
    registeredAt: "2026-03-10",
    maxWorkloadHours: 18,
    preferredLanguage: "English",
    bio: "Industry professional transitioning to academia with 8 years of full-stack experience.",
  },
  {
    id: "tchr-005",
    name: "Malika Yusupova",
    email: "m.yusupova@uou.edu",
    phone: "+998 95 567 8901",
    department: "Business",
    specialization: ["Marketing", "Strategic Management", "Entrepreneurship"],
    status: "Active",
    coursesCount: 3,
    studentsCount: 94,
    lectureHoursWeek: 14,
    lectureHoursSemester: 168,
    kpiScore: 95,
    contractEndDate: "2026-09-30",
    registeredAt: "2022-09-01",
    maxWorkloadHours: 20,
    preferredLanguage: "English",
    bio: "MBA graduate with experience in multinational corporations.",
  },
  {
    id: "tchr-006",
    name: "Jamshid Rakhimov",
    email: "j.rakhimov@uou.edu",
    phone: "+998 97 678 9012",
    department: "Physics",
    specialization: ["Quantum Mechanics", "Thermodynamics", "Optics"],
    status: "Pending",
    coursesCount: 0,
    studentsCount: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    kpiScore: 0,
    contractEndDate: null,
    registeredAt: "2026-03-20",
    maxWorkloadHours: 16,
    preferredLanguage: "Russian",
    bio: "PhD candidate at National University with strong research background.",
  },
  {
    id: "tchr-007",
    name: "Nargiza Islamova",
    email: "n.islamova@uou.edu",
    phone: "+998 90 789 0123",
    department: "Computer Science",
    specialization: ["Database Systems", "SQL", "Data Engineering"],
    status: "Pending",
    coursesCount: 0,
    studentsCount: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    kpiScore: 0,
    contractEndDate: null,
    registeredAt: "2026-03-18",
    maxWorkloadHours: 18,
    preferredLanguage: "English",
    bio: "Data engineer with 5 years of industry experience.",
  },
  {
    id: "tchr-008",
    name: "Otabek Mirzayev",
    email: "o.mirzayev@uou.edu",
    phone: "+998 91 890 1234",
    department: "Business",
    specialization: ["Finance", "Accounting", "Financial Modeling"],
    status: "Active",
    coursesCount: 5,
    studentsCount: 143,
    lectureHoursWeek: 26,
    lectureHoursSemester: 312,
    kpiScore: 71,
    contractEndDate: "2026-04-30",
    registeredAt: "2021-09-01",
    maxWorkloadHours: 20,
    preferredLanguage: "Russian",
    bio: "CFA charterholder and experienced finance educator.",
  },
  {
    id: "tchr-009",
    name: "Sarvinoz Umarova",
    email: "s.umarova@uou.edu",
    phone: "+998 93 901 2345",
    department: "Psychology",
    specialization: ["Organizational Behavior", "HR Management", "Leadership"],
    status: "Active",
    coursesCount: 2,
    studentsCount: 58,
    lectureHoursWeek: 10,
    lectureHoursSemester: 120,
    kpiScore: 89,
    contractEndDate: "2027-06-30",
    registeredAt: "2023-01-15",
    maxWorkloadHours: 16,
    preferredLanguage: "English",
    bio: "Industrial-organizational psychologist focused on leadership development.",
  },
  {
    id: "tchr-010",
    name: "Firdavs Ergashev",
    email: "f.ergashev@uou.edu",
    phone: "+998 94 012 3456",
    department: "Computer Science",
    specialization: ["Cybersecurity", "Network Administration", "Linux"],
    status: "Suspended",
    coursesCount: 0,
    studentsCount: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    kpiScore: 45,
    contractEndDate: "2026-05-31",
    registeredAt: "2022-09-01",
    maxWorkloadHours: 18,
    preferredLanguage: "English",
    bio: "Network security specialist with CISSP certification.",
  },
  {
    id: "tchr-011",
    name: "Aziza Xasanova",
    email: "a.xasanova@uou.edu",
    phone: "+998 95 123 4567",
    department: "Mathematics",
    specialization: ["Discrete Mathematics", "Graph Theory", "Combinatorics"],
    status: "Active",
    coursesCount: 3,
    studentsCount: 76,
    lectureHoursWeek: 14,
    lectureHoursSemester: 168,
    kpiScore: 84,
    contractEndDate: "2026-08-31",
    registeredAt: "2023-09-01",
    maxWorkloadHours: 18,
    preferredLanguage: "Uzbek",
    bio: "Applied mathematician with focus on computer science applications.",
  },
  {
    id: "tchr-012",
    name: "Ulugbek Sodiqov",
    email: "u.sodiqov@uou.edu",
    phone: "+998 97 234 5678",
    department: "Business",
    specialization: ["Operations Management", "Supply Chain", "Project Management"],
    status: "Pending",
    coursesCount: 0,
    studentsCount: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    kpiScore: 0,
    contractEndDate: null,
    registeredAt: "2026-03-22",
    maxWorkloadHours: 16,
    preferredLanguage: "Russian",
    bio: "PMP-certified project manager with 12 years of industry experience.",
  },
  {
    id: "tchr-013",
    name: "Iroda Hamidova",
    email: "i.hamidova@uou.edu",
    phone: "+998 90 345 6789",
    department: "English",
    specialization: ["TOEFL Prep", "Communication Skills", "Academic Reading"],
    status: "Verified",
    coursesCount: 0,
    studentsCount: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    kpiScore: 0,
    contractEndDate: "2027-01-31",
    registeredAt: "2026-03-05",
    maxWorkloadHours: 18,
    preferredLanguage: "English",
    bio: "Experienced ESL instructor with 7 years in higher education.",
  },
  {
    id: "tchr-014",
    name: "Sherzod Tursunov",
    email: "sh.tursunov@uou.edu",
    phone: "+998 91 456 7890",
    department: "Physics",
    specialization: ["Classical Mechanics", "Electromagnetism", "Mathematical Physics"],
    status: "Active",
    coursesCount: 4,
    studentsCount: 102,
    lectureHoursWeek: 18,
    lectureHoursSemester: 216,
    kpiScore: 80,
    contractEndDate: "2026-06-30",
    registeredAt: "2022-01-10",
    maxWorkloadHours: 20,
    preferredLanguage: "Russian",
    bio: "Associate Professor of Physics with PhD from Moscow State University.",
  },
  {
    id: "tchr-015",
    name: "Gulnora Baxtiyor",
    email: "g.baxtiyor@uou.edu",
    phone: "+998 93 567 8901",
    department: "Psychology",
    specialization: ["Cognitive Psychology", "Research Methods", "Statistics for Social Sciences"],
    status: "Pending",
    coursesCount: 0,
    studentsCount: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    kpiScore: 0,
    contractEndDate: null,
    registeredAt: "2026-03-24",
    maxWorkloadHours: 14,
    preferredLanguage: "English",
    bio: "Postdoctoral researcher with expertise in cognitive psychology.",
  },
];

export const mockAssignments: TeacherAssignment[] = [
  {
    id: "asgn-001",
    teacherId: "tchr-001",
    teacherName: "Elena Volkova",
    program: "CS Bachelor's",
    course: "Algorithms & Data Structures",
    courseCode: "CS301",
    group: "CS-2023-A",
    type: "Primary",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-002",
    teacherId: "tchr-001",
    teacherName: "Elena Volkova",
    program: "CS Bachelor's",
    course: "Machine Learning Fundamentals",
    courseCode: "CS402",
    group: "CS-2022-A",
    type: "Primary",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-003",
    teacherId: "tchr-001",
    teacherName: "Elena Volkova",
    program: "CS Bachelor's",
    course: "Introduction to Programming",
    courseCode: "CS101",
    group: "CS-2025-B",
    type: "CoTeaching",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-004",
    teacherId: "tchr-002",
    teacherName: "Rustam Nazarov",
    program: "CS Bachelor's",
    course: "Calculus I",
    courseCode: "MATH101",
    group: "CS-2025-A",
    type: "Primary",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-005",
    teacherId: "tchr-002",
    teacherName: "Rustam Nazarov",
    program: "CS Bachelor's",
    course: "Linear Algebra",
    courseCode: "MATH201",
    group: "CS-2024-A",
    type: "Primary",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-006",
    teacherId: "tchr-002",
    teacherName: "Rustam Nazarov",
    program: "Business Bachelor's",
    course: "Business Statistics",
    courseCode: "BUS201",
    group: "BUS-2024-A",
    type: "Primary",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-007",
    teacherId: "tchr-005",
    teacherName: "Malika Yusupova",
    program: "Business Bachelor's",
    course: "Marketing Principles",
    courseCode: "BUS301",
    group: "BUS-2023-A",
    type: "Primary",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-008",
    teacherId: "tchr-008",
    teacherName: "Otabek Mirzayev",
    program: "Business Bachelor's",
    course: "Corporate Finance",
    courseCode: "BUS401",
    group: "BUS-2022-A",
    type: "Primary",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-009",
    teacherId: "tchr-008",
    teacherName: "Otabek Mirzayev",
    program: "Business Bachelor's",
    course: "Financial Accounting",
    courseCode: "BUS201",
    group: "BUS-2024-B",
    type: "Primary",
    startDate: "2026-01-15",
    endDate: "2026-06-15",
    status: "Active",
  },
  {
    id: "asgn-010",
    teacherId: "tchr-001",
    teacherName: "Elena Volkova",
    program: "CS Bachelor's",
    course: "Data Mining",
    courseCode: "CS350",
    group: "CS-2023-B",
    type: "Primary",
    startDate: "2025-09-01",
    endDate: "2026-01-10",
    status: "Completed",
  },
];

export const mockWorkload: WorkloadEntry[] = [
  {
    teacherId: "tchr-001",
    teacherName: "Elena Volkova",
    department: "Computer Science",
    courses: 3,
    lectureHoursWeek: 12,
    lectureHoursSemester: 144,
    students: 87,
    qaActivity: 24,
    gradingQueue: 12,
    maxWorkloadHours: 20,
    status: "Normal",
  },
  {
    teacherId: "tchr-002",
    teacherName: "Rustam Nazarov",
    department: "Mathematics",
    courses: 4,
    lectureHoursWeek: 22,
    lectureHoursSemester: 264,
    students: 112,
    qaActivity: 8,
    gradingQueue: 45,
    maxWorkloadHours: 20,
    status: "Overloaded",
  },
  {
    teacherId: "tchr-003",
    teacherName: "Dilnoza Karimova",
    department: "English",
    courses: 2,
    lectureHoursWeek: 8,
    lectureHoursSemester: 96,
    students: 45,
    qaActivity: 15,
    gradingQueue: 20,
    maxWorkloadHours: 16,
    status: "Normal",
  },
  {
    teacherId: "tchr-005",
    teacherName: "Malika Yusupova",
    department: "Business",
    courses: 3,
    lectureHoursWeek: 14,
    lectureHoursSemester: 168,
    students: 94,
    qaActivity: 18,
    gradingQueue: 22,
    maxWorkloadHours: 20,
    status: "Normal",
  },
  {
    teacherId: "tchr-008",
    teacherName: "Otabek Mirzayev",
    department: "Business",
    courses: 5,
    lectureHoursWeek: 26,
    lectureHoursSemester: 312,
    students: 143,
    qaActivity: 5,
    gradingQueue: 67,
    maxWorkloadHours: 20,
    status: "Overloaded",
  },
  {
    teacherId: "tchr-009",
    teacherName: "Sarvinoz Umarova",
    department: "Psychology",
    courses: 2,
    lectureHoursWeek: 10,
    lectureHoursSemester: 120,
    students: 58,
    qaActivity: 12,
    gradingQueue: 14,
    maxWorkloadHours: 16,
    status: "High",
  },
  {
    teacherId: "tchr-011",
    teacherName: "Aziza Xasanova",
    department: "Mathematics",
    courses: 3,
    lectureHoursWeek: 14,
    lectureHoursSemester: 168,
    students: 76,
    qaActivity: 10,
    gradingQueue: 30,
    maxWorkloadHours: 18,
    status: "Normal",
  },
  {
    teacherId: "tchr-014",
    teacherName: "Sherzod Tursunov",
    department: "Physics",
    courses: 4,
    lectureHoursWeek: 18,
    lectureHoursSemester: 216,
    students: 102,
    qaActivity: 9,
    gradingQueue: 28,
    maxWorkloadHours: 20,
    status: "High",
  },
  {
    teacherId: "tchr-004",
    teacherName: "Bobur Toshmatov",
    department: "Computer Science",
    courses: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    students: 0,
    qaActivity: 0,
    gradingQueue: 0,
    maxWorkloadHours: 18,
    status: "Underloaded",
  },
  {
    teacherId: "tchr-013",
    teacherName: "Iroda Hamidova",
    department: "English",
    courses: 0,
    lectureHoursWeek: 0,
    lectureHoursSemester: 0,
    students: 0,
    qaActivity: 0,
    gradingQueue: 0,
    maxWorkloadHours: 18,
    status: "Underloaded",
  },
];

export const mockKPIs: TeacherKPI[] = [
  {
    teacherId: "tchr-001",
    teacherName: "Elena Volkova",
    department: "Computer Science",
    avgAttendance: 88,
    feedbackScore: 4.6,
    qaSLAPercent: 94,
    qaAvgResponseHours: 8,
    qaUnanswered: 2,
    aqadFirstPassRate: 100,
    overallScore: 92,
    semester: "Spring 2026",
    prevSemesterScore: 89,
  },
  {
    teacherId: "tchr-002",
    teacherName: "Rustam Nazarov",
    department: "Mathematics",
    avgAttendance: 72,
    feedbackScore: 3.8,
    qaSLAPercent: 65,
    qaAvgResponseHours: 32,
    qaUnanswered: 14,
    aqadFirstPassRate: 75,
    overallScore: 78,
    semester: "Spring 2026",
    prevSemesterScore: 80,
  },
  {
    teacherId: "tchr-003",
    teacherName: "Dilnoza Karimova",
    department: "English",
    avgAttendance: 91,
    feedbackScore: 4.4,
    qaSLAPercent: 97,
    qaAvgResponseHours: 6,
    qaUnanswered: 0,
    aqadFirstPassRate: 100,
    overallScore: 88,
    semester: "Spring 2026",
    prevSemesterScore: 85,
  },
  {
    teacherId: "tchr-005",
    teacherName: "Malika Yusupova",
    department: "Business",
    avgAttendance: 93,
    feedbackScore: 4.8,
    qaSLAPercent: 98,
    qaAvgResponseHours: 4,
    qaUnanswered: 0,
    aqadFirstPassRate: 100,
    overallScore: 95,
    semester: "Spring 2026",
    prevSemesterScore: 93,
  },
  {
    teacherId: "tchr-008",
    teacherName: "Otabek Mirzayev",
    department: "Business",
    avgAttendance: 68,
    feedbackScore: 3.4,
    qaSLAPercent: 52,
    qaAvgResponseHours: 48,
    qaUnanswered: 23,
    aqadFirstPassRate: 60,
    overallScore: 71,
    semester: "Spring 2026",
    prevSemesterScore: 76,
  },
  {
    teacherId: "tchr-009",
    teacherName: "Sarvinoz Umarova",
    department: "Psychology",
    avgAttendance: 87,
    feedbackScore: 4.5,
    qaSLAPercent: 92,
    qaAvgResponseHours: 10,
    qaUnanswered: 1,
    aqadFirstPassRate: 100,
    overallScore: 89,
    semester: "Spring 2026",
    prevSemesterScore: 88,
  },
  {
    teacherId: "tchr-011",
    teacherName: "Aziza Xasanova",
    department: "Mathematics",
    avgAttendance: 82,
    feedbackScore: 4.2,
    qaSLAPercent: 88,
    qaAvgResponseHours: 14,
    qaUnanswered: 3,
    aqadFirstPassRate: 100,
    overallScore: 84,
    semester: "Spring 2026",
    prevSemesterScore: 81,
  },
  {
    teacherId: "tchr-014",
    teacherName: "Sherzod Tursunov",
    department: "Physics",
    avgAttendance: 79,
    feedbackScore: 4.0,
    qaSLAPercent: 85,
    qaAvgResponseHours: 16,
    qaUnanswered: 4,
    aqadFirstPassRate: 75,
    overallScore: 80,
    semester: "Spring 2026",
    prevSemesterScore: 79,
  },
];

export const mockReplacements: Replacement[] = [
  {
    id: "repl-001",
    currentTeacherId: "tchr-010",
    currentTeacherName: "Firdavs Ergashev",
    newTeacherId: "tchr-004",
    newTeacherName: "Bobur Toshmatov",
    reason: "Disciplinary",
    effectiveDate: "2026-03-01",
    status: "Completed",
    scope: "All",
    courses: ["CS201 — Cybersecurity Basics", "CS305 — Network Administration"],
    isTemporary: false,
    autoRevert: false,
    initiatedBy: "Resource Dept",
    initiatedAt: "2026-02-25",
    steps: [
      { label: "Initiated", status: "Completed", completedAt: "2026-02-25" },
      { label: "Stakeholders Notified", status: "Completed", completedAt: "2026-02-26" },
      { label: "Content Transferred", status: "Completed", completedAt: "2026-02-28" },
      { label: "Access Updated", status: "Completed", completedAt: "2026-03-01" },
      { label: "Completed", status: "Completed", completedAt: "2026-03-01" },
    ],
  },
  {
    id: "repl-002",
    currentTeacherId: "tchr-002",
    currentTeacherName: "Rustam Nazarov",
    newTeacherId: "tchr-011",
    newTeacherName: "Aziza Xasanova",
    reason: "Medical Leave",
    effectiveDate: "2026-03-20",
    status: "InProgress",
    scope: "Specific",
    courses: ["MATH101 — Calculus I (CS-2025-A)"],
    isTemporary: true,
    endDate: "2026-04-20",
    autoRevert: true,
    initiatedBy: "Resource Dept",
    initiatedAt: "2026-03-18",
    steps: [
      { label: "Initiated", status: "Completed", completedAt: "2026-03-18" },
      { label: "Stakeholders Notified", status: "Completed", completedAt: "2026-03-19" },
      { label: "Content Transferred", status: "InProgress" },
      { label: "Access Updated", status: "Pending" },
      { label: "Completed", status: "Pending" },
    ],
  },
  {
    id: "repl-003",
    currentTeacherId: "tchr-008",
    currentTeacherName: "Otabek Mirzayev",
    newTeacherId: "tchr-005",
    newTeacherName: "Malika Yusupova",
    reason: "Overload",
    effectiveDate: "2026-04-01",
    status: "Initiated",
    scope: "Specific",
    courses: ["BUS201 — Financial Accounting (BUS-2024-B)"],
    isTemporary: false,
    autoRevert: false,
    initiatedBy: "Resource Dept",
    initiatedAt: "2026-03-24",
    steps: [
      { label: "Initiated", status: "Completed", completedAt: "2026-03-24" },
      { label: "Stakeholders Notified", status: "Pending" },
      { label: "Content Transferred", status: "Pending" },
      { label: "Access Updated", status: "Pending" },
      { label: "Completed", status: "Pending" },
    ],
  },
];

export const mockAccessEntries: AccessEntry[] = [
  {
    id: "acc-001",
    teacherId: "tchr-001",
    teacherName: "Elena Volkova",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    level: "Full",
    type: "Permanent",
    grantedBy: "Resource Dept",
    grantedAt: "2026-01-15",
  },
  {
    id: "acc-002",
    teacherId: "tchr-001",
    teacherName: "Elena Volkova",
    courseId: "crs-002",
    courseName: "Machine Learning Fundamentals",
    courseCode: "CS402",
    level: "Full",
    type: "Permanent",
    grantedBy: "Resource Dept",
    grantedAt: "2026-01-15",
  },
  {
    id: "acc-003",
    teacherId: "tchr-002",
    teacherName: "Rustam Nazarov",
    courseId: "crs-003",
    courseName: "Calculus I",
    courseCode: "MATH101",
    level: "Full",
    type: "Permanent",
    grantedBy: "Resource Dept",
    grantedAt: "2026-01-15",
  },
  {
    id: "acc-004",
    teacherId: "tchr-011",
    teacherName: "Aziza Xasanova",
    courseId: "crs-003",
    courseName: "Calculus I",
    courseCode: "MATH101",
    level: "ReadOnly",
    type: "Temporary",
    expiryDate: "2026-04-20",
    grantedBy: "Resource Dept",
    grantedAt: "2026-03-19",
  },
  {
    id: "acc-005",
    teacherId: "tchr-005",
    teacherName: "Malika Yusupova",
    courseId: "crs-007",
    courseName: "Marketing Principles",
    courseCode: "BUS301",
    level: "Full",
    type: "Permanent",
    grantedBy: "Resource Dept",
    grantedAt: "2026-01-15",
  },
  {
    id: "acc-006",
    teacherId: "tchr-008",
    teacherName: "Otabek Mirzayev",
    courseId: "crs-008",
    courseName: "Corporate Finance",
    courseCode: "BUS401",
    level: "Full",
    type: "Permanent",
    grantedBy: "Resource Dept",
    grantedAt: "2026-01-15",
  },
  {
    id: "acc-007",
    teacherId: "tchr-004",
    teacherName: "Bobur Toshmatov",
    courseId: "crs-010",
    courseName: "Cybersecurity Basics",
    courseCode: "CS201",
    level: "Full",
    type: "Permanent",
    grantedBy: "Resource Dept",
    grantedAt: "2026-03-01",
  },
];

export const mockAccessHistory: AccessHistoryEntry[] = [
  {
    id: "hist-001",
    teacherName: "Bobur Toshmatov",
    courseName: "Cybersecurity Basics",
    courseCode: "CS201",
    action: "Granted",
    level: "Full",
    reason: "Replacement for Firdavs Ergashev (Disciplinary)",
    actor: "Resource Dept",
    timestamp: "2026-03-01T10:00:00Z",
  },
  {
    id: "hist-002",
    teacherName: "Firdavs Ergashev",
    courseName: "Cybersecurity Basics",
    courseCode: "CS201",
    action: "Revoked",
    level: "Full",
    reason: "Disciplinary suspension — replacement initiated",
    actor: "Resource Dept",
    timestamp: "2026-03-01T09:55:00Z",
  },
  {
    id: "hist-003",
    teacherName: "Aziza Xasanova",
    courseName: "Calculus I",
    courseCode: "MATH101",
    action: "Granted",
    level: "ReadOnly",
    reason: "Temporary coverage — Rustam Nazarov on medical leave",
    actor: "Resource Dept",
    timestamp: "2026-03-19T14:30:00Z",
  },
  {
    id: "hist-004",
    teacherName: "Elena Volkova",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    action: "Granted",
    level: "Full",
    reason: "New semester assignment",
    actor: "Resource Dept",
    timestamp: "2026-01-15T09:00:00Z",
  },
  {
    id: "hist-005",
    teacherName: "Rustam Nazarov",
    courseName: "Linear Algebra",
    courseCode: "MATH201",
    action: "Granted",
    level: "Full",
    reason: "New semester assignment",
    actor: "Resource Dept",
    timestamp: "2026-01-15T09:00:00Z",
  },
];

export const mockDocuments: TeacherDocument[] = [
  {
    id: "doc-001",
    teacherId: "tchr-006",
    type: "Certificate",
    name: "PhD Diploma — National University.pdf",
    status: "Pending",
    uploadedAt: "2026-03-20",
  },
  {
    id: "doc-002",
    teacherId: "tchr-006",
    type: "Contract",
    name: "Employment Contract — Jamshid Rakhimov.pdf",
    status: "Pending",
    uploadedAt: "2026-03-20",
  },
  {
    id: "doc-003",
    teacherId: "tchr-006",
    type: "CV",
    name: "CV — Jamshid Rakhimov 2026.pdf",
    status: "Pending",
    uploadedAt: "2026-03-20",
  },
  {
    id: "doc-004",
    teacherId: "tchr-007",
    type: "Certificate",
    name: "AWS Data Engineering Cert.pdf",
    status: "Pending",
    uploadedAt: "2026-03-18",
  },
  {
    id: "doc-005",
    teacherId: "tchr-007",
    type: "Contract",
    name: "Employment Contract — Nargiza Islamova.pdf",
    status: "Pending",
    uploadedAt: "2026-03-18",
  },
  {
    id: "doc-006",
    teacherId: "tchr-007",
    type: "CV",
    name: "CV — Nargiza Islamova 2026.pdf",
    status: "Pending",
    uploadedAt: "2026-03-18",
  },
  {
    id: "doc-007",
    teacherId: "tchr-001",
    type: "Certificate",
    name: "PhD Diploma — Moscow State University.pdf",
    status: "Verified",
    uploadedAt: "2024-08-10",
  },
  {
    id: "doc-008",
    teacherId: "tchr-001",
    type: "Contract",
    name: "Employment Contract — Elena Volkova.pdf",
    status: "Verified",
    uploadedAt: "2024-08-10",
  },
  {
    id: "doc-009",
    teacherId: "tchr-001",
    type: "CV",
    name: "CV — Elena Volkova 2024.pdf",
    status: "Verified",
    uploadedAt: "2024-08-10",
  },
];

export const mockResourceAlerts: ResourceAlert[] = [
  {
    id: "alert-001",
    type: "workload",
    teacherName: "Rustam Nazarov",
    teacherId: "tchr-002",
    message: "22 hrs/week — 110% of max. Recommend assigning a TA.",
    severity: "danger",
  },
  {
    id: "alert-002",
    type: "workload",
    teacherName: "Otabek Mirzayev",
    teacherId: "tchr-008",
    message: "26 hrs/week — 130% of max. Consider reassigning 1–2 courses.",
    severity: "danger",
  },
  {
    id: "alert-003",
    type: "performance",
    teacherName: "Otabek Mirzayev",
    teacherId: "tchr-008",
    message: "Q&A SLA at 52% — below 80% threshold. Avg response: 48 hrs.",
    severity: "warning",
  },
  {
    id: "alert-004",
    type: "performance",
    teacherName: "Rustam Nazarov",
    teacherId: "tchr-002",
    message: "Q&A SLA at 65% — below 80% threshold. 14 unanswered questions.",
    severity: "warning",
  },
  {
    id: "alert-005",
    type: "contract",
    teacherName: "Otabek Mirzayev",
    teacherId: "tchr-008",
    message: "Contract expires on Apr 30, 2026 — 36 days remaining.",
    severity: "warning",
  },
  {
    id: "alert-006",
    type: "contract",
    teacherName: "Rustam Nazarov",
    teacherId: "tchr-002",
    message: "Contract expires on Jun 30, 2026 — 97 days remaining.",
    severity: "info",
  },
  {
    id: "alert-007",
    type: "contract",
    teacherName: "Sherzod Tursunov",
    teacherId: "tchr-014",
    message: "Contract expires on Jun 30, 2026 — 97 days remaining.",
    severity: "info",
  },
];

// Departments list (for dropdowns)
export const DEPARTMENTS = [
  "Computer Science",
  "Mathematics",
  "English",
  "Business",
  "Physics",
  "Psychology",
] as const;

// Specialization options (for multi-select)
export const SPECIALIZATIONS = [
  "Algorithms",
  "Data Structures",
  "Machine Learning",
  "Web Development",
  "React",
  "Node.js",
  "Cybersecurity",
  "Network Administration",
  "Database Systems",
  "Calculus",
  "Linear Algebra",
  "Statistics",
  "Discrete Mathematics",
  "Academic Writing",
  "Business English",
  "Marketing",
  "Strategic Management",
  "Finance",
  "Accounting",
  "Quantum Mechanics",
  "Thermodynamics",
  "Organizational Behavior",
  "Leadership",
] as const;
