import type {
  StudentProfile,
  Course,
  Lecture,
  LectureMaterial,
  Assignment,
  Exam,
  Grade,
  AttendanceRecord,
  CourseAttendanceSummary,
  Payment,
  FinancialSummary,
  StudentNotification,
  ScheduleEvent,
  QAMessage,
  ChatMessage,
  ExamQuestion,
} from "@/types/student";

export const mockStudentProfile: StudentProfile = {
  id: "stu-001",
  name: "Amir Saidov",
  email: "amir.saidov@uou.edu",
  studentId: "2024-CS-0142",
  program: "Computer Science — Bachelor's",
  faculty: "Faculty of Engineering & Technology",
  year: 2,
  semester: 4,
  group: "CS-24B",
  enrollmentDate: "2024-09-01",
  accessStatus: "Active",
  gpa: 3.6,
  totalCredits: 120,
  earnedCredits: 54,
};

// ─── Courses ───────────────────────────────────────────────────────────────────

export const mockCourses: Course[] = [
  {
    id: "crs-001",
    code: "CS301",
    name: "Algorithms & Data Structures",
    description:
      "Study of fundamental algorithms and data structures including sorting, searching, trees, graphs, and dynamic programming.",
    teacherName: "Prof. Elena Volkova",
    teacherId: "tch-001",
    credits: 5,
    semester: 4,
    status: "in_progress",
    progress: 62,
    currentGrade: "B+",
    currentScore: 78,
    attendanceRate: 88,
    totalLectures: 24,
    completedLectures: 15,
    schedule: "Mon / Wed 10:00–11:30",
    language: "English",
    category: "Core",
    prerequisites: ["CS201 — Programming Fundamentals"],
    gradingPolicy: [
      { type: "Assignments", weight: 30, description: "6 assignments, best 5 counted" },
      { type: "Midterm Exam", weight: 25, description: "Written, 90 minutes" },
      { type: "Final Exam", weight: 35, description: "Written, 120 minutes" },
      { type: "Participation", weight: 10, description: "In-class activity" },
    ],
    modules: [
      {
        id: "mod-001",
        courseId: "crs-001",
        name: "Module 1: Sorting Algorithms",
        orderIndex: 1,
        status: "completed",
        lectureIds: ["lec-001", "lec-002", "lec-003"],
      },
      {
        id: "mod-002",
        courseId: "crs-001",
        name: "Module 2: Trees & Graphs",
        orderIndex: 2,
        status: "in_progress",
        lectureIds: ["lec-004", "lec-005", "lec-006"],
      },
      {
        id: "mod-003",
        courseId: "crs-001",
        name: "Module 3: Dynamic Programming",
        orderIndex: 3,
        status: "available",
        lectureIds: ["lec-007", "lec-008"],
      },
    ],
  },
  {
    id: "crs-002",
    code: "MATH204",
    name: "Linear Algebra",
    description:
      "Vectors, matrices, linear transformations, eigenvalues, and applications in computer science.",
    teacherName: "Dr. Rustam Nazarov",
    teacherId: "tch-002",
    credits: 4,
    semester: 4,
    status: "in_progress",
    progress: 50,
    currentGrade: "A-",
    currentScore: 87,
    attendanceRate: 95,
    totalLectures: 20,
    completedLectures: 10,
    schedule: "Tue / Thu 09:00–10:30",
    language: "English",
    category: "Core",
    gradingPolicy: [
      { type: "Assignments", weight: 35 },
      { type: "Midterm Exam", weight: 30 },
      { type: "Final Exam", weight: 35 },
    ],
    modules: [
      {
        id: "mod-004",
        courseId: "crs-002",
        name: "Module 1: Vectors & Matrices",
        orderIndex: 1,
        status: "completed",
        lectureIds: ["lec-009", "lec-010"],
      },
      {
        id: "mod-005",
        courseId: "crs-002",
        name: "Module 2: Eigenvalues",
        orderIndex: 2,
        status: "in_progress",
        lectureIds: ["lec-011", "lec-012"],
      },
    ],
  },
  {
    id: "crs-003",
    code: "CS312",
    name: "Database Systems",
    description:
      "Relational database design, SQL, normalization, transactions, indexing, and NoSQL overview.",
    teacherName: "Prof. Ivan Petrenko",
    teacherId: "tch-003",
    credits: 4,
    semester: 4,
    status: "in_progress",
    progress: 40,
    currentGrade: "B",
    currentScore: 72,
    attendanceRate: 75,
    totalLectures: 22,
    completedLectures: 9,
    schedule: "Mon / Fri 14:00–15:30",
    language: "English",
    category: "Core",
    gradingPolicy: [
      { type: "Labs", weight: 40 },
      { type: "Midterm Exam", weight: 25 },
      { type: "Final Exam", weight: 35 },
    ],
    modules: [
      {
        id: "mod-006",
        courseId: "crs-003",
        name: "Module 1: Relational Model",
        orderIndex: 1,
        status: "completed",
        lectureIds: ["lec-013", "lec-014"],
      },
      {
        id: "mod-007",
        courseId: "crs-003",
        name: "Module 2: SQL",
        orderIndex: 2,
        status: "in_progress",
        lectureIds: ["lec-015", "lec-016"],
      },
    ],
  },
  {
    id: "crs-004",
    code: "ENG201",
    name: "Technical Writing",
    description:
      "Academic and professional writing for engineers: reports, proposals, documentation.",
    teacherName: "Ms. Laura Chen",
    teacherId: "tch-004",
    credits: 2,
    semester: 4,
    status: "in_progress",
    progress: 70,
    currentGrade: "A",
    currentScore: 93,
    attendanceRate: 100,
    totalLectures: 14,
    completedLectures: 10,
    schedule: "Wed 16:00–17:30",
    language: "English",
    category: "Elective",
    gradingPolicy: [
      { type: "Essays", weight: 50 },
      { type: "Presentations", weight: 30 },
      { type: "Participation", weight: 20 },
    ],
    modules: [
      {
        id: "mod-008",
        courseId: "crs-004",
        name: "Module 1: Technical Reports",
        orderIndex: 1,
        status: "completed",
        lectureIds: ["lec-017", "lec-018"],
      },
    ],
  },
  {
    id: "crs-005",
    code: "CS210",
    name: "Operating Systems",
    description:
      "Process management, memory management, file systems, concurrency, and OS internals.",
    teacherName: "Prof. Boris Klimov",
    teacherId: "tch-005",
    credits: 5,
    semester: 3,
    status: "completed",
    progress: 100,
    currentGrade: "A-",
    currentScore: 88,
    attendanceRate: 91,
    totalLectures: 26,
    completedLectures: 26,
    schedule: "Completed",
    language: "English",
    category: "Core",
    gradingPolicy: [
      { type: "Assignments", weight: 25 },
      { type: "Midterm Exam", weight: 35 },
      { type: "Final Exam", weight: 40 },
    ],
    modules: [],
  },
];

// ─── Lectures ──────────────────────────────────────────────────────────────────

const csMaterials: LectureMaterial[] = [
  {
    id: "mat-001",
    lectureId: "lec-005",
    name: "Lecture Slides — Binary Trees",
    type: "slides",
    url: "#",
    size: 1_500_000,
  },
  {
    id: "mat-002",
    lectureId: "lec-005",
    name: "Practice Problems Set 3",
    type: "pdf",
    url: "#",
    size: 800_000,
  },
  {
    id: "mat-003",
    lectureId: "lec-005",
    name: "Tree Traversal — Reference Code",
    type: "link",
    url: "#",
  },
];

export const mockLectures: Lecture[] = [
  {
    id: "lec-001",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    moduleId: "mod-001",
    title: "Introduction to Sorting",
    description: "Overview of sorting problem, comparison-based lower bound, Bubble Sort and Insertion Sort.",
    teacherName: "Prof. Elena Volkova",
    date: "2026-02-18",
    startTime: "10:00",
    endTime: "11:30",
    status: "completed",
    attendanceStatus: "present",
    materials: [],
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-002",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    moduleId: "mod-001",
    title: "Merge Sort & Quick Sort",
    description: "Divide and conquer approach. Merge sort analysis. Quick sort with partitioning strategies.",
    teacherName: "Prof. Elena Volkova",
    date: "2026-02-25",
    startTime: "10:00",
    endTime: "11:30",
    status: "completed",
    attendanceStatus: "present",
    materials: [],
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-003",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    moduleId: "mod-001",
    title: "Heap Sort & Counting Sort",
    description: "Priority queues, heapify, heap sort. Non-comparison sorts: Counting Sort, Radix Sort.",
    teacherName: "Prof. Elena Volkova",
    date: "2026-03-04",
    startTime: "10:00",
    endTime: "11:30",
    status: "completed",
    attendanceStatus: "absent",
    materials: [],
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-004",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    moduleId: "mod-002",
    title: "Binary Search Trees",
    description: "BST properties, insertion, deletion, search. Balance considerations.",
    teacherName: "Prof. Elena Volkova",
    date: "2026-03-11",
    startTime: "10:00",
    endTime: "11:30",
    status: "completed",
    attendanceStatus: "present",
    materials: [],
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-005",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    moduleId: "mod-002",
    title: "AVL Trees & Red-Black Trees",
    description: "Self-balancing trees. AVL rotations, red-black invariants, amortized analysis.",
    teacherName: "Prof. Elena Volkova",
    date: "2026-03-18",
    startTime: "10:00",
    endTime: "11:30",
    status: "completed",
    attendanceStatus: "present",
    materials: csMaterials,
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-006",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    moduleId: "mod-002",
    title: "Graph Representations & BFS",
    description: "Adjacency list vs matrix, BFS algorithm, shortest path in unweighted graphs.",
    teacherName: "Prof. Elena Volkova",
    date: "2026-03-25",
    startTime: "10:00",
    endTime: "11:30",
    status: "upcoming",
    materials: [],
    isLive: false,
    meetingUrl: "https://teams.microsoft.com/meet/cs301",
  },
  {
    id: "lec-007",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    moduleId: "mod-003",
    title: "DFS & Topological Sort",
    description: "DFS traversal, cycle detection, topological ordering of DAGs.",
    teacherName: "Prof. Elena Volkova",
    date: "2026-03-26",
    startTime: "10:00",
    endTime: "11:30",
    status: "upcoming",
    materials: [],
    isLive: false,
    meetingUrl: "https://teams.microsoft.com/meet/cs301",
  },
  {
    id: "lec-008",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    moduleId: "mod-003",
    title: "Dynamic Programming Intro",
    description: "Overlapping subproblems, memoization, tabulation. Classic problems: Fibonacci, Knapsack.",
    teacherName: "Prof. Elena Volkova",
    date: "2026-04-01",
    startTime: "10:00",
    endTime: "11:30",
    status: "upcoming",
    materials: [],
    isLive: false,
    meetingUrl: "https://teams.microsoft.com/meet/cs301",
  },
  {
    id: "lec-009",
    courseId: "crs-002",
    courseName: "Linear Algebra",
    moduleId: "mod-004",
    title: "Vectors & Vector Spaces",
    description: "Vector operations, linear independence, span, basis, dimension.",
    teacherName: "Dr. Rustam Nazarov",
    date: "2026-03-04",
    startTime: "09:00",
    endTime: "10:30",
    status: "completed",
    attendanceStatus: "present",
    materials: [],
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-010",
    courseId: "crs-002",
    courseName: "Linear Algebra",
    moduleId: "mod-004",
    title: "Matrix Operations",
    description: "Matrix multiplication, transpose, inverse, determinants.",
    teacherName: "Dr. Rustam Nazarov",
    date: "2026-03-11",
    startTime: "09:00",
    endTime: "10:30",
    status: "completed",
    attendanceStatus: "late",
    materials: [],
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-011",
    courseId: "crs-002",
    courseName: "Linear Algebra",
    moduleId: "mod-005",
    title: "Eigenvalues & Eigenvectors",
    description: "Characteristic polynomial, eigendecomposition, diagonalization.",
    teacherName: "Dr. Rustam Nazarov",
    date: "2026-03-24",
    startTime: "09:00",
    endTime: "10:30",
    status: "live",
    attendanceStatus: "present",
    materials: [],
    isLive: true,
    meetingUrl: "https://teams.microsoft.com/meet/math204",
  },
  {
    id: "lec-012",
    courseId: "crs-002",
    courseName: "Linear Algebra",
    moduleId: "mod-005",
    title: "Singular Value Decomposition",
    description: "SVD and applications: image compression, PCA, dimensionality reduction.",
    teacherName: "Dr. Rustam Nazarov",
    date: "2026-03-26",
    startTime: "09:00",
    endTime: "10:30",
    status: "upcoming",
    materials: [],
    isLive: false,
    meetingUrl: "https://teams.microsoft.com/meet/math204",
  },
  {
    id: "lec-013",
    courseId: "crs-003",
    courseName: "Database Systems",
    moduleId: "mod-006",
    title: "Relational Model",
    description: "Relations, attributes, keys, integrity constraints, relational algebra.",
    teacherName: "Prof. Ivan Petrenko",
    date: "2026-03-03",
    startTime: "14:00",
    endTime: "15:30",
    status: "completed",
    attendanceStatus: "present",
    materials: [],
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-014",
    courseId: "crs-003",
    courseName: "Database Systems",
    moduleId: "mod-006",
    title: "Entity-Relationship Modeling",
    description: "ER diagrams, entities, relationships, attributes, conversion to relational schema.",
    teacherName: "Prof. Ivan Petrenko",
    date: "2026-03-10",
    startTime: "14:00",
    endTime: "15:30",
    status: "completed",
    attendanceStatus: "absent",
    materials: [],
    recordingUrl: "#",
    isLive: false,
  },
  {
    id: "lec-015",
    courseId: "crs-003",
    courseName: "Database Systems",
    moduleId: "mod-007",
    title: "SQL Fundamentals",
    description: "SELECT, INSERT, UPDATE, DELETE. JOINs, subqueries, GROUP BY, HAVING.",
    teacherName: "Prof. Ivan Petrenko",
    date: "2026-03-25",
    startTime: "14:00",
    endTime: "15:30",
    status: "upcoming",
    materials: [],
    isLive: false,
    meetingUrl: "https://teams.microsoft.com/meet/cs312",
  },
];

// ─── Assignments ───────────────────────────────────────────────────────────────

export const mockAssignments: Assignment[] = [
  {
    id: "asg-001",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    title: "Assignment 1 — Sorting Implementations",
    description:
      "Implement Merge Sort and Quick Sort in Python. Benchmark with datasets of size 1K, 10K, 100K. Plot time complexity.",
    dueDate: "2026-03-10T23:59:00",
    status: "graded",
    maxScore: 100,
    score: 85,
    weight: 6,
    submittedAt: "2026-03-09T22:14:00",
    feedback:
      "Good implementation. Quick sort pivot selection could be improved — consider median-of-three. Benchmarking graphs are clear.",
    rubric: [
      { id: "rub-001", criterion: "Correct Merge Sort implementation", maxPoints: 30, earnedPoints: 30 },
      { id: "rub-002", criterion: "Correct Quick Sort implementation", maxPoints: 30, earnedPoints: 25, feedback: "Pivot selection is naive — worst case O(n²) on sorted input." },
      { id: "rub-003", criterion: "Benchmarking with 3 dataset sizes", maxPoints: 20, earnedPoints: 20 },
      { id: "rub-004", criterion: "Analysis and plots quality", maxPoints: 20, earnedPoints: 10, feedback: "Plots are present but missing proper axis labels." },
    ],
    maxAttempts: 1,
    currentAttempt: 1,
    latePolicy: "10% penalty per day late, maximum 3 days.",
  },
  {
    id: "asg-002",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    title: "Assignment 2 — BST Operations",
    description:
      "Implement a Binary Search Tree with insert, delete, search, and all traversal methods. Write unit tests.",
    dueDate: "2026-03-28T23:59:00",
    status: "in_progress",
    maxScore: 100,
    weight: 6,
    rubric: [
      { id: "rub-005", criterion: "Insert, delete, search operations", maxPoints: 40 },
      { id: "rub-006", criterion: "In-order, pre-order, post-order traversals", maxPoints: 30 },
      { id: "rub-007", criterion: "Unit tests coverage ≥ 80%", maxPoints: 30 },
    ],
    maxAttempts: 2,
    currentAttempt: 0,
    latePolicy: "10% penalty per day late, maximum 3 days.",
  },
  {
    id: "asg-003",
    courseId: "crs-002",
    courseName: "Linear Algebra",
    title: "Problem Set 3 — Eigenvalues",
    description:
      "Solve 12 problems on eigenvalues, eigenvectors, diagonalization, and PCA. Show all work.",
    dueDate: "2026-03-27T23:59:00",
    status: "not_started",
    maxScore: 100,
    weight: 11,
    rubric: [
      { id: "rub-008", criterion: "Eigenvalue computation (4 problems)", maxPoints: 40 },
      { id: "rub-009", criterion: "Diagonalization (4 problems)", maxPoints: 35 },
      { id: "rub-010", criterion: "PCA application problem", maxPoints: 25 },
    ],
    latePolicy: "No late submissions accepted.",
  },
  {
    id: "asg-004",
    courseId: "crs-003",
    courseName: "Database Systems",
    title: "Lab 2 — SQL Queries",
    description:
      "Write 15 SQL queries against the provided university database schema. Includes JOINs, aggregations, and subqueries.",
    dueDate: "2026-04-04T23:59:00",
    status: "not_started",
    maxScore: 100,
    weight: 13,
    rubric: [
      { id: "rub-011", criterion: "Basic SELECT queries (5)", maxPoints: 25 },
      { id: "rub-012", criterion: "JOIN queries (5)", maxPoints: 35 },
      { id: "rub-013", criterion: "Aggregation & subqueries (5)", maxPoints: 40 },
    ],
    latePolicy: "5% penalty per day, maximum 5 days.",
  },
  {
    id: "asg-005",
    courseId: "crs-004",
    courseName: "Technical Writing",
    title: "Essay — AI in Higher Education",
    description:
      "Write a 1500-word argumentative essay on the impact of AI tools on academic integrity in higher education. APA format.",
    dueDate: "2026-03-22T23:59:00",
    status: "submitted",
    maxScore: 100,
    weight: 17,
    submittedAt: "2026-03-22T19:30:00",
    rubric: [
      { id: "rub-014", criterion: "Argument clarity and structure", maxPoints: 35 },
      { id: "rub-015", criterion: "Evidence and citations (APA)", maxPoints: 30 },
      { id: "rub-016", criterion: "Writing quality and style", maxPoints: 25 },
      { id: "rub-017", criterion: "Word count and formatting", maxPoints: 10 },
    ],
    latePolicy: "Late submissions accepted up to 48h, -20% penalty.",
  },
  {
    id: "asg-006",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    title: "Assignment 0 — Complexity Analysis",
    description: "Analyze time and space complexity of 10 given code snippets. Justify each answer.",
    dueDate: "2026-02-28T23:59:00",
    status: "graded",
    maxScore: 50,
    score: 47,
    weight: 3,
    submittedAt: "2026-02-27T18:00:00",
    feedback: "Excellent work. Minor error in problem 7 — O(n log n) not O(n²).",
    rubric: [
      { id: "rub-018", criterion: "Correct complexity analysis (10 problems)", maxPoints: 50, earnedPoints: 47 },
    ],
    maxAttempts: 1,
    currentAttempt: 1,
  },
];

// ─── Exams ─────────────────────────────────────────────────────────────────────

export const mockExams: Exam[] = [
  {
    id: "exm-001",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    type: "midterm",
    title: "CS301 Midterm Exam",
    date: "2026-04-08",
    startTime: "10:00",
    endTime: "11:30",
    durationMinutes: 90,
    status: "eligible",
    totalQuestions: 30,
    maxScore: 100,
    location: "Hall A, Room 201",
    eligibility: {
      attendanceMet: true,
      attendanceRequired: 75,
      attendanceActual: 88,
      debtFree: true,
      prerequisitesDone: true,
      prerequisites: ["Assignment 0", "Assignment 1"],
      overrideGranted: false,
      isEligible: true,
    },
  },
  {
    id: "exm-002",
    courseId: "crs-002",
    courseName: "Linear Algebra",
    type: "midterm",
    title: "MATH204 Midterm Exam",
    date: "2026-04-10",
    startTime: "09:00",
    endTime: "10:30",
    durationMinutes: 90,
    status: "eligible",
    totalQuestions: 20,
    maxScore: 100,
    location: "Hall B, Room 105",
    eligibility: {
      attendanceMet: true,
      attendanceRequired: 75,
      attendanceActual: 95,
      debtFree: true,
      prerequisitesDone: true,
      prerequisites: ["Problem Set 1", "Problem Set 2"],
      overrideGranted: false,
      isEligible: true,
    },
  },
  {
    id: "exm-003",
    courseId: "crs-003",
    courseName: "Database Systems",
    type: "midterm",
    title: "CS312 Midterm Exam",
    date: "2026-04-12",
    startTime: "14:00",
    endTime: "15:30",
    durationMinutes: 90,
    status: "ineligible",
    totalQuestions: 25,
    maxScore: 100,
    location: "Hall A, Room 305",
    eligibility: {
      attendanceMet: false,
      attendanceRequired: 75,
      attendanceActual: 75,
      debtFree: true,
      prerequisitesDone: false,
      prerequisites: ["Lab 1"],
      overrideGranted: false,
      isEligible: false,
    },
  },
  {
    id: "exm-004",
    courseId: "crs-005",
    courseName: "Operating Systems",
    type: "final",
    title: "CS210 Final Exam",
    date: "2025-12-20",
    startTime: "10:00",
    endTime: "12:00",
    durationMinutes: 120,
    status: "completed",
    totalQuestions: 40,
    score: 82,
    maxScore: 100,
    eligibility: {
      attendanceMet: true,
      attendanceRequired: 75,
      attendanceActual: 91,
      debtFree: true,
      prerequisitesDone: true,
      prerequisites: [],
      overrideGranted: false,
      isEligible: true,
    },
  },
];

// ─── Exam Session ──────────────────────────────────────────────────────────────

export const mockExamSession: { questions: ExamQuestion[]; durationMinutes: number } = {
  durationMinutes: 90,
  questions: [
    {
      id: "eq-001",
      text: "What is the time complexity of Merge Sort in the worst case?",
      type: "multiple_choice",
      options: [
        { id: "eq1-a", label: "O(n)" },
        { id: "eq1-b", label: "O(n log n)" },
        { id: "eq1-c", label: "O(n²)" },
        { id: "eq1-d", label: "O(log n)" },
      ],
      points: 3,
    },
    {
      id: "eq-002",
      text: "Which data structure is used in BFS traversal of a graph?",
      type: "multiple_choice",
      options: [
        { id: "eq2-a", label: "Stack" },
        { id: "eq2-b", label: "Queue" },
        { id: "eq2-c", label: "Priority Queue" },
        { id: "eq2-d", label: "Deque" },
      ],
      points: 3,
    },
    {
      id: "eq-003",
      text: "What is the height of a balanced AVL tree with n nodes?",
      type: "multiple_choice",
      options: [
        { id: "eq3-a", label: "O(n)" },
        { id: "eq3-b", label: "O(log n)" },
        { id: "eq3-c", label: "O(√n)" },
        { id: "eq3-d", label: "O(n log n)" },
      ],
      points: 3,
    },
    {
      id: "eq-004",
      text: "In Quick Sort, what is the time complexity of the worst case?",
      type: "multiple_choice",
      options: [
        { id: "eq4-a", label: "O(n log n)" },
        { id: "eq4-b", label: "O(n)" },
        { id: "eq4-c", label: "O(n²)" },
        { id: "eq4-d", label: "O(log n)" },
      ],
      points: 3,
    },
    {
      id: "eq-005",
      text: "Which of the following is NOT a self-balancing binary search tree?",
      type: "multiple_choice",
      options: [
        { id: "eq5-a", label: "AVL Tree" },
        { id: "eq5-b", label: "Red-Black Tree" },
        { id: "eq5-c", label: "B-Tree" },
        { id: "eq5-d", label: "Binary Heap" },
      ],
      points: 3,
    },
    {
      id: "eq-006",
      text: "Explain the difference between DFS and BFS. When would you prefer DFS over BFS?",
      type: "short_answer",
      points: 10,
    },
    {
      id: "eq-007",
      text: "Describe the concept of Dynamic Programming and explain the Overlapping Subproblems property with an example.",
      type: "essay",
      points: 15,
    },
  ],
};

// ─── Grades ────────────────────────────────────────────────────────────────────

export const mockGrades: Grade[] = [
  {
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    credits: 5,
    items: [
      { id: "gi-001", name: "Assignment 0", type: "assignment", weight: 3, score: 47, maxScore: 50, gradedAt: "2026-03-01" },
      { id: "gi-002", name: "Assignment 1", type: "assignment", weight: 6, score: 85, maxScore: 100, gradedAt: "2026-03-12" },
      { id: "gi-003", name: "Participation", type: "participation", weight: 10, score: 8, maxScore: 10, gradedAt: "2026-03-20" },
    ],
    totalScore: 78,
    letterGrade: "B+",
    gpaPoints: 3.3,
  },
  {
    courseId: "crs-002",
    courseName: "Linear Algebra",
    courseCode: "MATH204",
    credits: 4,
    items: [
      { id: "gi-004", name: "Problem Set 1", type: "assignment", weight: 12, score: 92, maxScore: 100, gradedAt: "2026-02-20" },
      { id: "gi-005", name: "Problem Set 2", type: "assignment", weight: 12, score: 88, maxScore: 100, gradedAt: "2026-03-10" },
      { id: "gi-006", name: "Quiz 1", type: "quiz", weight: 11, score: 80, maxScore: 100, gradedAt: "2026-03-05" },
    ],
    totalScore: 87,
    letterGrade: "A-",
    gpaPoints: 3.7,
  },
  {
    courseId: "crs-003",
    courseName: "Database Systems",
    courseCode: "CS312",
    credits: 4,
    items: [
      { id: "gi-007", name: "Lab 1", type: "assignment", weight: 13, score: 70, maxScore: 100, gradedAt: "2026-03-15" },
      { id: "gi-008", name: "Participation", type: "participation", weight: 5, score: 4, maxScore: 5, gradedAt: "2026-03-20" },
    ],
    totalScore: 72,
    letterGrade: "B",
    gpaPoints: 3.0,
  },
  {
    courseId: "crs-004",
    courseName: "Technical Writing",
    courseCode: "ENG201",
    credits: 2,
    items: [
      { id: "gi-009", name: "Essay 1", type: "assignment", weight: 17, score: 95, maxScore: 100, gradedAt: "2026-03-01" },
      { id: "gi-010", name: "Presentation", type: "assignment", weight: 15, score: 90, maxScore: 100, gradedAt: "2026-03-15" },
      { id: "gi-011", name: "Participation", type: "participation", weight: 10, score: 9, maxScore: 10, gradedAt: "2026-03-20" },
    ],
    totalScore: 93,
    letterGrade: "A",
    gpaPoints: 4.0,
  },
  {
    courseId: "crs-005",
    courseName: "Operating Systems",
    courseCode: "CS210",
    credits: 5,
    items: [
      { id: "gi-012", name: "Midterm Exam", type: "midterm", weight: 35, score: 85, maxScore: 100, gradedAt: "2025-11-10" },
      { id: "gi-013", name: "Final Exam", type: "final", weight: 40, score: 82, maxScore: 100, gradedAt: "2025-12-22" },
      { id: "gi-014", name: "Assignments (avg)", type: "assignment", weight: 25, score: 92, maxScore: 100, gradedAt: "2025-12-20" },
    ],
    totalScore: 88,
    letterGrade: "A-",
    gpaPoints: 3.7,
  },
];

// ─── Attendance ────────────────────────────────────────────────────────────────

export const mockAttendanceRecords: AttendanceRecord[] = [
  { id: "att-001", lectureId: "lec-001", courseId: "crs-001", courseName: "Algorithms & Data Structures", lectureTitle: "Introduction to Sorting", date: "2026-02-18", status: "present", joinTime: "09:58", leaveTime: "11:32", duration: 94 },
  { id: "att-002", lectureId: "lec-002", courseId: "crs-001", courseName: "Algorithms & Data Structures", lectureTitle: "Merge Sort & Quick Sort", date: "2026-02-25", status: "present", joinTime: "10:01", leaveTime: "11:30", duration: 89 },
  { id: "att-003", lectureId: "lec-003", courseId: "crs-001", courseName: "Algorithms & Data Structures", lectureTitle: "Heap Sort & Counting Sort", date: "2026-03-04", status: "absent" },
  { id: "att-004", lectureId: "lec-004", courseId: "crs-001", courseName: "Algorithms & Data Structures", lectureTitle: "Binary Search Trees", date: "2026-03-11", status: "present", joinTime: "10:00", leaveTime: "11:30", duration: 90 },
  { id: "att-005", lectureId: "lec-005", courseId: "crs-001", courseName: "Algorithms & Data Structures", lectureTitle: "AVL Trees & Red-Black Trees", date: "2026-03-18", status: "present", joinTime: "09:55", leaveTime: "11:30", duration: 95 },
  { id: "att-006", lectureId: "lec-009", courseId: "crs-002", courseName: "Linear Algebra", lectureTitle: "Vectors & Vector Spaces", date: "2026-03-04", status: "present", joinTime: "08:59", leaveTime: "10:30", duration: 91 },
  { id: "att-007", lectureId: "lec-010", courseId: "crs-002", courseName: "Linear Algebra", lectureTitle: "Matrix Operations", date: "2026-03-11", status: "late", joinTime: "09:22", leaveTime: "10:30", duration: 68 },
  { id: "att-008", lectureId: "lec-011", courseId: "crs-002", courseName: "Linear Algebra", lectureTitle: "Eigenvalues & Eigenvectors", date: "2026-03-24", status: "present", joinTime: "09:00", leaveTime: "10:30", duration: 90 },
  { id: "att-009", lectureId: "lec-013", courseId: "crs-003", courseName: "Database Systems", lectureTitle: "Relational Model", date: "2026-03-03", status: "present", joinTime: "14:00", leaveTime: "15:30", duration: 90 },
  { id: "att-010", lectureId: "lec-014", courseId: "crs-003", courseName: "Database Systems", lectureTitle: "Entity-Relationship Modeling", date: "2026-03-10", status: "absent" },
];

export const mockCourseAttendance: CourseAttendanceSummary[] = [
  { courseId: "crs-001", courseName: "Algorithms & Data Structures", totalLectures: 15, attended: 12, missed: 2, late: 1, excused: 0, rate: 88, threshold: 75 },
  { courseId: "crs-002", courseName: "Linear Algebra", totalLectures: 10, attended: 9, missed: 0, late: 1, excused: 0, rate: 95, threshold: 75 },
  { courseId: "crs-003", courseName: "Database Systems", totalLectures: 9, attended: 6, missed: 2, late: 1, excused: 0, rate: 75, threshold: 75 },
  { courseId: "crs-004", courseName: "Technical Writing", totalLectures: 10, attended: 10, missed: 0, late: 0, excused: 0, rate: 100, threshold: 70 },
];

// ─── Finances ──────────────────────────────────────────────────────────────────

export const mockPayments: Payment[] = [
  {
    id: "pay-001",
    description: "Tuition — Semester 3 (Fall 2025)",
    amount: 2500,
    currency: "USD",
    dueDate: "2025-09-01",
    paidDate: "2025-08-28",
    status: "paid",
    method: "bank_transfer",
    semester: "Fall 2025",
  },
  {
    id: "pay-002",
    description: "Tuition — Semester 4 (Spring 2026), 1st installment",
    amount: 1500,
    currency: "USD",
    dueDate: "2026-02-01",
    paidDate: "2026-01-30",
    status: "paid",
    method: "card",
    semester: "Spring 2026",
  },
  {
    id: "pay-003",
    description: "Tuition — Semester 4 (Spring 2026), 2nd installment",
    amount: 1500,
    currency: "USD",
    dueDate: "2026-04-01",
    status: "pending",
    semester: "Spring 2026",
  },
  {
    id: "pay-004",
    description: "Library & Lab Fee — Spring 2026",
    amount: 200,
    currency: "USD",
    dueDate: "2026-03-01",
    paidDate: "2026-03-01",
    status: "paid",
    method: "card",
    semester: "Spring 2026",
  },
  {
    id: "pay-005",
    description: "Dormitory — March 2026",
    amount: 400,
    currency: "USD",
    dueDate: "2026-03-05",
    paidDate: "2026-03-04",
    status: "paid",
    method: "bank_transfer",
    semester: "Spring 2026",
  },
  {
    id: "pay-006",
    description: "Dormitory — April 2026",
    amount: 400,
    currency: "USD",
    dueDate: "2026-04-05",
    status: "pending",
    semester: "Spring 2026",
  },
];

export const mockFinancialSummary: FinancialSummary = {
  totalOwed: 6500,
  totalPaid: 4600,
  currentDebt: 1900,
  nextPaymentDate: "2026-04-01",
  nextPaymentAmount: 1500,
  currency: "USD",
};

// ─── Notifications ─────────────────────────────────────────────────────────────

export const mockNotifications: StudentNotification[] = [
  {
    id: "sn-001",
    type: "lecture",
    title: "Lecture starting in 15 minutes",
    message: "Eigenvalues & Eigenvectors (Linear Algebra) starts at 09:00. Join the Teams meeting.",
    timestamp: "2026-03-24T08:45:00Z",
    read: false,
    actionHref: "/student/lectures/lec-011",
    priority: "urgent",
  },
  {
    id: "sn-002",
    type: "grade",
    title: "Assignment graded",
    message: "Assignment 1 — Sorting Implementations has been graded. Score: 85/100.",
    timestamp: "2026-03-12T15:30:00Z",
    read: false,
    actionHref: "/student/assignments/asg-001",
    priority: "normal",
  },
  {
    id: "sn-003",
    type: "assignment",
    title: "New assignment posted",
    message: "Problem Set 3 — Eigenvalues has been posted in Linear Algebra. Due: March 27.",
    timestamp: "2026-03-22T09:00:00Z",
    read: false,
    actionHref: "/student/assignments/asg-003",
    priority: "normal",
  },
  {
    id: "sn-004",
    type: "exam",
    title: "Exam schedule confirmed",
    message: "CS301 Midterm Exam is scheduled for April 8 at 10:00 in Hall A, Room 201.",
    timestamp: "2026-03-20T10:00:00Z",
    read: true,
    actionHref: "/student/exams",
    priority: "normal",
  },
  {
    id: "sn-005",
    type: "attendance",
    title: "Low attendance warning — Database Systems",
    message: "Your attendance in CS312 is at 75%, which is the minimum threshold. Missing any more lectures may affect exam eligibility.",
    timestamp: "2026-03-18T08:00:00Z",
    read: false,
    actionHref: "/student/attendance",
    priority: "urgent",
  },
  {
    id: "sn-006",
    type: "finance",
    title: "Payment reminder",
    message: "Tuition 2nd installment ($1,500) is due on April 1, 2026. Please ensure timely payment to avoid account restrictions.",
    timestamp: "2026-03-15T09:00:00Z",
    read: true,
    actionHref: "/student/finance",
    priority: "normal",
  },
  {
    id: "sn-007",
    type: "grade",
    title: "Teacher replied to your Q&A question",
    message: "Prof. Volkova answered your question about AVL rotations in lecture 'AVL Trees & Red-Black Trees'.",
    timestamp: "2026-03-19T14:20:00Z",
    read: true,
    actionHref: "/student/lectures/lec-005",
    priority: "normal",
  },
  {
    id: "sn-008",
    type: "system",
    title: "Schedule updated",
    message: "Linear Algebra lecture on March 26 has been moved to Room 210. Meeting URL remains the same.",
    timestamp: "2026-03-23T16:00:00Z",
    read: false,
    actionHref: "/student/schedule",
    priority: "normal",
  },
];

// ─── Schedule Events ───────────────────────────────────────────────────────────

export const mockScheduleEvents: ScheduleEvent[] = [
  { id: "se-001", type: "lecture", title: "Algorithms: Graph Representations & BFS", courseId: "crs-001", courseName: "Algorithms & Data Structures", date: "2026-03-25", startTime: "10:00", endTime: "11:30", meetingUrl: "https://teams.microsoft.com/meet/cs301", color: "#4f46e5" },
  { id: "se-002", type: "lecture", title: "DB Systems: SQL Fundamentals", courseId: "crs-003", courseName: "Database Systems", date: "2026-03-25", startTime: "14:00", endTime: "15:30", meetingUrl: "https://teams.microsoft.com/meet/cs312", color: "#0891b2" },
  { id: "se-003", type: "lecture", title: "Linear Algebra: SVD", courseId: "crs-002", courseName: "Linear Algebra", date: "2026-03-26", startTime: "09:00", endTime: "10:30", meetingUrl: "https://teams.microsoft.com/meet/math204", color: "#059669" },
  { id: "se-004", type: "lecture", title: "Algorithms: DFS & Topological Sort", courseId: "crs-001", courseName: "Algorithms & Data Structures", date: "2026-03-26", startTime: "10:00", endTime: "11:30", meetingUrl: "https://teams.microsoft.com/meet/cs301", color: "#4f46e5" },
  { id: "se-005", type: "lecture", title: "Technical Writing: Presentation Skills", courseId: "crs-004", courseName: "Technical Writing", date: "2026-03-26", startTime: "16:00", endTime: "17:30", meetingUrl: "https://teams.microsoft.com/meet/eng201", color: "#d97706" },
  { id: "se-006", type: "assignment_due", title: "Algorithms: BST Operations due", courseId: "crs-001", courseName: "Algorithms & Data Structures", date: "2026-03-28", startTime: "23:59", endTime: "23:59", color: "#dc2626" },
  { id: "se-007", type: "assignment_due", title: "Linear Algebra: Problem Set 3 due", courseId: "crs-002", courseName: "Linear Algebra", date: "2026-03-27", startTime: "23:59", endTime: "23:59", color: "#dc2626" },
  { id: "se-008", type: "lecture", title: "Algorithms: Dynamic Programming Intro", courseId: "crs-001", courseName: "Algorithms & Data Structures", date: "2026-04-01", startTime: "10:00", endTime: "11:30", meetingUrl: "https://teams.microsoft.com/meet/cs301", color: "#4f46e5" },
  { id: "se-009", type: "lecture", title: "Linear Algebra: Applications", courseId: "crs-002", courseName: "Linear Algebra", date: "2026-04-02", startTime: "09:00", endTime: "10:30", meetingUrl: "https://teams.microsoft.com/meet/math204", color: "#059669" },
  { id: "se-010", type: "assignment_due", title: "DB Systems: SQL Queries Lab due", courseId: "crs-003", courseName: "Database Systems", date: "2026-04-04", startTime: "23:59", endTime: "23:59", color: "#dc2626" },
  { id: "se-011", type: "exam", title: "CS301 Midterm Exam", courseId: "crs-001", courseName: "Algorithms & Data Structures", date: "2026-04-08", startTime: "10:00", endTime: "11:30", location: "Hall A, Room 201", color: "#7c3aed" },
  { id: "se-012", type: "exam", title: "MATH204 Midterm Exam", courseId: "crs-002", courseName: "Linear Algebra", date: "2026-04-10", startTime: "09:00", endTime: "10:30", location: "Hall B, Room 105", color: "#7c3aed" },
  { id: "se-013", type: "exam", title: "CS312 Midterm Exam", courseId: "crs-003", courseName: "Database Systems", date: "2026-04-12", startTime: "14:00", endTime: "15:30", location: "Hall A, Room 305", color: "#7c3aed" },
  { id: "se-014", type: "lecture", title: "Algorithms: Midterm Review", courseId: "crs-001", courseName: "Algorithms & Data Structures", date: "2026-04-05", startTime: "10:00", endTime: "11:30", meetingUrl: "https://teams.microsoft.com/meet/cs301", color: "#4f46e5" },
  { id: "se-015", type: "lecture", title: "Linear Algebra: Midterm Review", courseId: "crs-002", courseName: "Linear Algebra", date: "2026-04-07", startTime: "09:00", endTime: "10:30", meetingUrl: "https://teams.microsoft.com/meet/math204", color: "#059669" },
  { id: "se-016", type: "lecture", title: "Eigenvalues & Eigenvectors (LIVE NOW)", courseId: "crs-002", courseName: "Linear Algebra", date: "2026-03-24", startTime: "09:00", endTime: "10:30", meetingUrl: "https://teams.microsoft.com/meet/math204", color: "#059669" },
];

// ─── Q&A Messages ──────────────────────────────────────────────────────────────

export const mockQAMessages: QAMessage[] = [
  {
    id: "qa-001",
    lectureId: "lec-005",
    authorName: "Amir Saidov",
    authorRole: "student",
    content: "Can you clarify when to use an AVL tree vs. a Red-Black tree in practice? They seem to have similar performance.",
    timestamp: "2026-03-18T11:45:00Z",
    upvotes: 12,
    isAccepted: false,
  },
  {
    id: "qa-002",
    lectureId: "lec-005",
    authorName: "Prof. Elena Volkova",
    authorRole: "teacher",
    content: "Great question! AVL trees are more strictly balanced, so lookups are slightly faster (good for read-heavy workloads). Red-Black trees have faster insertions/deletions because they require fewer rotations. In most standard library implementations (like Java's TreeMap), Red-Black trees are preferred for general-purpose use. Use AVL when you need optimal search time and your data is relatively static.",
    timestamp: "2026-03-19T14:20:00Z",
    parentId: "qa-001",
    upvotes: 18,
    isAccepted: true,
  },
  {
    id: "qa-003",
    lectureId: "lec-005",
    authorName: "Dina Karimova",
    authorRole: "student",
    content: "Is there a scenario where neither AVL nor Red-Black trees would be appropriate?",
    timestamp: "2026-03-18T12:00:00Z",
    upvotes: 7,
    isAccepted: false,
  },
  {
    id: "qa-004",
    lectureId: "lec-005",
    authorName: "Prof. Elena Volkova",
    authorRole: "teacher",
    content: "Yes! For disk-based storage or databases, B-trees and B+ trees are preferred because they minimize disk I/O by keeping more keys per node, reducing tree height. Also, for approximate lookups, skip lists or treaps can be simpler to implement and tune.",
    timestamp: "2026-03-19T14:35:00Z",
    parentId: "qa-003",
    upvotes: 9,
    isAccepted: true,
  },
];

// ─── Live Chat Messages ────────────────────────────────────────────────────────

export const mockChatMessages: ChatMessage[] = [
  { id: "cm-001", authorName: "Amir Saidov", content: "Good morning everyone!", timestamp: "2026-03-24T08:55:00Z" },
  { id: "cm-002", authorName: "Dina Karimova", content: "Morning! Ready for eigenvalues 😅", timestamp: "2026-03-24T08:56:00Z" },
  { id: "cm-003", authorName: "Dr. Rustam Nazarov", content: "Welcome everyone! We'll start in 3 minutes. Make sure your video is on.", timestamp: "2026-03-24T08:57:00Z" },
  { id: "cm-004", authorName: "Timur Yusupov", content: "Quick question — will today's lecture cover PCA applications?", timestamp: "2026-03-24T08:58:00Z" },
  { id: "cm-005", authorName: "Dr. Rustam Nazarov", content: "Yes, we'll briefly touch on PCA at the end if time permits. It's mainly covered next lecture.", timestamp: "2026-03-24T08:59:00Z" },
];
