import type {
  TeacherProfile,
  TeacherCourse,
  CourseModule,
  TeacherLecture,
  EnrolledStudent,
  LectureAttendance,
  GradebookColumn,
  GradebookRow,
  TeacherAssignment,
  StudentSubmission,
  TeacherExam,
  QAQuestion,
  ChatMessage,
  MaterialComment,
  AQADReview,
  CorrectiveAction,
  TeacherNotification,
  ScheduleEvent,
} from "@/types/teacher";

// ─── Teacher Profile ──────────────────────────────────────────────────────────

export const mockTeacherProfile: TeacherProfile = {
  id: "tch-001",
  name: "Dr. Elena Volkova",
  email: "e.volkova@uou.edu",
  employeeId: "EMP-2019-042",
  department: "Computer Science",
  title: "Associate Professor",
  faculty: "Faculty of Engineering & Technology",
  joinDate: "2019-09-01",
  phone: "+998 90 123 45 67",
  bio: "Associate Professor specializing in algorithms, data structures, and software engineering. 10 years of teaching experience with focus on active learning methodologies.",
  kpi: {
    avgAttendance: 84,
    avgStudentRating: 4.6,
    qaSlaPercent: 91,
    aqadFirstPassRate: 87,
  },
  notificationSettings: {
    emailOnNewQuestion: true,
    emailOnSubmission: true,
    emailOnAqadFeedback: true,
    emailLectureReminder: true,
    pushNotifications: true,
  },
};

// ─── Courses ──────────────────────────────────────────────────────────────────

export const mockCourses: TeacherCourse[] = [
  {
    id: "crs-001",
    code: "CS301",
    name: "Algorithms & Data Structures",
    description:
      "Study of fundamental algorithms and data structures including sorting, searching, trees, graphs, and dynamic programming.",
    status: "Published",
    semester: 4,
    year: "2025–2026",
    credits: 5,
    language: "English",
    difficultyLevel: "intermediate",
    learningOutcomes: [
      "Analyze time and space complexity of algorithms",
      "Implement fundamental data structures from scratch",
      "Apply dynamic programming to solve optimization problems",
      "Design graph algorithms for real-world problems",
    ],
    prerequisites: ["CS201 — Programming Fundamentals", "MATH101 — Discrete Mathematics"],
    totalStudents: 42,
    totalLectures: 24,
    completedLectures: 15,
    avgAttendance: 84,
    avgGrade: 76,
    gradingPolicy: [
      { type: "Assignments", weight: 30, description: "6 assignments, best 5 counted" },
      { type: "Midterm Exam", weight: 25, description: "Written, 90 minutes" },
      { type: "Final Exam", weight: 35, description: "Written, 120 minutes" },
      { type: "Attendance", weight: 10, description: "Minimum 75% required" },
    ],
    gradeScale: [
      { letter: "A", minScore: 90, maxScore: 100 },
      { letter: "B", minScore: 75, maxScore: 89 },
      { letter: "C", minScore: 60, maxScore: 74 },
      { letter: "D", minScore: 50, maxScore: 59 },
      { letter: "F", minScore: 0, maxScore: 49 },
    ],
    lateSubmissionPolicy: "Accepted within 48 hours with 20% penalty",
    publishedAt: "2025-09-05",
    lastUpdatedAt: "2026-03-10",
  },
  {
    id: "crs-002",
    code: "CS401",
    name: "Software Engineering Principles",
    description:
      "Software development lifecycle, design patterns, agile methodologies, testing strategies, and team collaboration.",
    status: "Draft",
    semester: 6,
    year: "2025–2026",
    credits: 4,
    language: "English",
    difficultyLevel: "advanced",
    learningOutcomes: [
      "Apply SOLID principles in software design",
      "Lead agile development sprints",
      "Write comprehensive unit and integration tests",
    ],
    prerequisites: ["CS301 — Algorithms & Data Structures"],
    totalStudents: 0,
    totalLectures: 20,
    completedLectures: 0,
    avgAttendance: 0,
    avgGrade: 0,
    gradingPolicy: [
      { type: "Assignments", weight: 25, description: "5 practical assignments" },
      { type: "Group Project", weight: 40, description: "Team project with presentation" },
      { type: "Final Exam", weight: 25, description: "Written, 90 minutes" },
      { type: "Attendance", weight: 10, description: "Minimum 75% required" },
    ],
    gradeScale: [
      { letter: "A", minScore: 90, maxScore: 100 },
      { letter: "B", minScore: 75, maxScore: 89 },
      { letter: "C", minScore: 60, maxScore: 74 },
      { letter: "D", minScore: 50, maxScore: 59 },
      { letter: "F", minScore: 0, maxScore: 49 },
    ],
    lateSubmissionPolicy: "No late submissions accepted",
    lastUpdatedAt: "2026-03-18",
  },
  {
    id: "crs-003",
    code: "CS202",
    name: "Database Management Systems",
    description:
      "Relational database design, SQL, normalization, transactions, indexing, and NoSQL databases.",
    status: "InReview",
    semester: 3,
    year: "2025–2026",
    credits: 4,
    language: "English",
    difficultyLevel: "intermediate",
    learningOutcomes: [
      "Design normalized relational database schemas",
      "Write complex SQL queries and stored procedures",
      "Understand transaction management and concurrency control",
    ],
    prerequisites: ["CS101 — Introduction to Programming"],
    totalStudents: 0,
    totalLectures: 22,
    completedLectures: 0,
    avgAttendance: 0,
    avgGrade: 0,
    gradingPolicy: [
      { type: "Assignments", weight: 30, description: "Lab assignments" },
      { type: "Midterm Exam", weight: 30, description: "Practical SQL exam" },
      { type: "Final Exam", weight: 30, description: "Written + practical" },
      { type: "Attendance", weight: 10, description: "Minimum 75% required" },
    ],
    gradeScale: [
      { letter: "A", minScore: 90, maxScore: 100 },
      { letter: "B", minScore: 75, maxScore: 89 },
      { letter: "C", minScore: 60, maxScore: 74 },
      { letter: "D", minScore: 50, maxScore: 59 },
      { letter: "F", minScore: 0, maxScore: 49 },
    ],
    lateSubmissionPolicy: "Accepted within 24 hours with 10% penalty",
    submittedForReviewAt: "2026-03-15",
    lastUpdatedAt: "2026-03-15",
  },
  {
    id: "crs-004",
    code: "CS150",
    name: "Introduction to Computer Networks",
    description: "Fundamentals of networking, TCP/IP, routing, switching, and network security basics.",
    status: "Rejected",
    semester: 2,
    year: "2025–2026",
    credits: 3,
    language: "English",
    difficultyLevel: "beginner",
    learningOutcomes: [
      "Understand OSI and TCP/IP models",
      "Configure basic network topologies",
      "Analyze network protocols and security vulnerabilities",
    ],
    prerequisites: [],
    totalStudents: 0,
    totalLectures: 18,
    completedLectures: 0,
    avgAttendance: 0,
    avgGrade: 0,
    gradingPolicy: [
      { type: "Assignments", weight: 30, description: "Lab assignments" },
      { type: "Midterm Exam", weight: 30, description: "Written exam" },
      { type: "Final Exam", weight: 30, description: "Written exam" },
      { type: "Attendance", weight: 10, description: "Minimum 75% required" },
    ],
    gradeScale: [
      { letter: "A", minScore: 90, maxScore: 100 },
      { letter: "B", minScore: 75, maxScore: 89 },
      { letter: "C", minScore: 60, maxScore: 74 },
      { letter: "D", minScore: 50, maxScore: 59 },
      { letter: "F", minScore: 0, maxScore: 49 },
    ],
    lateSubmissionPolicy: "Accepted within 48 hours with 15% penalty",
    aqadRemarks: 3,
    submittedForReviewAt: "2026-02-20",
    lastUpdatedAt: "2026-03-01",
  },
  {
    id: "crs-005",
    code: "CS350",
    name: "Machine Learning Fundamentals",
    description:
      "Supervised and unsupervised learning, neural networks, model evaluation, and practical applications.",
    status: "Approved",
    semester: 5,
    year: "2025–2026",
    credits: 5,
    language: "English",
    difficultyLevel: "advanced",
    learningOutcomes: [
      "Implement and evaluate supervised learning models",
      "Apply unsupervised learning for clustering and dimensionality reduction",
      "Build and train neural networks with modern frameworks",
    ],
    prerequisites: ["CS301 — Algorithms & Data Structures", "MATH204 — Linear Algebra"],
    totalStudents: 0,
    totalLectures: 26,
    completedLectures: 0,
    avgAttendance: 0,
    avgGrade: 0,
    gradingPolicy: [
      { type: "Assignments", weight: 30, description: "6 coding assignments" },
      { type: "Midterm Exam", weight: 25, description: "Written + practical" },
      { type: "Final Project", weight: 35, description: "ML project with report" },
      { type: "Attendance", weight: 10, description: "Minimum 75% required" },
    ],
    gradeScale: [
      { letter: "A", minScore: 90, maxScore: 100 },
      { letter: "B", minScore: 75, maxScore: 89 },
      { letter: "C", minScore: 60, maxScore: 74 },
      { letter: "D", minScore: 50, maxScore: 59 },
      { letter: "F", minScore: 0, maxScore: 49 },
    ],
    lateSubmissionPolicy: "Accepted within 72 hours with 25% penalty",
    submittedForReviewAt: "2026-03-05",
    lastUpdatedAt: "2026-03-22",
  },
];

// ─── Modules ──────────────────────────────────────────────────────────────────

export const mockModules: CourseModule[] = [
  {
    id: "mod-001",
    courseId: "crs-001",
    name: "Module 1: Introduction & Complexity",
    description: "Big-O notation, time and space complexity analysis, asymptotic analysis.",
    orderIndex: 1,
    lectureIds: ["lec-001", "lec-002", "lec-003"],
  },
  {
    id: "mod-002",
    courseId: "crs-001",
    name: "Module 2: Sorting & Searching",
    description: "Bubble, merge, quick sort. Binary search trees, heaps.",
    orderIndex: 2,
    lectureIds: ["lec-004", "lec-005", "lec-006"],
  },
  {
    id: "mod-003",
    courseId: "crs-001",
    name: "Module 3: Trees & Graphs",
    description: "BSTs, AVL trees, BFS, DFS, Dijkstra, minimum spanning trees.",
    orderIndex: 3,
    lectureIds: ["lec-007", "lec-008", "lec-009"],
  },
  {
    id: "mod-004",
    courseId: "crs-001",
    name: "Module 4: Dynamic Programming",
    description: "Memoization, tabulation, classic DP problems.",
    orderIndex: 4,
    lectureIds: ["lec-010", "lec-011"],
  },
];

// ─── Lectures ─────────────────────────────────────────────────────────────────

export const mockLectures: TeacherLecture[] = [
  {
    id: "lec-001",
    courseId: "crs-001",
    moduleId: "mod-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    topic: "Introduction to Algorithm Analysis",
    plan: "1. What is an algorithm?\n2. Big-O, Big-Theta, Big-Omega notations\n3. Analyzing simple loops\n4. Space complexity\n5. Practice problems",
    learningOutcomes: [
      "Define Big-O notation and explain its purpose",
      "Analyze time complexity of iterative algorithms",
      "Compare algorithms by their asymptotic behavior",
    ],
    date: "2026-03-10",
    startTime: "10:00",
    endTime: "11:30",
    room: "Room 302",
    status: "completed",
    teamsLink: "https://teams.microsoft.com/l/meetup-join/mock-001",
    teamsRecordingUrl: "https://teams.microsoft.com/l/recording/mock-001",
    attendanceRate: 88,
    materials: [
      {
        id: "mat-001",
        lectureId: "lec-001",
        title: "Algorithm Analysis Slides",
        type: "ppt",
        url: "/materials/algo-analysis.pptx",
        description: "Main lecture slides covering Big-O notation",
        orderIndex: 1,
        versionType: "minor",
        uploadedAt: "2026-03-09",
        fileSize: "2.4 MB",
      },
      {
        id: "mat-002",
        lectureId: "lec-001",
        title: "Practice Problems PDF",
        type: "pdf",
        url: "/materials/practice-complexity.pdf",
        description: "10 practice problems on complexity analysis",
        orderIndex: 2,
        versionType: "minor",
        uploadedAt: "2026-03-09",
        fileSize: "1.1 MB",
      },
    ],
    activities: [
      {
        id: "act-001",
        lectureId: "lec-001",
        type: "quiz",
        title: "Complexity Warm-up Quiz",
        description: "5 MCQ questions on Big-O basics",
        maxScore: 10,
        isRequired: true,
      },
    ],
    qaOpen: false,
    qaCloseAfterHours: 72,
    chatEnabled: true,
    group: "CS-24B",
  },
  {
    id: "lec-002",
    courseId: "crs-001",
    moduleId: "mod-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    topic: "Arrays and Linked Lists",
    plan: "1. Array internals and memory\n2. Singly linked list implementation\n3. Doubly linked list\n4. Time complexity comparison\n5. Coding exercise",
    learningOutcomes: [
      "Implement singly and doubly linked lists",
      "Compare arrays and linked lists for different use cases",
      "Analyze insertion/deletion complexity",
    ],
    date: "2026-03-12",
    startTime: "10:00",
    endTime: "11:30",
    room: "Room 302",
    status: "completed",
    teamsLink: "https://teams.microsoft.com/l/meetup-join/mock-002",
    teamsRecordingUrl: "https://teams.microsoft.com/l/recording/mock-002",
    attendanceRate: 86,
    materials: [
      {
        id: "mat-003",
        lectureId: "lec-002",
        title: "Linked Lists Slides",
        type: "ppt",
        url: "/materials/linked-lists.pptx",
        orderIndex: 1,
        versionType: "minor",
        uploadedAt: "2026-03-11",
        fileSize: "3.2 MB",
      },
    ],
    activities: [
      {
        id: "act-002",
        lectureId: "lec-002",
        type: "assignment",
        title: "Assignment 1: Linked List Implementation",
        description: "Implement a doubly linked list with all CRUD operations",
        maxScore: 100,
        isRequired: true,
      },
    ],
    qaOpen: false,
    qaCloseAfterHours: 72,
    chatEnabled: true,
    group: "CS-24B",
  },
  {
    id: "lec-007",
    courseId: "crs-001",
    moduleId: "mod-003",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    topic: "Binary Search Trees",
    plan: "1. BST definition and properties\n2. Insertion and deletion\n3. Traversal algorithms\n4. Balanced BSTs overview\n5. AVL rotation introduction",
    learningOutcomes: [
      "Implement BST insert, delete, and search operations",
      "Perform in-order, pre-order, and post-order traversals",
      "Explain why balance matters in BSTs",
    ],
    date: "2026-03-24",
    startTime: "10:00",
    endTime: "11:30",
    room: "Room 302",
    status: "live",
    teamsLink: "https://teams.microsoft.com/l/meetup-join/mock-007",
    attendanceRate: undefined,
    materials: [
      {
        id: "mat-007",
        lectureId: "lec-007",
        title: "BST Lecture Slides",
        type: "ppt",
        url: "/materials/bst-slides.pptx",
        orderIndex: 1,
        versionType: "minor",
        uploadedAt: "2026-03-23",
        fileSize: "4.1 MB",
      },
    ],
    activities: [
      {
        id: "act-007",
        lectureId: "lec-007",
        type: "quiz",
        title: "BST Quick Quiz",
        description: "In-lecture quiz on BST operations",
        maxScore: 10,
        isRequired: true,
      },
    ],
    qaOpen: true,
    qaCloseAfterHours: 72,
    chatEnabled: true,
    group: "CS-24B",
  },
  {
    id: "lec-008",
    courseId: "crs-001",
    moduleId: "mod-003",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    topic: "Graph Traversal — BFS & DFS",
    plan: "1. Graph representations\n2. Breadth-first search\n3. Depth-first search\n4. Applications\n5. Practice",
    learningOutcomes: [
      "Implement BFS and DFS for directed and undirected graphs",
      "Apply graph traversal to find connected components",
      "Analyze time and space complexity of BFS and DFS",
    ],
    date: "2026-03-26",
    startTime: "10:00",
    endTime: "11:30",
    room: "Room 302",
    status: "scheduled",
    teamsLink: "https://teams.microsoft.com/l/meetup-join/mock-008",
    materials: [],
    activities: [],
    qaOpen: false,
    qaCloseAfterHours: 72,
    chatEnabled: true,
    group: "CS-24B",
  },
  {
    id: "lec-009",
    courseId: "crs-001",
    moduleId: "mod-003",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    topic: "Shortest Path Algorithms",
    plan: "1. Dijkstra's algorithm\n2. Bellman-Ford\n3. Floyd-Warshall\n4. Applications in routing\n5. Complexity comparison",
    learningOutcomes: [
      "Implement Dijkstra's shortest path algorithm",
      "Compare Dijkstra and Bellman-Ford for different graph types",
    ],
    date: "2026-03-28",
    startTime: "10:00",
    endTime: "11:30",
    room: "Room 302",
    status: "scheduled",
    teamsLink: "https://teams.microsoft.com/l/meetup-join/mock-009",
    materials: [],
    activities: [],
    qaOpen: false,
    qaCloseAfterHours: 72,
    chatEnabled: true,
    group: "CS-24B",
  },
];

// ─── Enrolled Students ────────────────────────────────────────────────────────

export const mockEnrolledStudents: EnrolledStudent[] = [
  {
    id: "stu-001",
    name: "Amir Saidov",
    studentId: "2024-CS-0142",
    group: "CS-24B",
    email: "a.saidov@uou.edu",
    attendanceRate: 88,
    currentGrade: "B+",
    currentScore: 78,
    submittedAssignments: 4,
    totalAssignments: 5,
  },
  {
    id: "stu-002",
    name: "Kamola Rashidova",
    studentId: "2024-CS-0159",
    group: "CS-24B",
    email: "k.rashidova@uou.edu",
    attendanceRate: 95,
    currentGrade: "A",
    currentScore: 92,
    submittedAssignments: 5,
    totalAssignments: 5,
  },
  {
    id: "stu-003",
    name: "Bobur Toshmatov",
    studentId: "2024-CS-0173",
    group: "CS-24B",
    email: "b.toshmatov@uou.edu",
    attendanceRate: 72,
    currentGrade: "C+",
    currentScore: 65,
    submittedAssignments: 3,
    totalAssignments: 5,
  },
  {
    id: "stu-004",
    name: "Nilufar Karimova",
    studentId: "2024-CS-0188",
    group: "CS-24B",
    email: "n.karimova@uou.edu",
    attendanceRate: 91,
    currentGrade: "A-",
    currentScore: 87,
    submittedAssignments: 5,
    totalAssignments: 5,
  },
  {
    id: "stu-005",
    name: "Jasur Mirzayev",
    studentId: "2024-CS-0201",
    group: "CS-24B",
    email: "j.mirzayev@uou.edu",
    attendanceRate: 60,
    currentGrade: "D",
    currentScore: 52,
    submittedAssignments: 2,
    totalAssignments: 5,
  },
  {
    id: "stu-006",
    name: "Zulfiya Nazarova",
    studentId: "2024-CS-0215",
    group: "CS-24B",
    email: "z.nazarova@uou.edu",
    attendanceRate: 79,
    currentGrade: "B",
    currentScore: 75,
    submittedAssignments: 4,
    totalAssignments: 5,
  },
];

// ─── Attendance ───────────────────────────────────────────────────────────────

export const mockLectureAttendance: LectureAttendance[] = [
  {
    lectureId: "lec-001",
    lectureTopic: "Introduction to Algorithm Analysis",
    date: "2026-03-10",
    attendanceRate: 88,
    presentCount: 37,
    totalCount: 42,
    records: [
      {
        studentId: "stu-001",
        studentName: "Amir Saidov",
        entryTime: "10:02",
        exitTime: "11:30",
        duration: 88,
        status: "present",
      },
      {
        studentId: "stu-002",
        studentName: "Kamola Rashidova",
        entryTime: "09:58",
        exitTime: "11:30",
        duration: 92,
        status: "present",
      },
      {
        studentId: "stu-003",
        studentName: "Bobur Toshmatov",
        entryTime: "10:15",
        exitTime: "11:30",
        duration: 75,
        status: "late",
      },
      {
        studentId: "stu-004",
        studentName: "Nilufar Karimova",
        entryTime: "10:00",
        exitTime: "11:30",
        duration: 90,
        status: "present",
      },
      {
        studentId: "stu-005",
        studentName: "Jasur Mirzayev",
        status: "absent",
        absenceReason: "Medical",
      },
      {
        studentId: "stu-006",
        studentName: "Zulfiya Nazarova",
        entryTime: "10:05",
        exitTime: "11:15",
        duration: 70,
        status: "present",
      },
    ],
  },
  {
    lectureId: "lec-002",
    lectureTopic: "Arrays and Linked Lists",
    date: "2026-03-12",
    attendanceRate: 86,
    presentCount: 36,
    totalCount: 42,
    records: [
      {
        studentId: "stu-001",
        studentName: "Amir Saidov",
        entryTime: "10:01",
        exitTime: "11:30",
        duration: 89,
        status: "present",
      },
      {
        studentId: "stu-002",
        studentName: "Kamola Rashidova",
        entryTime: "09:55",
        exitTime: "11:30",
        duration: 95,
        status: "present",
      },
      {
        studentId: "stu-003",
        studentName: "Bobur Toshmatov",
        status: "absent",
      },
      {
        studentId: "stu-004",
        studentName: "Nilufar Karimova",
        entryTime: "10:00",
        exitTime: "11:30",
        duration: 90,
        status: "present",
      },
      {
        studentId: "stu-005",
        studentName: "Jasur Mirzayev",
        status: "absent",
      },
      {
        studentId: "stu-006",
        studentName: "Zulfiya Nazarova",
        entryTime: "10:08",
        exitTime: "11:30",
        duration: 82,
        status: "present",
      },
    ],
  },
];

// ─── Gradebook ────────────────────────────────────────────────────────────────

export const mockGradebookColumns: GradebookColumn[] = [
  { id: "asgn-001", label: "Assignment 1", type: "assignment", maxScore: 100, weight: 6 },
  { id: "asgn-002", label: "Assignment 2", type: "assignment", maxScore: 100, weight: 6 },
  { id: "asgn-003", label: "Assignment 3", type: "assignment", maxScore: 100, weight: 6 },
  { id: "asgn-004", label: "Assignment 4", type: "assignment", maxScore: 100, weight: 6 },
  { id: "asgn-005", label: "Assignment 5", type: "assignment", maxScore: 100, weight: 6 },
  { id: "mid-001", label: "Midterm", type: "midterm", maxScore: 100, weight: 25 },
  { id: "fin-001", label: "Final", type: "final", maxScore: 100, weight: 35 },
  { id: "att-001", label: "Attendance", type: "attendance", maxScore: 100, weight: 10 },
];

export const mockGradebookRows: GradebookRow[] = [
  {
    studentId: "stu-001",
    studentName: "Amir Saidov",
    group: "CS-24B",
    cells: {
      "asgn-001": { columnId: "asgn-001", score: 85, feedback: "Good work!", published: true, submittedAt: "2026-02-05", gradedAt: "2026-02-07", isOverdue: false },
      "asgn-002": { columnId: "asgn-002", score: 78, published: true, submittedAt: "2026-02-19", gradedAt: "2026-02-21", isOverdue: false },
      "asgn-003": { columnId: "asgn-003", score: 90, published: true, submittedAt: "2026-03-04", gradedAt: "2026-03-06", isOverdue: false },
      "asgn-004": { columnId: "asgn-004", score: 72, published: true, submittedAt: "2026-03-18", gradedAt: "2026-03-20", isOverdue: false },
      "asgn-005": { columnId: "asgn-005", score: null, published: false, submittedAt: "2026-03-22", isOverdue: true },
      "mid-001": { columnId: "mid-001", score: 74, published: true, gradedAt: "2026-03-02", isOverdue: false },
      "fin-001": { columnId: "fin-001", score: null, published: false, isOverdue: false },
      "att-001": { columnId: "att-001", score: 88, published: true, isOverdue: false },
    },
    totalScore: 78,
    finalGrade: "B+",
  },
  {
    studentId: "stu-002",
    studentName: "Kamola Rashidova",
    group: "CS-24B",
    cells: {
      "asgn-001": { columnId: "asgn-001", score: 95, published: true, submittedAt: "2026-02-04", gradedAt: "2026-02-07", isOverdue: false },
      "asgn-002": { columnId: "asgn-002", score: 92, published: true, submittedAt: "2026-02-18", gradedAt: "2026-02-21", isOverdue: false },
      "asgn-003": { columnId: "asgn-003", score: 97, published: true, submittedAt: "2026-03-03", gradedAt: "2026-03-06", isOverdue: false },
      "asgn-004": { columnId: "asgn-004", score: 88, published: true, submittedAt: "2026-03-17", gradedAt: "2026-03-20", isOverdue: false },
      "asgn-005": { columnId: "asgn-005", score: null, published: false, submittedAt: "2026-03-21", isOverdue: true },
      "mid-001": { columnId: "mid-001", score: 91, published: true, gradedAt: "2026-03-02", isOverdue: false },
      "fin-001": { columnId: "fin-001", score: null, published: false, isOverdue: false },
      "att-001": { columnId: "att-001", score: 95, published: true, isOverdue: false },
    },
    totalScore: 92,
    finalGrade: "A",
  },
  {
    studentId: "stu-003",
    studentName: "Bobur Toshmatov",
    group: "CS-24B",
    cells: {
      "asgn-001": { columnId: "asgn-001", score: 65, published: true, submittedAt: "2026-02-07", gradedAt: "2026-02-09", isOverdue: false },
      "asgn-002": { columnId: "asgn-002", score: 58, published: true, submittedAt: "2026-02-22", gradedAt: "2026-02-24", isOverdue: false },
      "asgn-003": { columnId: "asgn-003", score: 70, published: true, submittedAt: "2026-03-06", gradedAt: "2026-03-08", isOverdue: false },
      "asgn-004": { columnId: "asgn-004", score: null, published: false, isOverdue: true },
      "asgn-005": { columnId: "asgn-005", score: null, published: false, isOverdue: false },
      "mid-001": { columnId: "mid-001", score: 62, published: true, gradedAt: "2026-03-02", isOverdue: false },
      "fin-001": { columnId: "fin-001", score: null, published: false, isOverdue: false },
      "att-001": { columnId: "att-001", score: 72, published: true, isOverdue: false },
    },
    totalScore: 65,
    finalGrade: "C+",
  },
];

// ─── Assignments ──────────────────────────────────────────────────────────────

export const mockAssignments: TeacherAssignment[] = [
  {
    id: "asgn-001",
    courseId: "crs-001",
    lectureId: "lec-002",
    courseName: "Algorithms & Data Structures",
    lectureTopic: "Arrays and Linked Lists",
    title: "Assignment 1: Linked List Implementation",
    description: "Implement a fully functional doubly linked list in Python or Java.",
    instructions:
      "Implement all CRUD operations: add, remove, search, and display. Include time complexity analysis in comments. Submit as a single .py or .java file.",
    rubrics: [
      {
        id: "rub-001",
        criterion: "Correctness",
        maxScore: 40,
        levels: [
          { label: "Excellent", score: 40, description: "All operations work correctly" },
          { label: "Good", score: 30, description: "Minor bugs in edge cases" },
          { label: "Needs Work", score: 20, description: "Several operations fail" },
          { label: "Incomplete", score: 10, description: "Most operations missing" },
        ],
      },
      {
        id: "rub-002",
        criterion: "Code Quality",
        maxScore: 30,
        levels: [
          { label: "Excellent", score: 30, description: "Clean, well-documented code" },
          { label: "Good", score: 22, description: "Mostly clean with minor issues" },
          { label: "Needs Work", score: 15, description: "Hard to read, few comments" },
          { label: "Incomplete", score: 5, description: "No documentation" },
        ],
      },
      {
        id: "rub-003",
        criterion: "Complexity Analysis",
        maxScore: 30,
        levels: [
          { label: "Excellent", score: 30, description: "Accurate analysis for all ops" },
          { label: "Good", score: 22, description: "Minor errors in analysis" },
          { label: "Needs Work", score: 15, description: "Incomplete analysis" },
          { label: "Missing", score: 0, description: "No analysis provided" },
        ],
      },
    ],
    deadline: "2026-02-19",
    lateSubmissionAllowed: true,
    latePenaltyPercent: 20,
    maxAttempts: 2,
    allowedFileTypes: [".py", ".java"],
    plagiarismCheck: true,
    status: "closed",
    submissionsCount: 38,
    totalStudents: 42,
    gradedCount: 38,
  },
  {
    id: "asgn-005",
    courseId: "crs-001",
    lectureId: "lec-007",
    courseName: "Algorithms & Data Structures",
    lectureTopic: "Binary Search Trees",
    title: "Assignment 5: BST Operations",
    description: "Implement a Binary Search Tree with all standard operations.",
    instructions:
      "Implement insert, delete, search, and all three traversals (in-order, pre-order, post-order). Include a demonstration with at least 10 nodes.",
    rubrics: [
      {
        id: "rub-004",
        criterion: "Correctness",
        maxScore: 50,
        levels: [
          { label: "Excellent", score: 50, description: "All operations correct" },
          { label: "Good", score: 38, description: "Minor issues" },
          { label: "Needs Work", score: 25, description: "Several bugs" },
          { label: "Incomplete", score: 10, description: "Mostly incomplete" },
        ],
      },
      {
        id: "rub-005",
        criterion: "Code Quality",
        maxScore: 30,
        levels: [
          { label: "Excellent", score: 30, description: "Clean code" },
          { label: "Good", score: 22, description: "Mostly clean" },
          { label: "Needs Work", score: 15, description: "Messy" },
          { label: "Incomplete", score: 5, description: "No documentation" },
        ],
      },
      {
        id: "rub-006",
        criterion: "Testing",
        maxScore: 20,
        levels: [
          { label: "Excellent", score: 20, description: "Edge cases covered" },
          { label: "Good", score: 15, description: "Basic tests" },
          { label: "Needs Work", score: 8, description: "Minimal tests" },
          { label: "Missing", score: 0, description: "No tests" },
        ],
      },
    ],
    deadline: "2026-03-28",
    lateSubmissionAllowed: true,
    latePenaltyPercent: 20,
    maxAttempts: 1,
    allowedFileTypes: [".py", ".java", ".cpp"],
    plagiarismCheck: true,
    status: "published",
    submissionsCount: 14,
    totalStudents: 42,
    gradedCount: 0,
  },
];

export const mockSubmissions: StudentSubmission[] = [
  {
    id: "sub-001",
    assignmentId: "asgn-005",
    studentId: "stu-001",
    studentName: "Amir Saidov",
    submittedAt: "2026-03-22T14:30:00",
    status: "submitted",
    files: [
      { name: "bst_solution.py", url: "/submissions/bst_solution_stu001.py", size: "12 KB" },
    ],
    isLate: false,
  },
  {
    id: "sub-002",
    assignmentId: "asgn-005",
    studentId: "stu-002",
    studentName: "Kamola Rashidova",
    submittedAt: "2026-03-21T10:15:00",
    status: "submitted",
    files: [
      { name: "BinarySearchTree.java", url: "/submissions/bst_stu002.java", size: "18 KB" },
    ],
    isLate: false,
  },
  {
    id: "sub-003",
    assignmentId: "asgn-005",
    studentId: "stu-003",
    studentName: "Bobur Toshmatov",
    submittedAt: "2026-03-29T09:00:00",
    status: "late",
    files: [
      { name: "bst.py", url: "/submissions/bst_stu003.py", size: "8 KB" },
    ],
    isLate: true,
  },
];

// ─── Exams ────────────────────────────────────────────────────────────────────

export const mockExams: TeacherExam[] = [
  {
    id: "exam-001",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    type: "midterm",
    date: "2026-03-01",
    startTime: "09:00",
    duration: 90,
    room: "Exam Hall A",
    status: "completed",
    totalStudents: 42,
    eligibleCount: 39,
    questions: [
      {
        id: "q-001",
        text: "What is the time complexity of binary search?",
        type: "multiple_choice",
        options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
        correctAnswer: "O(log n)",
        maxScore: 5,
      },
      {
        id: "q-002",
        text: "Explain the difference between stack and queue data structures.",
        type: "short_answer",
        maxScore: 15,
      },
    ],
    eligibility: [
      {
        studentId: "stu-001",
        studentName: "Amir Saidov",
        attendanceRate: 88,
        assignmentsCompleted: 4,
        totalAssignments: 4,
        isEligible: true,
        ineligibilityReasons: [],
      },
      {
        studentId: "stu-005",
        studentName: "Jasur Mirzayev",
        attendanceRate: 60,
        assignmentsCompleted: 2,
        totalAssignments: 4,
        isEligible: false,
        ineligibilityReasons: ["Attendance below 75%", "Less than 50% assignments completed"],
      },
    ],
    results: [
      {
        studentId: "stu-001",
        studentName: "Amir Saidov",
        score: 74,
        maxScore: 100,
        grade: "B",
        submittedAt: "2026-03-01T10:28:00",
        hasAppeal: false,
      },
      {
        studentId: "stu-002",
        studentName: "Kamola Rashidova",
        score: 91,
        maxScore: 100,
        grade: "A",
        submittedAt: "2026-03-01T10:15:00",
        hasAppeal: false,
      },
      {
        studentId: "stu-003",
        studentName: "Bobur Toshmatov",
        score: 62,
        maxScore: 100,
        grade: "C",
        submittedAt: "2026-03-01T10:30:00",
        hasAppeal: true,
        appealStatus: "pending",
        appealComment: "I believe question 3 was incorrectly graded.",
      },
    ],
  },
  {
    id: "exam-002",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    type: "final",
    date: "2026-05-20",
    startTime: "09:00",
    duration: 120,
    room: "Exam Hall A",
    status: "upcoming",
    totalStudents: 42,
    eligibleCount: 0,
    questions: [],
    eligibility: [],
    results: [],
  },
];

// ─── Q&A ──────────────────────────────────────────────────────────────────────

export const mockQAQuestions: QAQuestion[] = [
  {
    id: "qa-001",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    lectureId: "lec-007",
    lectureTopic: "Binary Search Trees",
    authorId: "stu-001",
    authorName: "Amir Saidov",
    title: "When should I use AVL tree vs regular BST?",
    content:
      "I understand that AVL trees are self-balancing, but when is it practically worth the overhead of maintaining balance? Are there specific use cases where a regular BST is preferred?",
    createdAt: "2026-03-24T11:45:00",
    status: "open",
    votes: 8,
    answers: [],
    isHidden: false,
    authorMuted: false,
    slaDeadline: "2026-03-25T11:45:00",
    slaBreached: false,
  },
  {
    id: "qa-002",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    lectureId: "lec-002",
    lectureTopic: "Arrays and Linked Lists",
    authorId: "stu-003",
    authorName: "Bobur Toshmatov",
    title: "Why is linked list insertion O(1) if we need to traverse to find the position?",
    content:
      "In the lecture, you said linked list insertion is O(1), but if I need to insert at position k, I need to traverse k elements first. Can you clarify?",
    createdAt: "2026-03-12T15:20:00",
    status: "answered",
    votes: 12,
    answers: [
      {
        id: "ans-001",
        questionId: "qa-002",
        authorId: "tch-001",
        authorName: "Dr. Elena Volkova",
        authorRole: "teacher",
        content:
          "Great question! The O(1) insertion time for linked lists assumes you already have a pointer/reference to the node before the insertion point. If you need to find that position first, the overall operation becomes O(n). When we compare with arrays, we're typically comparing the actual insertion (shifting elements vs. pointer manipulation), not including the traversal. Context matters!",
        createdAt: "2026-03-12T16:30:00",
        isAccepted: true,
        isHidden: false,
      },
    ],
    isHidden: false,
    authorMuted: false,
    slaDeadline: "2026-03-13T15:20:00",
    slaBreached: false,
  },
  {
    id: "qa-003",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    lectureId: "lec-001",
    lectureTopic: "Introduction to Algorithm Analysis",
    authorId: "stu-004",
    authorName: "Nilufar Karimova",
    title: "What is the difference between O(n) and Θ(n)?",
    content:
      "I'm confused about the different asymptotic notations. Can you explain when to use Big-O, Big-Theta, and Big-Omega?",
    createdAt: "2026-03-23T09:10:00",
    status: "open",
    votes: 5,
    answers: [],
    isHidden: false,
    authorMuted: false,
    slaDeadline: "2026-03-24T09:10:00",
    slaBreached: true,
  },
];

// ─── Chat Messages ────────────────────────────────────────────────────────────

export const mockChatMessages: ChatMessage[] = [
  {
    id: "chat-001",
    lectureId: "lec-007",
    authorId: "stu-001",
    authorName: "Amir Saidov",
    content: "Can you show the deletion case when the node has two children again?",
    createdAt: "2026-03-24T10:35:00",
    isHidden: false,
    authorMuted: false,
  },
  {
    id: "chat-002",
    lectureId: "lec-007",
    authorId: "stu-002",
    authorName: "Kamola Rashidova",
    content: "This is very clear, thank you!",
    createdAt: "2026-03-24T10:42:00",
    isHidden: false,
    authorMuted: false,
  },
  {
    id: "chat-003",
    lectureId: "lec-007",
    authorId: "stu-005",
    authorName: "Jasur Mirzayev",
    content: "I don't understand in-order traversal...",
    createdAt: "2026-03-24T11:00:00",
    isHidden: false,
    authorMuted: false,
  },
];

export const mockMaterialComments: MaterialComment[] = [
  {
    id: "cmt-001",
    materialId: "mat-001",
    lectureId: "lec-001",
    authorId: "stu-001",
    authorName: "Amir Saidov",
    content: "Slide 15 has a typo — Big-O formula shows n^2 but should be n log n",
    createdAt: "2026-03-10T14:20:00",
    isHidden: false,
  },
  {
    id: "cmt-002",
    materialId: "mat-003",
    lectureId: "lec-002",
    authorId: "stu-004",
    authorName: "Nilufar Karimova",
    content: "Could you add more examples for circular linked lists?",
    createdAt: "2026-03-13T09:45:00",
    isHidden: false,
  },
];

// ─── AQAD Reviews ─────────────────────────────────────────────────────────────

export const mockAQADReviews: AQADReview[] = [
  {
    id: "rev-001",
    courseId: "crs-004",
    courseName: "Introduction to Computer Networks",
    courseCode: "CS150",
    status: "Rejected",
    submittedAt: "2026-02-20",
    reviewedAt: "2026-03-01",
    reviewerName: "Prof. Saidakbar Yusupov",
    checklist: [
      {
        id: "chk-001",
        category: "Learning Outcomes",
        criterion: "Learning outcomes are measurable and aligned with program objectives",
        status: "passed",
      },
      {
        id: "chk-002",
        category: "Content",
        criterion: "Lecture materials cover all stated learning outcomes",
        status: "failed",
        reviewerComment: "Module 3 lacks materials for network security learning outcome",
      },
      {
        id: "chk-003",
        category: "Assessment",
        criterion: "Grading policy is clearly defined and communicated",
        status: "passed",
      },
      {
        id: "chk-004",
        category: "Assessment",
        criterion: "Assessment methods align with learning outcomes",
        status: "needs_revision",
        reviewerComment: "Final exam does not include practical component as stated in course description",
      },
      {
        id: "chk-005",
        category: "Content",
        criterion: "All lectures have required elements (materials + activities)",
        status: "failed",
        reviewerComment: "Lectures 5, 7, and 12 are missing activities",
      },
    ],
    requiredActions: [
      { id: "act-001", description: "Add materials for network security topics in Module 3", isCompleted: false },
      { id: "act-002", description: "Add practical component to final exam design", isCompleted: false },
      { id: "act-003", description: "Add activities to Lectures 5, 7, and 12", isCompleted: false },
    ],
    deadline: "2026-04-01",
    teacherResponse: "",
  },
  {
    id: "rev-002",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    status: "Approved",
    submittedAt: "2025-08-15",
    reviewedAt: "2025-08-28",
    reviewerName: "Prof. Saidakbar Yusupov",
    checklist: [
      {
        id: "chk-006",
        category: "Learning Outcomes",
        criterion: "Learning outcomes are measurable and aligned with program objectives",
        status: "passed",
      },
      {
        id: "chk-007",
        category: "Content",
        criterion: "Lecture materials cover all stated learning outcomes",
        status: "passed",
      },
      {
        id: "chk-008",
        category: "Assessment",
        criterion: "Grading policy is clearly defined and communicated",
        status: "passed",
      },
    ],
    requiredActions: [],
    deadline: undefined,
  },
];

// ─── Corrective Actions ───────────────────────────────────────────────────────

export const mockCorrectiveActions: CorrectiveAction[] = [
  {
    id: "ca-001",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    description: "Average attendance dropped below 75% threshold in Module 3",
    requiredAction:
      "Review lecture engagement strategies. Submit corrective plan with at least 3 specific actions to improve attendance.",
    deadline: "2026-04-05",
    priority: "high",
    status: "pending",
    issuedAt: "2026-03-20",
    aqadVerified: false,
  },
  {
    id: "ca-002",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    description: "Q&A response SLA breached on 5+ occasions in March",
    requiredAction:
      "Improve Q&A response time. Maintain below 24-hour response for all student questions for 30 consecutive days.",
    deadline: "2026-04-15",
    priority: "medium",
    status: "in_progress",
    issuedAt: "2026-03-22",
    aqadVerified: false,
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const mockNotifications: TeacherNotification[] = [
  {
    id: "notif-001",
    type: "qa",
    title: "New unanswered question",
    message: "Nilufar Karimova asked a question in CS301 — SLA breached",
    createdAt: "2026-03-24T09:10:00",
    read: false,
    actionUrl: "/teacher/qa",
  },
  {
    id: "notif-002",
    type: "corrective_action",
    title: "Corrective action issued",
    message: "AQAD issued a corrective action for CS301 — deadline April 5",
    createdAt: "2026-03-20T11:00:00",
    read: false,
    actionUrl: "/teacher/aqad-feedback",
  },
  {
    id: "notif-003",
    type: "aqad",
    title: "Course review rejected",
    message: "CS150 was rejected by AQAD. 3 required actions pending.",
    createdAt: "2026-03-01T14:30:00",
    read: true,
    actionUrl: "/teacher/aqad-feedback",
  },
  {
    id: "notif-004",
    type: "submission",
    title: "New assignment submissions",
    message: "14 students submitted Assignment 5 in CS301",
    createdAt: "2026-03-22T18:00:00",
    read: true,
    actionUrl: "/teacher/assignments",
  },
  {
    id: "notif-005",
    type: "lecture",
    title: "Lecture reminder",
    message: "CS301 lecture 'Binary Search Trees' starts in 24 hours",
    createdAt: "2026-03-23T10:00:00",
    read: true,
    actionUrl: "/teacher/schedule",
  },
  {
    id: "notif-006",
    type: "course",
    title: "Course approved",
    message: "Machine Learning Fundamentals (CS350) was approved by AQAD",
    createdAt: "2026-03-22T09:00:00",
    read: true,
    actionUrl: "/teacher/courses/crs-005",
  },
];

// ─── Schedule ─────────────────────────────────────────────────────────────────

export const mockScheduleEvents: ScheduleEvent[] = [
  {
    id: "sch-001",
    lectureId: "lec-007",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    group: "CS-24B",
    topic: "Binary Search Trees",
    date: "2026-03-24",
    startTime: "10:00",
    endTime: "11:30",
    room: "Room 302",
    type: "lecture",
    status: "live",
  },
  {
    id: "sch-002",
    lectureId: "lec-008",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    group: "CS-24B",
    topic: "Graph Traversal — BFS & DFS",
    date: "2026-03-26",
    startTime: "10:00",
    endTime: "11:30",
    room: "Room 302",
    type: "lecture",
    status: "scheduled",
  },
  {
    id: "sch-003",
    lectureId: "lec-009",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    group: "CS-24B",
    topic: "Shortest Path Algorithms",
    date: "2026-03-28",
    startTime: "10:00",
    endTime: "11:30",
    room: "Room 302",
    type: "lecture",
    status: "scheduled",
  },
  {
    id: "sch-004",
    lectureId: "exam-002",
    courseId: "crs-001",
    courseName: "Algorithms & Data Structures",
    courseCode: "CS301",
    group: "CS-24B",
    topic: "Final Exam",
    date: "2026-05-20",
    startTime: "09:00",
    endTime: "11:00",
    room: "Exam Hall A",
    type: "exam",
    status: "scheduled",
  },
];
